--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘


--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-- Instructions for use

-- 1. Create a folder under the "Worksheets" tab within Snowflake named SDE-Lighthouse-09-Thompson (unless it already exists)
-- 2. For each sql file in the extraction-sql directory, create a worksheet with the same name within the SDE-Lighthouse-09-Thompson folder
-- 3. Copy/paste the contents of each sql file into the matching worksheet
-- 4. Run this worksheet first (to create an empty code set table for this project)
-- 5. Before running the other worksheets you must load the code sets for this project into the code set table:
--    a. From the "Database" menu on the far left hand side, select "Add Data"
--    b. Select "Load data into a Table"
--    c. Browse to select the 0.code-sets.csv file in this directory
--    d. Select the "SDE_REPOSITORY.SHARED_UTILITIES" schema
--    e. Select the table: "Code_Sets_SDE_Lighthouse_09_Thompson" and click "Next"
--    f. Select the file format "Delimited files (CSV/TSV)"
--    g. Double check that the preview looks ok and then click "Load"
-- 6. You can now return to the worksheet folder SDE-Lighthouse-09-Thompson and execute the remaining sql files.

-- Creates the code set table for this project.
DROP TABLE IF EXISTS SDE_REPOSITORY.SHARED_UTILITIES."Code_Sets_SDE_Lighthouse_09_Thompson";
CREATE TABLE SDE_REPOSITORY.SHARED_UTILITIES."Code_Sets_SDE_Lighthouse_09_Thompson" (
	CONCEPT VARCHAR(255),
	VERSION NUMBER(38,0),
	CODE VARCHAR(20),
	DESCRIPTION VARCHAR(255)
);