--┌────────────┐
--│ HbA1c file │
--└────────────┘

------------------------ RDE CHECK -------------------------

-- Cohort is patients included in the DARE study. The below queries produce the data
-- that is required for each patient. However, a filter needs to be applied to only
-- provide this data for patients in the DARE study. Adrian Heald will provide GraphNet
-- with a list of NHS numbers, then they will execute the below but filtered to the list
-- of NHS numbers.

-- We assume that a temporary table will exist as follows:
-- CREATE TABLE #DAREPatients (NhsNo NVARCHAR(30));

-- For each patient in the DARE cohort, this produces all biomarker readings
-- since 2018-01-01.

-- TODO actually we now want 4 columns, so that we can include all bio readings and not just
-- hbA1c readings. We now also include bmi, hba1c, cholesterol, ldl, hdl etc..

--Just want the output, not the messages
SET NOCOUNT ON;

-- Set the start date
DECLARE @StartDate datetime;
SET @StartDate = '2018-01-01';

-- Get link ids of patients
SELECT DISTINCT FK_Patient_Link_ID INTO #Patients
FROM [RLS].vw_Patient p
INNER JOIN #DAREPatients dp ON dp.NhsNo = p.NhsNo;

-- >>> Codesets required... Inserting the code set code
--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘

-- OBJECTIVE: To populate temporary tables with the existing clinical code sets.
--            See the [SQL-generation-process.md](SQL-generation-process.md) for more details.

-- INPUT: No pre-requisites

-- OUTPUT: Five temp tables as follows:
--  #AllCodes (Concept, Version, Code)
--  #CodeSets (FK_Reference_Coding_ID, Concept)
--  #SnomedSets (FK_Reference_SnomedCT_ID, FK_SNOMED_ID)
--  #VersionedCodeSets (FK_Reference_Coding_ID, Concept, Version)
--  #VersionedSnomedSets (FK_Reference_SnomedCT_ID, Version, FK_SNOMED_ID)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

IF OBJECT_ID('tempdb..#AllCodes') IS NOT NULL DROP TABLE #AllCodes;
CREATE TABLE #AllCodes (
  [Concept] [varchar](255) NOT NULL,
  [Version] INT NOT NULL,
  [Code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
  [description] [varchar] (255) NULL 
);

IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('bmi',1,'22K..00','Body Mass Index'),('bmi',1,'22K..','Body Mass Index'),('bmi',1,'22KE.00','Obese class III (body mass index equal to or greater than 40.0)'),('bmi',1,'22KE.','Obese class III (body mass index equal to or greater than 40.0)'),('bmi',1,'22KD.00','Obese class II (body mass index 35.0 - 39.9)'),('bmi',1,'22KD.','Obese class II (body mass index 35.0 - 39.9)'),('bmi',1,'22KC.00','Obese class I (body mass index 30.0 - 34.9)'),('bmi',1,'22KC.','Obese class I (body mass index 30.0 - 34.9)'),('bmi',1,'22KB.00','Baseline body mass index'),('bmi',1,'22KB.','Baseline body mass index'),('bmi',1,'22KA.00','Target body mass index'),('bmi',1,'22KA.','Target body mass index'),('bmi',1,'22K9.00','Body mass index centile'),('bmi',1,'22K9.','Body mass index centile'),('bmi',1,'22K9K00','Downs syndrome body mass index centile'),('bmi',1,'22K9K','Downs syndrome body mass index centile'),('bmi',1,'22K9J00','Child body mass index greater than 99.6th centile'),('bmi',1,'22K9J','Child body mass index greater than 99.6th centile'),('bmi',1,'22K9H00','Child body mass index 98.1st-99.6th centile'),('bmi',1,'22K9H','Child body mass index 98.1st-99.6th centile'),('bmi',1,'22K9G00','Child body mass index on 98th centile'),('bmi',1,'22K9G','Child body mass index on 98th centile'),('bmi',1,'22K9F00','Child body mass index 92nd-97th centile'),('bmi',1,'22K9F','Child body mass index 92nd-97th centile'),('bmi',1,'22K9E00','Child body mass index on 91st centile'),('bmi',1,'22K9E','Child body mass index on 91st centile'),('bmi',1,'22K9D00','Child body mass index 76th-90th centile'),('bmi',1,'22K9D','Child body mass index 76th-90th centile'),('bmi',1,'22K9C00','Child body mass index on 75th centile'),('bmi',1,'22K9C','Child body mass index on 75th centile'),('bmi',1,'22K9B00','Child body mass index 51st-74th centile'),('bmi',1,'22K9B','Child body mass index 51st-74th centile'),('bmi',1,'22K9A00','Child body mass index on 50th centile'),('bmi',1,'22K9A','Child body mass index on 50th centile'),('bmi',1,'22K9900','Child body mass index 26th-49th centile'),('bmi',1,'22K99','Child body mass index 26th-49th centile'),('bmi',1,'22K9800','Child body mass index on 25th centile'),('bmi',1,'22K98','Child body mass index on 25th centile'),('bmi',1,'22K9700','Child body mass index 10th-24th centile'),('bmi',1,'22K97','Child body mass index 10th-24th centile'),('bmi',1,'22K9600','Child body mass index on 9th centile'),('bmi',1,'22K96','Child body mass index on 9th centile'),('bmi',1,'22K9500','Child body mass index 3rd-8th centile'),('bmi',1,'22K95','Child body mass index 3rd-8th centile'),('bmi',1,'22K9400','Child body mass index on 2nd centile'),('bmi',1,'22K94','Child body mass index on 2nd centile'),('bmi',1,'22K9300','Child body mass index 0.4th-1.9th centile'),('bmi',1,'22K93','Child body mass index 0.4th-1.9th centile'),('bmi',1,'22K9200','Child body mass index less than 0.4th centile'),('bmi',1,'22K92','Child body mass index less than 0.4th centile'),('bmi',1,'22K9100','Child body mass index centile'),('bmi',1,'22K91','Child body mass index centile'),('bmi',1,'22K9000','Baseline body mass index centile'),('bmi',1,'22K90','Baseline body mass index centile'),('bmi',1,'22K8.00','Body mass index 20-24 - normal'),('bmi',1,'22K8.','Body mass index 20-24 - normal'),('bmi',1,'22K7.00','Body mass index 40+ - severely obese'),('bmi',1,'22K7.','Body mass index 40+ - severely obese'),('bmi',1,'22K6.00','Body mass index less than 20'),('bmi',1,'22K6.','Body mass index less than 20'),('bmi',1,'22K5.00','Body mass index 30+ - obesity'),('bmi',1,'22K5.','Body mass index 30+ - obesity'),('bmi',1,'22K4.00','Body mass index index 25-29 - overweight'),('bmi',1,'22K4.','Body mass index index 25-29 - overweight'),('bmi',1,'22K3.00','Body Mass Index low K/M2'),('bmi',1,'22K3.','Body Mass Index low K/M2'),('bmi',1,'22K2.00','Body Mass Index high K/M2'),('bmi',1,'22K2.','Body Mass Index high K/M2'),('bmi',1,'22K1.00','Body Mass Index normal K/M2'),('bmi',1,'22K1.','Body Mass Index normal K/M2'),('bmi',1,'C3808','Childhood obesity'),('bmi',1,'C380800','Childhood obesity'),('bmi',2,'22K..00','Body Mass Index'),('bmi',2,'22K..','Body Mass Index');
INSERT INTO #codesreadv2
VALUES ('cholesterol',1,'44P..00','Serum cholesterol'),('cholesterol',1,'44P..','Serum cholesterol'),('cholesterol',1,'44PZ.00','Serum cholesterol NOS'),('cholesterol',1,'44PZ.','Serum cholesterol NOS'),('cholesterol',1,'44PL.00','Non HDL cholesterol level'),('cholesterol',1,'44PL.','Non HDL cholesterol level'),('cholesterol',1,'44PL100','Estimated serum non-high density lipoprotein cholesterol level'),('cholesterol',1,'44PL1','Estimated serum non-high density lipoprotein cholesterol level'),('cholesterol',1,'44PL000','Serum non high density lipoprotein cholesterol level'),('cholesterol',1,'44PL0','Serum non high density lipoprotein cholesterol level'),('cholesterol',1,'44PK.00','Serum fasting total cholesterol'),('cholesterol',1,'44PK.','Serum fasting total cholesterol'),('cholesterol',1,'44PJ.00','Serum total cholesterol level'),('cholesterol',1,'44PJ.','Serum total cholesterol level'),('cholesterol',1,'44PI.00','Calculated LDL cholesterol level'),('cholesterol',1,'44PI.','Calculated LDL cholesterol level'),('cholesterol',1,'44PH.00','Total cholesterol measurement'),('cholesterol',1,'44PH.','Total cholesterol measurement'),('cholesterol',1,'44PG.00','HDL : total cholesterol ratio'),('cholesterol',1,'44PG.','HDL : total cholesterol ratio'),('cholesterol',1,'44PF.00','Total cholesterol:HDL ratio'),('cholesterol',1,'44PF.','Total cholesterol:HDL ratio'),('cholesterol',1,'44PE.00','Serum random LDL cholesterol level'),('cholesterol',1,'44PE.','Serum random LDL cholesterol level'),('cholesterol',1,'44PD.00','Serum fasting LDL cholesterol level'),('cholesterol',1,'44PD.','Serum fasting LDL cholesterol level'),('cholesterol',1,'44PC.00','Serum random HDL cholesterol level'),('cholesterol',1,'44PC.','Serum random HDL cholesterol level'),('cholesterol',1,'44PB.00','Serum fasting HDL cholesterol level'),('cholesterol',1,'44PB.','Serum fasting HDL cholesterol level'),('cholesterol',1,'44P9.00','Serum cholesterol studies'),('cholesterol',1,'44P9.','Serum cholesterol studies'),('cholesterol',1,'44P8.00','Serum HDL:non-HDL cholesterol ratio'),('cholesterol',1,'44P8.','Serum HDL:non-HDL cholesterol ratio'),('cholesterol',1,'44P7.00','Serum VLDL cholesterol level'),('cholesterol',1,'44P7.','Serum VLDL cholesterol level'),('cholesterol',1,'44P6.00','Serum LDL cholesterol level'),('cholesterol',1,'44P6.','Serum LDL cholesterol level'),('cholesterol',1,'44P5.00','Serum HDL cholesterol level'),('cholesterol',1,'44P5.','Serum HDL cholesterol level'),('cholesterol',1,'44P4.00','Serum cholesterol very high'),('cholesterol',1,'44P4.','Serum cholesterol very high'),('cholesterol',1,'44P3.00','Serum cholesterol raised'),('cholesterol',1,'44P3.','Serum cholesterol raised'),('cholesterol',1,'44P2.00','Serum cholesterol borderline'),('cholesterol',1,'44P2.','Serum cholesterol borderline'),('cholesterol',1,'44P1.00','Serum cholesterol normal'),('cholesterol',1,'44P1.','Serum cholesterol normal'),('cholesterol',1,'44PA.00','HDL : LDL ratio'),('cholesterol',1,'44PA.','HDL : LDL ratio'),('cholesterol',1,'44lM.00','Plasma LDL/HDL ratio'),('cholesterol',1,'44lM.','Plasma LDL/HDL ratio'),('cholesterol',1,'44lL.00','Serum LDL/HDL ratio'),('cholesterol',1,'44lL.','Serum LDL/HDL ratio'),('cholesterol',1,'44lK.00','Plasma cholesterol/VLDL ratio'),('cholesterol',1,'44lK.','Plasma cholesterol/VLDL ratio'),('cholesterol',1,'44lJ.00','Serum cholesterol/VLDL ratio'),('cholesterol',1,'44lJ.','Serum cholesterol/VLDL ratio'),('cholesterol',1,'44lI.00','Plasma cholesterol/LDL ratio'),('cholesterol',1,'44lI.','Plasma cholesterol/LDL ratio'),('cholesterol',1,'44lH.00','Serum cholesterol/LDL ratio'),('cholesterol',1,'44lH.','Serum cholesterol/LDL ratio'),('cholesterol',1,'44lG.00','Plasma cholesterol/HDL ratio'),('cholesterol',1,'44lG.','Plasma cholesterol/HDL ratio'),('cholesterol',1,'44lF.00','Serum cholesterol/HDL ratio'),('cholesterol',1,'44lF.','Serum cholesterol/HDL ratio'),('cholesterol',1,'44l2.00','Cholesterol/HDL ratio'),('cholesterol',1,'44l2.','Cholesterol/HDL ratio'),('cholesterol',1,'44dB.00','Plasma LDL cholesterol level'),('cholesterol',1,'44dB.','Plasma LDL cholesterol level'),('cholesterol',1,'44dA.00','Plasma HDL cholesterol level'),('cholesterol',1,'44dA.','Plasma HDL cholesterol level'),('cholesterol',1,'44d5.00','Plasma fasting LDL cholesterol level'),('cholesterol',1,'44d5.','Plasma fasting LDL cholesterol level'),('cholesterol',1,'44d4.00','Plasma random LDL cholesterol level'),('cholesterol',1,'44d4.','Plasma random LDL cholesterol level'),('cholesterol',1,'44d3.00','Plasma fasting HDL cholesterol level'),('cholesterol',1,'44d3.','Plasma fasting HDL cholesterol level'),('cholesterol',1,'44d2.00','Plasma random HDL cholesterol level'),('cholesterol',1,'44d2.','Plasma random HDL cholesterol level'),('cholesterol',1,'44R4.11','LDL - electrophoresis'),('cholesterol',1,'44R4.','LDL - electrophoresis'),('cholesterol',1,'44R4.00','Lipoprotein electroph. - LDL'),('cholesterol',1,'44R4.','Lipoprotein electroph. - LDL'),('cholesterol',1,'44R3.11','HDL - electrophoresis'),('cholesterol',1,'44R3.','HDL - electrophoresis'),('cholesterol',1,'44R3.00','Lipoprotein electroph. - HDL'),('cholesterol',1,'44R3.','Lipoprotein electroph. - HDL'),('cholesterol',1,'662a.00','Pre-treatment serum cholesterol level'),('cholesterol',1,'662a.','Pre-treatment serum cholesterol level'),('cholesterol',1,'44OE.00','Plasma total cholesterol level'),('cholesterol',1,'44OE.','Plasma total cholesterol level'),('cholesterol',1,'44lzY00','Serum high density lipoprotein cholesterol:triglyceride ratio'),('cholesterol',1,'44lzY','Serum high density lipoprotein cholesterol:triglyceride ratio'),('cholesterol',1,'4I3O.00','Fluid sample cholesterol level'),('cholesterol',1,'4I3O.','Fluid sample cholesterol level'),('cholesterol',2,'44P..00','Serum cholesterol'),('cholesterol',2,'44P..','Serum cholesterol'),('cholesterol',2,'44PZ.00','Serum cholesterol NOS'),('cholesterol',2,'44PZ.','Serum cholesterol NOS'),('cholesterol',2,'44PJ.00','Serum total cholesterol level'),('cholesterol',2,'44PJ.','Serum total cholesterol level'),('cholesterol',2,'44PH.00','Total cholesterol measurement'),('cholesterol',2,'44PH.','Total cholesterol measurement');
INSERT INTO #codesreadv2
VALUES ('egfr',1,'451E.00','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'451E.','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'451G.00','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'451G.','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'451K.00','Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'451K.','Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'451M.00','Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451M.','Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451N.00','Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451N.','Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres');
INSERT INTO #codesreadv2
VALUES ('hba1c',1,'42c..00','HbA1 - diabetic control'),('hba1c',1,'42c..','HbA1 - diabetic control'),('hba1c',1,'42c3.00','HbA1 level (DCCT aligned)'),('hba1c',1,'42c3.','HbA1 level (DCCT aligned)'),('hba1c',1,'42c2.00','HbA1 > 10% - bad control'),('hba1c',1,'42c2.','HbA1 > 10% - bad control'),('hba1c',1,'42c1.00','HbA1 7 - 10% - borderline control'),('hba1c',1,'42c1.','HbA1 7 - 10% - borderline control'),('hba1c',1,'42c0.00','HbA1 < 7% - good control'),('hba1c',1,'42c0.','HbA1 < 7% - good control'),('hba1c',1,'42W..11','Glycosylated Hb'),('hba1c',1,'42W..','Glycosylated Hb'),('hba1c',1,'42W..12','Glycated haemoglobin'),('hba1c',1,'42W..','Glycated haemoglobin'),('hba1c',1,'42W..00','Hb. A1C - diabetic control'),('hba1c',1,'42W..','Hb. A1C - diabetic control'),('hba1c',1,'42WZ.00','Hb. A1C - diabetic control NOS'),('hba1c',1,'42WZ.','Hb. A1C - diabetic control NOS'),('hba1c',1,'42W3.00','Hb. A1C > 10% - bad control'),('hba1c',1,'42W3.','Hb. A1C > 10% - bad control'),('hba1c',1,'42W2.00','Hb. A1C 7-10% - borderline'),('hba1c',1,'42W2.','Hb. A1C 7-10% - borderline'),('hba1c',1,'42W1.00','Hb. A1C < 7% - good control'),('hba1c',1,'42W1.','Hb. A1C < 7% - good control'),('hba1c',1,'42W5.00','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',1,'42W5.','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',1,'42W5100','HbA1c (haemoglobin A1c) level (monitoring ranges) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W51','HbA1c (haemoglobin A1c) level (monitoring ranges) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W5000','HbA1c (haemoglobin A1c) level (diagnostic reference range) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W50','HbA1c (haemoglobin A1c) level (diagnostic reference range) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W4.00','HbA1c level (DCCT aligned)'),('hba1c',1,'42W4.','HbA1c level (DCCT aligned)'),('hba1c',1,'44TL.00','Total glycosylated haemoglobin level'),('hba1c',1,'44TL.','Total glycosylated haemoglobin level'),('hba1c',1,'44TB.00','Haemoglobin A1c level'),('hba1c',1,'44TB.','Haemoglobin A1c level'),('hba1c',1,'44TB100','Haemoglobin A1c (monitoring ranges)'),('hba1c',1,'44TB1','Haemoglobin A1c (monitoring ranges)'),('hba1c',1,'44TB000','Haemoglobin A1c (diagnostic reference range)'),('hba1c',1,'44TB0','Haemoglobin A1c (diagnostic reference range)'),('hba1c',2,'42W5.00','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',2,'42W5.','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',2,'42W4.00','HbA1c level (DCCT aligned)'),('hba1c',2,'42W4.','HbA1c level (DCCT aligned)');
INSERT INTO #codesreadv2
VALUES ('hdl-cholesterol',1,'44PC.00','Serum random HDL cholesterol level'),('hdl-cholesterol',1,'44PC.','Serum random HDL cholesterol level'),('hdl-cholesterol',1,'44P5.00','Serum HDL cholesterol level'),('hdl-cholesterol',1,'44P5.','Serum HDL cholesterol level'),('hdl-cholesterol',1,'44dA.00','Plasma HDL cholesterol level'),('hdl-cholesterol',1,'44dA.','Plasma HDL cholesterol level');
INSERT INTO #codesreadv2
VALUES ('ldl-cholesterol',1,'44PI.00','Calculated LDL cholesterol level'),('ldl-cholesterol',1,'44PI.','Calculated LDL cholesterol level'),('ldl-cholesterol',1,'44P6.00','Serum LDL cholesterol level'),('ldl-cholesterol',1,'44P6.','Serum LDL cholesterol level'),('ldl-cholesterol',1,'44dB.00','Plasma LDL cholesterol level'),('ldl-cholesterol',1,'44dB.','Plasma LDL cholesterol level');
INSERT INTO #codesreadv2
VALUES ('sex-hormone-binding-globulin',1,'44CD.00','Serum sex hormone binding globulin level'),('sex-hormone-binding-globulin',1,'44CD.','Serum sex hormone binding globulin level');
INSERT INTO #codesreadv2
VALUES ('testosterone',1,'4473.00','Serum testosterone'),('testosterone',1,'4473.','Serum testosterone'),('testosterone',1,'447G.00','Plasma testosterone level'),('testosterone',1,'447G.','Plasma testosterone level');
INSERT INTO #codesreadv2
VALUES ('vitamin-d',1,'4QB4.00','Vitamin D level'),('vitamin-d',1,'4QB4.','Vitamin D level'),('vitamin-d',1,'44LA.00','Serum vitamin D'),('vitamin-d',1,'44LA.','Serum vitamin D'),('vitamin-d',1,'4QB4.00','Vitamin D level'),('vitamin-d',1,'4QB4.','Vitamin D level'),('vitamin-d',1,'4QB4400','Combined total vitamin D2 and D3 level'),('vitamin-d',1,'4QB44','Combined total vitamin D2 and D3 level'),('vitamin-d',1,'4QB4500','25-Hydroxyvitamin D level'),('vitamin-d',1,'4QB45','25-Hydroxyvitamin D level'),('vitamin-d',1,'4QB4600','Total 25-hydroxyvitamin D level'),('vitamin-d',1,'4QB46','Total 25-hydroxyvitamin D level'),('vitamin-d',1,'4QB4700','Serum total 25-hydroxy vitamin D level'),('vitamin-d',1,'4QB47','Serum total 25-hydroxy vitamin D level')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesreadv2;

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('bmi',1,'22K..','Body Mass Index'),('bmi',1,'22K1.','Body Mass Index normal K/M2'),('bmi',1,'22K2.','Body Mass Index high K/M2'),('bmi',1,'22K3.','Body Mass Index low K/M2'),('bmi',1,'22K4.','Body mass index index 25-29 - overweight'),('bmi',1,'22K5.','Body mass index 30+ - obesity'),('bmi',1,'X76CO','Quetelet index'),('bmi',1,'Xa7wG','Observation of body mass index'),('bmi',1,'Xaa0k','Childhood obesity'),('bmi',1,'Xaatm','Child BMI centile'),('bmi',1,'Xabdn','Downs syndrome BMI centile'),('bmi',1,'XabHx','Obese class I (BMI 30.0-34.9)'),('bmi',1,'XabHy','Obese class II (BMI 35.0-39.9)'),('bmi',1,'XabHz','Obese cls III (BMI eq/gr 40.0)'),('bmi',1,'XabSe','Child BMI < 0.4th centile'),('bmi',1,'XabSf','Child BMI 0.4th-1.9th centile'),('bmi',1,'XabSg','Child BMI on 2nd centile'),('bmi',1,'XabSh','Child BMI 3rd-8th centile'),('bmi',1,'XabSj','Child BMI on 9th centile'),('bmi',1,'XabSk','Child BMI 10th-24th centile'),('bmi',1,'XabSl','Child BMI on 25th centile'),('bmi',1,'XabSm','Child BMI 26th-49th centile'),('bmi',1,'XabSn','Child BMI on 50th centile'),('bmi',1,'XabTe','Child BMI on 75th centile'),('bmi',1,'XabTf','Child BMI 76th-90th centile'),('bmi',1,'XabTg','Child BMI on 91st centile'),('bmi',1,'XabTh','Child BMI 92nd-97th centile'),('bmi',1,'XabTi','Child BMI on 98th centile'),('bmi',1,'XabTj','Child BMI 98.1-99.6 centile'),('bmi',1,'XabTk','Child BMI > 99.6th centile'),('bmi',1,'XabTZ','Child BMI 51st-74th centile'),('bmi',1,'XaCDR','Body mass index less than 20'),('bmi',1,'XaJJH','BMI 40+ - severely obese'),('bmi',1,'XaJqk','Body mass index 20-24 - normal'),('bmi',1,'XaVwA','Body mass index centile'),('bmi',1,'XaZck','Baseline BMI centile'),('bmi',1,'XaZcl','Baseline body mass index'),('bmi',2,'22K..','Body Mass Index');
INSERT INTO #codesctv3
VALUES ('cholesterol',1,'X772L','Cholesterol level'),('cholesterol',1,'X772M','High density lipoprot chol lev'),('cholesterol',1,'X772N','LDL-Low dens lipoprot chol lev'),('cholesterol',1,'X773m','Percentage chol as ester'),('cholesterol',1,'X773W','HDL/LDL ratio'),('cholesterol',1,'X80J1','HDL - High density lipoprotein'),('cholesterol',1,'X80Nb','Hi density lipoprot subfrac 2'),('cholesterol',1,'X80Nc','Hi density lipoprot subfrac 3'),('cholesterol',1,'X80Ne','LDL - Low density lipoprotein'),('cholesterol',1,'X80NT','Free cholesterol'),('cholesterol',1,'X80NU','Cholesterol ester'),('cholesterol',1,'XabE1','Se non HDL cholesterol level'),('cholesterol',1,'XabT0','Estim serum non-HDL cholest lv'),('cholesterol',1,'Xabub','Se HDL chol:triglyceride ratio'),('cholesterol',1,'XaEil','Hi dens lipoprt/tot chol ratio'),('cholesterol',1,'XaERR','Cholesterol/HDL ratio'),('cholesterol',1,'XaEUp','Lipoprotein cholesterol ratio'),('cholesterol',1,'XaEUq','Serum cholesterol/HDL ratio'),('cholesterol',1,'XaEUr','Plasma cholesterol/HDL ratio'),('cholesterol',1,'XaEUs','Serum cholesterol/LDL ratio'),('cholesterol',1,'XaEUt','Plasma cholesterol/LDL ratio'),('cholesterol',1,'XaEUu','Serum cholesterol/VLDL ratio'),('cholesterol',1,'XaEUv','Plasma cholesterol/VLDL ratio'),('cholesterol',1,'XaEVQ','Serum LDL/HDL ratio'),('cholesterol',1,'XaEVr','Plasma HDL cholesterol level'),('cholesterol',1,'XaEVR','Plasma LDL/HDL ratio'),('cholesterol',1,'XaEVs','Plasma LDL cholesterol level'),('cholesterol',1,'XaFs9','Fasting cholesterol level'),('cholesterol',1,'XaIp4','Calculated LDL cholesterol lev'),('cholesterol',1,'XaIqd','Pre-treatmnt serum cholest lev'),('cholesterol',1,'XaIRd','Plasma total cholesterol level'),('cholesterol',1,'XaIYp','Fluid sample cholesterol level'),('cholesterol',1,'XaJe9','Serum total cholesterol level'),('cholesterol',1,'XaLux','Serum fastng total cholesterol'),('cholesterol',1,'XaN3z','Non HDL cholesterol level'),('cholesterol',1,'XE28o','HDL : LDL ratio'),('cholesterol',1,'XE2eD','Serum cholesterol'),('cholesterol',1,'XE2mn','Ser HDL/non-HDL cholest ratio'),('cholesterol',1,'XSK14','Total cholesterol measurement'),('cholesterol',1,'44P..','Serum cholesterol'),('cholesterol',1,'44PZ.','Serum cholesterol NOS'),('cholesterol',1,'44PL.','Non HDL cholesterol level'),('cholesterol',1,'44PL1','Estimated serum non-high density lipoprotein cholesterol level'),('cholesterol',1,'44PL0','Serum non high density lipoprotein cholesterol level'),('cholesterol',1,'44PK.','Serum fasting total cholesterol'),('cholesterol',1,'44PJ.','Serum total cholesterol level'),('cholesterol',1,'44PI.','Calculated LDL cholesterol level'),('cholesterol',1,'44PH.','Total cholesterol measurement'),('cholesterol',1,'44PG.','HDL : total cholesterol ratio'),('cholesterol',1,'44PF.','Total cholesterol:HDL ratio'),('cholesterol',1,'44PE.','Serum random LDL cholesterol level'),('cholesterol',1,'44PD.','Serum fasting LDL cholesterol level'),('cholesterol',1,'44PC.','Serum random HDL cholesterol level'),('cholesterol',1,'44PB.','Serum fasting HDL cholesterol level'),('cholesterol',1,'44P9.','Serum cholesterol studies'),('cholesterol',1,'44P8.','Serum HDL:non-HDL cholesterol ratio'),('cholesterol',1,'44P7.','Serum VLDL cholesterol level'),('cholesterol',1,'44P6.','Serum LDL cholesterol level'),('cholesterol',1,'44P5.','Serum HDL cholesterol level'),('cholesterol',1,'44P4.','Serum cholesterol very high'),('cholesterol',1,'44P3.','Serum cholesterol raised'),('cholesterol',1,'44P2.','Serum cholesterol borderline'),('cholesterol',1,'44P1.','Serum cholesterol normal'),('cholesterol',1,'44PA.','HDL : LDL ratio'),('cholesterol',1,'44lM.','Plasma LDL/HDL ratio'),('cholesterol',1,'44lL.','Serum LDL/HDL ratio'),('cholesterol',1,'44lK.','Plasma cholesterol/VLDL ratio'),('cholesterol',1,'44lJ.','Serum cholesterol/VLDL ratio'),('cholesterol',1,'44lI.','Plasma cholesterol/LDL ratio'),('cholesterol',1,'44lH.','Serum cholesterol/LDL ratio'),('cholesterol',1,'44lG.','Plasma cholesterol/HDL ratio'),('cholesterol',1,'44lF.','Serum cholesterol/HDL ratio'),('cholesterol',1,'44l2.','Cholesterol/HDL ratio'),('cholesterol',1,'44dB.','Plasma LDL cholesterol level'),('cholesterol',1,'44dA.','Plasma HDL cholesterol level'),('cholesterol',1,'44d5.','Plasma fasting LDL cholesterol level'),('cholesterol',1,'44d4.','Plasma random LDL cholesterol level'),('cholesterol',1,'44d3.','Plasma fasting HDL cholesterol level'),('cholesterol',1,'44d2.','Plasma random HDL cholesterol level'),('cholesterol',1,'44R4.','LDL - electrophoresis'),('cholesterol',1,'44R4.','Lipoprotein electroph. - LDL'),('cholesterol',1,'44R3.','HDL - electrophoresis'),('cholesterol',1,'44R3.','Lipoprotein electroph. - HDL'),('cholesterol',1,'662a.','Pre-treatment serum cholesterol level'),('cholesterol',1,'44OE.','Plasma total cholesterol level'),('cholesterol',1,'44lzY','Serum high density lipoprotein cholesterol:triglyceride ratio'),('cholesterol',1,'4I3O.','Fluid sample cholesterol level'),('cholesterol',2,'XSK14','Total cholesterol measurement'),('cholesterol',2,'44PH.','Total cholesterol measurement'),('cholesterol',2,'44PJ.','Serum total cholesterol level'),('cholesterol',2,'44P..','Serum cholesterol'),('cholesterol',2,'44PZ.','Serum cholesterol NOS'),('cholesterol',2,'XE2eD','Serum cholesterol'),('cholesterol',2,'XaJe9','Serum total cholesterol level');
INSERT INTO #codesctv3
VALUES ('egfr',1,'X70kK','Tc99m-DTPA clearance - GFR'),('egfr',1,'X70kL','Cr51- EDTA clearance - GFR'),('egfr',1,'X90kf','With GFR'),('egfr',1,'XaK8y','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'XaMDA','Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'XaZpN','Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'XacUJ','Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'XacUK','Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres');
INSERT INTO #codesctv3
VALUES ('hba1c',1,'X772q','Haemoglobin A1c level'),('hba1c',1,'XE24t','Hb. A1C - diabetic control'),('hba1c',1,'42W1.','Hb. A1C < 7% - good control'),('hba1c',1,'42W2.','Hb. A1C 7-10% - borderline'),('hba1c',1,'42W3.','Hb. A1C > 10% - bad control'),('hba1c',1,'42WZ.','Hb. A1C - diabetic control NOS'),('hba1c',1,'X80U4','Glycosylat haemoglobin-c frac'),('hba1c',1,'XaCES','HbA1 - diabetic control'),('hba1c',1,'XaCET','HbA1 <7% - good control'),('hba1c',1,'XaCEV','HbA1 >10% - bad control'),('hba1c',1,'XaCEU','HbA1 7-10% - borderline contrl'),('hba1c',1,'XaERp','HbA1c level (DCCT aligned)'),('hba1c',1,'XaPbt','HbA1c levl - IFCC standardised'),('hba1c',1,'XabrE','HbA1c (diagnostic refrn range)'),('hba1c',1,'XabrF','HbA1c (monitoring ranges)'),('hba1c',1,'Xaezd','HbA1c(diagnos ref rnge)IFCC st'),('hba1c',1,'Xaeze','HbA1c(monitoring rnges)IFCC st'),('hba1c',1,'42W..','Hb. A1C - diabetic control'),('hba1c',1,'42W5.','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',1,'42W51','HbA1c (haemoglobin A1c) level (monitoring ranges) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W50','HbA1c (haemoglobin A1c) level (diagnostic reference range) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'42W4.','HbA1c level (DCCT aligned)'),('hba1c',1,'44TB.','Haemoglobin A1c level'),('hba1c',1,'44TB1','Haemoglobin A1c (monitoring ranges)'),('hba1c',1,'44TB0','Haemoglobin A1c (diagnostic reference range)'),('hba1c',2,'XaERp','HbA1c level (DCCT aligned)'),('hba1c',2,'XaPbt','HbA1c levl - IFCC standardised'),('hba1c',2,'42W5.','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',2,'42W4.','HbA1c level (DCCT aligned)');
INSERT INTO #codesctv3
VALUES ('hdl-cholesterol',1,'44P5.','Serum HDL cholesterol level'),('hdl-cholesterol',1,'44PC.','Ser random HDL cholesterol lev'),('hdl-cholesterol',1,'XaEVr','Plasma HDL cholesterol level');
INSERT INTO #codesctv3
VALUES ('ldl-cholesterol',1,'44P6.','Serum LDL cholesterol level'),('ldl-cholesterol',1,'XaIp4','Calculated LDL cholesterol lev'),('ldl-cholesterol',1,'XaEVs','Plasma LDL cholesterol level');
INSERT INTO #codesctv3
VALUES ('sex-hormone-binding-globulin',1,'44CD.','Serum sex hormone binding globulin level');
INSERT INTO #codesctv3
VALUES ('testosterone',1,'XE2dr','Serum testosterone level'),('testosterone',1,'4473.','Serum testosterone'),('testosterone',1,'XaItQ','Plasma testosterone level');
INSERT INTO #codesctv3
VALUES ('vitamin-d',1,'44LA.','Serum vitamin D'),('vitamin-d',1,'Xabo0','Serum total 25-OH vit D level'),('vitamin-d',1,'XaY6m','Total 25-hydroxyvitamin D levl'),('vitamin-d',1,'XE2e7','Serum vitamin D level'),('vitamin-d',1,'XaXhN','Vitamin D level'),('vitamin-d',1,'XaXhT','Combined total vit D2 + D3 lvl'),('vitamin-d',1,'XaXm0','25-Hydroxyvitamin D level')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesctv3;

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codessnomed
VALUES ('bmi',1,'6497000','Decreased body mass index (finding)'),('bmi',1,'35425004','Normal body mass index (finding)'),('bmi',1,'48499001','Increased body mass index (finding)'),('bmi',1,'162863004','Body mass index 25-29 - overweight'),('bmi',1,'162864005','BMI 30+ - obesity'),('bmi',1,'301331008','Observation of body mass index'),('bmi',1,'310252000','BMI less than 20'),('bmi',1,'408512008','Body mass index 40+ - morbidly obese'),('bmi',1,'412768003','Body mass index 20-24 - normal'),('bmi',1,'427090001','Body mass index less than 16.5'),('bmi',1,'450451007','Childhood overweight BMI greater than 85 percentile'),('bmi',1,'722595002','Overweight in adulthood with BMI of 25 or more but less than 30'),('bmi',1,'920141000000102','Child BMI (body mass index) less than 0.4th centile'),('bmi',1,'920161000000101','Child BMI (body mass index) 0.4th-1.9th centile'),('bmi',1,'920181000000105','Child BMI (body mass index) on 2nd centile'),('bmi',1,'920201000000109','Child BMI (body mass index) 3rd-8th centile'),('bmi',1,'920231000000103','Child BMI (body mass index) on 9th centile'),('bmi',1,'920251000000105','Child BMI (body mass index) 10th-24th centile'),('bmi',1,'920271000000101','Child BMI (body mass index) on 25th centile'),('bmi',1,'920291000000102','Child BMI (body mass index) 26th-49th centile'),('bmi',1,'920311000000101','Child BMI (body mass index) on 50th centile'),('bmi',1,'920841000000108','Child BMI (body mass index) 51st-74th centile'),('bmi',1,'920931000000108','Child BMI (body mass index) on 75th centile'),('bmi',1,'920951000000101','Child BMI (body mass index) 76th-90th centile'),('bmi',1,'920971000000105','Child BMI (body mass index) on 91st centile'),('bmi',1,'920991000000109','Child BMI (body mass index) 92nd-97th centile'),('bmi',1,'921011000000105','Child BMI (body mass index) on 98th centile'),('bmi',1,'921031000000102','Child BMI (body mass index) 98.1st-99.6th centile'),('bmi',1,'921051000000109','Child BMI (body mass index) greater than 99.6th centile'),('bmi',1,'914721000000105','Obese class I (body mass index 30.0 - 34.9)'),('bmi',1,'914731000000107','Obese class II (body mass index 35.0 - 39.9)'),('bmi',1,'914741000000103','Obese class III (body mass index equal to or greater than 40.0)'),('bmi',1,'443371000124107','Body mass index 30.00 to 34.99'),('bmi',1,'443381000124105','Body mass index 35.00 to 39.99'),('bmi',1,'60621009','Quetelet index'),('bmi',1,'846931000000101','Baseline BMI (body mass index)'),('bmi',1,'852451000000103','Maximum body mass index (observable entity)'),('bmi',1,'852461000000100','Minimum body mass index (observable entity)'),('bmi',1,'446974000','Body mass index centile'),('bmi',1,'846911000000109','Baseline BMI (body mass index) centile'),('bmi',1,'896691000000102','Child BMI (body mass index) centile'),('bmi',1,'926011000000101','Downs syndrome BMI (body mass index) centile'),('bmi',1,'722562008','Foetal or neonatal effect or suspected effect of maternal obesity with adult body mass index 30 or greater but less than 40'),('bmi',1,'722563003','Foetal or neonatal effect of maternal obesity with adult body mass index equal to or greater than 40'),('bmi',1,'705131003','Child at risk for overweight body mass index greater than 85 percentile'),('bmi',1,'43991000119102','History of childhood obesity BMI 95-100 percentile'),('bmi',1,'698094009','Calculation of body mass index'),('bmi',1,'444862003','Childhood obesity BMI 95-100 percentile'),('bmi',2,'301331008','Finding of body mass index (finding)');
INSERT INTO #codessnomed
VALUES ('cholesterol',1,'13067005','Cholesteryl esters measurement (procedure)'),('cholesterol',1,'17888004','High density lipoprotein measurement (procedure)'),('cholesterol',1,'28036006','High density lipoprotein cholesterol level'),('cholesterol',1,'77068002','Cholesterol measurement (procedure)'),('cholesterol',1,'104583003','High density lipoprotein/total cholesterol ratio measurement'),('cholesterol',1,'104584009','Intermediate density lipoprotein cholesterol measurement'),('cholesterol',1,'104585005','Very low density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'104586006','Cholesterol/triglyceride ratio measurement (procedure)'),('cholesterol',1,'104594004','Cholesterol esterase measurement (procedure)'),('cholesterol',1,'104777003','Lecithin cholesterol acyltransferase measurement (procedure)'),('cholesterol',1,'104781003','Lipids, cholesterol measurement (procedure)'),('cholesterol',1,'104990004','Triglyceride and ester in high density lipoprotein measurement (procedure)'),('cholesterol',1,'104992007','Triglyceride and ester in low density lipoprotein measurement'),('cholesterol',1,'113079009','Low density lipoprotein cholesterol level'),('cholesterol',1,'121751004','Cholesterol sulfate measurement (procedure)'),('cholesterol',1,'121868005','Total cholesterol measurement (procedure)'),('cholesterol',1,'166832000','Serum high density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'166833005','Serum low density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'166834004','Serum very low density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'166838001','Serum fasting high density lipoprotein cholesterol measurement'),('cholesterol',1,'166839009','Serum random high density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'166840006','Serum fasting low density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'166841005','Serum random low density lipoprotein cholesterol measurement'),('cholesterol',1,'166842003','Total cholesterol:high density lipoprotein ratio measurement'),('cholesterol',1,'167072001','Plasma random high density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'167073006','Plasma fasting high density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'167074000','Plasma random low density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'167075004','Plasma fasting low density lipoprotein cholesterol measurement'),('cholesterol',1,'250743005','HDL/LDL ratio'),('cholesterol',1,'250759005','Measurement of percentage cholesterol as ester (procedure)'),('cholesterol',1,'271059008','Serum high density lipoprotein/non-high density lipoprotein cholesterol ratio measurement (procedure)'),('cholesterol',1,'313811003','Cholesterol/High density lipoprotein ratio measurement'),('cholesterol',1,'313988001','Lipoprotein cholesterol ratio measurement (procedure)'),('cholesterol',1,'313989009','Serum cholesterol/high density lipoprotein ratio measurement'),('cholesterol',1,'313990000','Plasma cholesterol/high density lipoprotein ratio measurement'),('cholesterol',1,'313991001','Serum cholesterol/low density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'313992008','Plasma cholesterol/low density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'313993003','Serum cholesterol/very low density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'313994009','Plasma cholesterol/very low density lipoprotein ratio measurement'),('cholesterol',1,'314012003','Serum low density lipoprotein/high density lipoprotein ratio measurement'),('cholesterol',1,'314013008','Plasma low density lipoprotein/high density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'314035000','Plasma high density lipoprotein cholesterol measurement (procedure)'),('cholesterol',1,'314036004','Plasma low density lipoprotein cholesterol measurement'),('cholesterol',1,'315017003','Fasting cholesterol level (procedure)'),('cholesterol',1,'390956002','Plasma total cholesterol level'),('cholesterol',1,'391291008','Fluid sample cholesterol level'),('cholesterol',1,'395065005','Calculated low density lipoprotein cholesterol level (procedure)'),('cholesterol',1,'395153009','Pre-treatment serum cholesterol level'),('cholesterol',1,'412808005','Serum total cholesterol level'),('cholesterol',1,'443915001','Measurement of total cholesterol and triglycerides'),('cholesterol',1,'789381000000104','Cholesterol/phospholipid ratio measurement (procedure)'),('cholesterol',1,'195861000000108','Cholesterol content measurement (procedure)'),('cholesterol',1,'293821000000103','Non high density lipoprotein cholesterol level'),('cholesterol',1,'194351000000100','Cholesterol/low density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'194361000000102','Cholesterol/very low density lipoprotein ratio measurement (procedure)'),('cholesterol',1,'247801000000106','Serum fasting total cholesterol'),('cholesterol',1,'194801000000108','High density lipoprotein/non-high density lipoprotein cholesterol ratio measurement (procedure)'),('cholesterol',1,'912151000000109','Serum non high density lipoprotein cholesterol level'),('cholesterol',1,'920471000000100','Estimated serum non-high density lipoprotein cholesterol level'),('cholesterol',1,'1006191000000106','Serum non HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1102851000000101','Estimated serum non high density lipoprotein cholesterol level (observable entity)'),('cholesterol',1,'1030411000000101','Non HDL cholesterol level'),('cholesterol',1,'1005681000000107','Serum HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1015271000000109','Serum HDL (high density lipoprotein):non-HDL (high density lipoprotein) cholesterol ratio'),('cholesterol',1,'1015681000000109','Serum cholesterol/HDL (high density lipoprotein) ratio'),('cholesterol',1,'1015741000000109','Serum LDL (low density lipoprotein)/HDL (high density lipoprotein) ratio'),('cholesterol',1,'1015751000000107','Plasma LDL/HDL (low density lipoprotein/high density lipoprotein) ratio'),('cholesterol',1,'1010581000000101','Plasma HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1015701000000106','Serum cholesterol/LDL (low density lipoprotein) ratio'),('cholesterol',1,'1015711000000108','Plasma cholesterol/LDL (low density lipoprotein) ratio'),('cholesterol',1,'1010591000000104','Plasma LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1014501000000104','Calculated LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1022191000000100','Serum LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1003441000000101','Serum VLDL (very low density lipoprotein) cholesterol level'),('cholesterol',1,'1015721000000102','Serum cholesterol/VLDL (very low density lipoprotein) ratio'),('cholesterol',1,'1015731000000100','Plasma cholesterol/VLDL (very low density lipoprotein) ratio'),('cholesterol',1,'1024231000000104','Fluid sample cholesterol level'),('cholesterol',1,'1031421000000101','High density lipoprotein/total cholesterol ratio'),('cholesterol',1,'1026451000000102','Serum fasting HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1026461000000104','Serum random HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1107681000000108','HDL (high density lipoprotein) cholesterol molar concentration in serum'),('cholesterol',1,'1028831000000106','Plasma random HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1028841000000102','Plasma fasting HDL (high density lipoprotein) cholesterol level'),('cholesterol',1,'1107661000000104','HDL (high density lipoprotein) cholesterol molar concentration in plasma'),('cholesterol',1,'1028861000000101','Plasma fasting LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1028851000000104','Plasma random LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1026471000000106','Serum fasting LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1026481000000108','Serum random LDL (low density lipoprotein) cholesterol level'),('cholesterol',1,'1015691000000106','Plasma cholesterol/HDL (high density lipoprotein) ratio'),('cholesterol',1,'994351000000103','Serum total cholesterol level'),('cholesterol',1,'1005671000000105','Serum cholesterol level'),('cholesterol',1,'1017161000000104','Plasma total cholesterol level'),('cholesterol',1,'1107731000000104','Ratio of high density lipoprotein cholesterol to total cholesterol in plasma (observable entity)'),('cholesterol',1,'1107741000000108','Ratio of high density lipoprotein cholesterol to total cholesterol in serum (observable entity)'),('cholesterol',1,'1028551000000102','Total cholesterol:HDL (high density lipoprotein) ratio'),('cholesterol',1,'1029071000000109','HDL/LDL ratio'),('cholesterol',1,'1083861000000102','Serum HDL (high density lipoprotein) cholesterol/triglyceride ratio'),('cholesterol',1,'1083761000000106','Serum fasting total cholesterol level (observable entity)'),('cholesterol',1,'1106541000000101','Cholesterol molar concentration in serum'),('cholesterol',1,'1106531000000105','Cholesterol molar concentration in plasma'),('cholesterol',1,'9422000','Alpha-lipoprotein'),('cholesterol',1,'9556009','Acyl CoA cholesterol acyltransferase'),('cholesterol',1,'22244007','LDL - Low density lipoprotein'),('cholesterol',1,'73427004','Cholesterol ester'),('cholesterol',1,'88557001','LCAT - Lecithin cholesterol acyltransferase'),('cholesterol',1,'102741009','Free cholesterol'),('cholesterol',1,'115332003','High density lipoprotein subfraction 2'),('cholesterol',1,'115333008','High density lipoprotein subfraction 3'),('cholesterol',1,'416724002','Cholesterol derivative'),('cholesterol',1,'707084003','HDL cholesterol 2'),
('cholesterol',1,'707086001','HDL cholesterol 2a'),('cholesterol',1,'707091000','IDL cholesterol 1'),('cholesterol',1,'707092007','IDL cholesterol 2'),('cholesterol',1,'707093002','LDL cholesterol pattern A'),('cholesterol',1,'707094008','LDL cholesterol pattern BI'),('cholesterol',1,'707095009','LDL cholesterol pattern BII'),('cholesterol',1,'707096005','LDL cholesterol, acetylated'),('cholesterol',1,'707097001','LDL cholesterol, narrow density'),('cholesterol',1,'707098006','Cholesterol in lipoprotein a'),('cholesterol',1,'707099003','VLDL cholesterol 3'),('cholesterol',1,'707100006','VLDL cholesterol, acetylated'),('cholesterol',1,'707101005','VLDL cholesterol, beta'),('cholesterol',1,'707124003','HDL cholesterol 2b'),('cholesterol',1,'707125002','HDL cholesterol 3'),('cholesterol',1,'707126001','HDL cholesterol 3a'),('cholesterol',1,'707127005','HDL cholesterol 3c'),('cholesterol',1,'707128000','HDL cholesterol 3b'),('cholesterol',1,'712626002','Cholesterol in chylomicrons'),('cholesterol',1,'13644009','High cholesterol'),('cholesterol',1,'124055002','Decreased cholesterol esters (finding)'),('cholesterol',1,'166828006','Serum cholesterol normal (finding)'),('cholesterol',1,'166830008','Serum cholesterol raised (finding)'),('cholesterol',1,'166831007','Serum cholesterol very high (finding)'),('cholesterol',1,'365793008','Finding of cholesterol level'),('cholesterol',1,'365794002','Finding of serum cholesterol level'),('cholesterol',1,'370992007','High blood cholesterol/triglycerides'),('cholesterol',1,'398036000','Low density lipoprotein catabolic defect'),('cholesterol',1,'442234001','Serum cholesterol borderline high (finding)'),('cholesterol',1,'442350007','Serum cholesterol borderline low (finding)'),('cholesterol',1,'445445006','Raised low density lipoprotein cholesterol'),('cholesterol',1,'67991000119104','Serum cholesterol abnormal (finding)'),('cholesterol',1,'850981000000101','Cholesterol level (observable entity)'),('cholesterol',1,'852401000000104','Maximum cholesterol level (observable entity)'),('cholesterol',1,'852411000000102','Minimum cholesterol level (observable entity)'),('cholesterol',1,'853681000000104','Total cholesterol level (observable entity)'),('cholesterol',1,'404670008','Hollenhorst plaque'),('cholesterol',1,'166854003','Lipoprotein electrophoresis - High density lipoprotein (procedure)'),('cholesterol',1,'166855002','Lipoprotein electrophoresis - Low density lipoprotein'),('cholesterol',1,'124054003','Increased cholesterol esters (finding)'),('cholesterol',1,'439953004','Elevated cholesterol/high density lipoprotein ratio'),('cholesterol',1,'102857004','Urinary crystal, cholesterol (finding)'),('cholesterol',1,'939391000000100','Serum high density lipoprotein cholesterol:triglyceride ratio'),('cholesterol',2,'1005671000000105','Serum cholesterol level'),('cholesterol',2,'412808005','Serum total cholesterol level'),('cholesterol',2,'121868005','Total cholesterol measurement (procedure)'),('cholesterol',2,'994351000000103','Serum total cholesterol level');
INSERT INTO #codessnomed
VALUES ('egfr',1,'1011481000000105','eGFR (estimated glomerular filtration rate) using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'1011491000000107','eGFR (estimated glomerular filtration rate) using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'1020291000000106','GFR (glomerular filtration rate) calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'1107411000000104','eGFR (estimated glomerular filtration rate) by laboratory calculation'),('egfr',1,'241373003','Technetium-99m-diethylenetriamine pentaacetic acid clearance - glomerular filtration rate (procedure)'),('egfr',1,'262300005','With glomerular filtration rate'),('egfr',1,'737105002','GFR (glomerular filtration rate) calculation technique'),('egfr',1,'80274001','Glomerular filtration rate (observable entity)'),('egfr',1,'996231000000108','GFR (glomerular filtration rate) calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin');
INSERT INTO #codessnomed
VALUES ('hba1c',1,'1019431000000105','HbA1c level (Diabetes Control and Complications Trial aligned)'),('hba1c',1,'1003671000000109','Haemoglobin A1c level'),('hba1c',1,'1049301000000100','HbA1c (haemoglobin A1c) level (diagnostic reference range) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'1049321000000109','HbA1c (haemoglobin A1c) level (monitoring ranges) - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'1107481000000106','HbA1c (haemoglobin A1c) molar concentration in blood'),('hba1c',1,'999791000000106','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised'),('hba1c',1,'1010941000000103','Haemoglobin A1c (monitoring ranges)'),('hba1c',1,'1010951000000100','Haemoglobin A1c (diagnostic reference range)'),('hba1c',1,'165679005','Haemoglobin A1c (HbA1c) less than 7% indicating good diabetic control'),('hba1c',1,'165680008','Haemoglobin A1c (HbA1c) between 7%-10% indicating borderline diabetic control'),('hba1c',1,'165681007','Hemoglobin A1c (HbA1c) greater than 10% indicating poor diabetic control'),('hba1c',1,'365845005','Haemoglobin A1C - diabetic control finding'),('hba1c',1,'444751005','High hemoglobin A1c level'),('hba1c',1,'43396009','Hemoglobin A1c measurement (procedure)'),('hba1c',1,'313835008','Hemoglobin A1c measurement aligned to the Diabetes Control and Complications Trial'),('hba1c',1,'371981000000106','Hb A1c (Haemoglobin A1c) level - IFCC (International Federation of Clinical Chemistry and Laboratory Medicine) standardised'),('hba1c',1,'444257008','Calculation of estimated average glucose based on haemoglobin A1c'),('hba1c',1,'269823000','Haemoglobin A1C - diabetic control interpretation'),('hba1c',1,'443911005','Ordinal level of hemoglobin A1c'),('hba1c',1,'733830002','HbA1c - Glycated haemoglobin-A1c'),('hba1c',2,'1019431000000105','HbA1c level (Diabetes Control and Complications Trial aligned)'),('hba1c',2,'999791000000106','Haemoglobin A1c level - International Federation of Clinical Chemistry and Laboratory Medicine standardised');
INSERT INTO #codessnomed
VALUES ('hdl-cholesterol',1,'1005681000000107','Serum high density lipoprotein cholesterol level (observable entity)'),('hdl-cholesterol',1,'1010581000000101','Plasma high density lipoprotein cholesterol level (observable entity)'),('hdl-cholesterol',1,'1026461000000104','Serum random high density lipoprotein cholesterol level (observable entity)');
INSERT INTO #codessnomed
VALUES ('ldl-cholesterol',1,'1010591000000104','Plasma low density lipoprotein cholesterol level (observable entity)'),('ldl-cholesterol',1,'1014501000000104','Calculated low density lipoprotein cholesterol level (observable entity)'),('ldl-cholesterol',1,'1022191000000100','Serum low density lipoprotein cholesterol level (observable entity)');
INSERT INTO #codessnomed
VALUES ('sex-hormone-binding-globulin',1,'999661000000105','Serum sex hormone binding globulin level (observable entity)');
INSERT INTO #codessnomed
VALUES ('testosterone',1,'270973006','Serum testosterone measurement (procedure)'),('testosterone',1,'995571000000101','Plasma testosterone level (observable entity)'),('testosterone',1,'997161000000108','Serum testosterone level (observable entity)');
INSERT INTO #codessnomed
VALUES ('vitamin-d',1,'1007991000000105','Serum total 25-hydroxy vitamin D level (observable entity)'),('vitamin-d',1,'1029801000000105','Total 25-hydroxyvitamin D level (observable entity)'),('vitamin-d',1,'1031181000000107','Serum vitamin D level (observable entity)'),('vitamin-d',1,'12199005','Vitamin D, 25-hydroxy measurement (procedure)'),('vitamin-d',1,'270990000','Serum vitamin D measurement (procedure)'),('vitamin-d',1,'83729008','Vitamin D measurement (procedure)'),('vitamin-d',1,'996641000000102','Combined total vitamin D2 and D3 level (observable entity)')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codessnomed;

IF OBJECT_ID('tempdb..#codesemis') IS NOT NULL DROP TABLE #codesemis;
CREATE TABLE #codesemis (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesemis
VALUES ('bmi',1,'EMISNQBM1','BMI centile')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesemis;


IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, version INT NOT NULL, [description] VARCHAR(255));

-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.concept, dcr.[version], dcr.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.concept, dcc.[version], dcc.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

-- EMIS codes with a FK Reference Coding ID
INSERT INTO #TempRefCodes
SELECT FK_Reference_Coding_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [version] INT NOT NULL, [description] VARCHAR(255));

-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.concept, dcs.[version], dcs.[description]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- EMIS codes with a FK SNOMED ID but without a FK Reference Coding ID
INSERT INTO #TempSNOMEDRefCodes
SELECT FK_Reference_SnomedCT_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID = -1
AND FK_Reference_SnomedCT_ID != -1;

-- De-duped tables
IF OBJECT_ID('tempdb..#CodeSets') IS NOT NULL DROP TABLE #CodeSets;
CREATE TABLE #CodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#SnomedSets') IS NOT NULL DROP TABLE #SnomedSets;
CREATE TABLE #SnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedCodeSets') IS NOT NULL DROP TABLE #VersionedCodeSets;
CREATE TABLE #VersionedCodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedSnomedSets') IS NOT NULL DROP TABLE #VersionedSnomedSets;
CREATE TABLE #VersionedSnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

INSERT INTO #VersionedCodeSets
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #VersionedSnomedSets
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

INSERT INTO #CodeSets
SELECT FK_Reference_Coding_ID, c.concept, [description]
FROM #VersionedCodeSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedCodeSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

INSERT INTO #SnomedSets
SELECT FK_Reference_SnomedCT_ID, c.concept, [description]
FROM #VersionedSnomedSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedSnomedSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

-- >>> Following code sets injected: bmi v2/hba1c v2/cholesterol v2/ldl-cholesterol v1/hdl-cholesterol v1/vitamin-d v1/testosterone v1/sex-hormone-binding-globulin v1/egfr v1

-- Get all biomarker values for the cohort
IF OBJECT_ID('tempdb..#biomarkers') IS NOT NULL DROP TABLE #biomarkers;
CREATE TABLE #biomarkers (
	FK_Patient_Link_ID BIGINT,
	Label VARCHAR(32),
	EventDate DATE,
	[Value] NVARCHAR(128)
);

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'bmi' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'bmi' AND [Version] = 2)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'bmi' AND [Version] = 2))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'hba1c' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'hba1c' AND [Version] = 2)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'hba1c' AND [Version] = 2))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'cholesterol' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'cholesterol' AND [Version] = 2)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'cholesterol' AND [Version] = 2))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'ldl' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'ldl-cholesterol' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'ldl-cholesterol' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'hdl' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'hdl-cholesterol' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'hdl-cholesterol' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'vitamin-d' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'vitamin-d' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'vitamin-d' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'testosterone' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'testosterone' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'testosterone' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'sex-hormone-binding-globulin' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'sex-hormone-binding-globulin' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'sex-hormone-binding-globulin' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

INSERT INTO #biomarkers
SELECT 
	FK_Patient_Link_ID,
  'egfr' AS Label,
	CAST(EventDate AS DATE) AS EventDate,
	[Value]
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE (Concept = 'egfr' AND [Version] = 1)) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE (Concept = 'egfr' AND [Version] = 1))
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate >= @StartDate
AND [Value] IS NOT NULL
AND [Value] != '0';

-- Final output
SELECT * FROM #biomarkers
ORDER BY FK_Patient_Link_ID, EventDate;