--┌──────────────────┐
--│ Main cohort file │
--└──────────────────┘

-- OUTPUT: Data with the following fields
-- 	- PatientId (int)
--  - DateOfFirstDiagnosis (YYYY-MM-DD) 

--Just want the output, not the messages
SET NOCOUNT ON;

--  - FirstCovidPositiveDate (DDMMYYYY)
--  - SecondCovidPositiveDate (DDMMYYYY)
--  - ThirdCovidPositiveDate (DDMMYYYY)
--  - FirstAdmissionPost1stCOVIDTest (DDMMYYYY)
--  - FirstAdmissionPost2ndCOVIDTest (DDMMYYYY)
--  - FirstAdmissionPost3rdCOVIDTest (DDMMYYYY)
--  - DateOfDeath (DDMMYYYY)
--  - DeathWithin28Days (Y/N)
--  - LSOA
--  - Months at this LSOA (if possible)
--  - YearOfBirth (YYYY)
--  - Sex (M/F)
--  - Ethnicity
--  - HasAsthma (Y/N) (at time of 1st COVID dx)
--  - HasIschemic heart disease (Y/N) (at time of 1st COVID dx)
--  - HasOther heart disease (Y/N) (at time of 1st COVID dx)
--  - HasStroke (Y/N) (at time of 1st COVID dx)
--  - HasDiabetes (Y/N) (at time of 1st COVID dx)
--  - HasCOPD (Y/N) (at time of 1st COVID dx)
--  - HasHypertension (Y/N) (at time of 1st COVID dx)
--  - WorstSmokingStatus (non-smoker / trivial smoker / non-trivial smoker)
--  - CurrentSmokingStatus (non-smoker / trivial smoker / non-trivial smoker)
--  - BMI (at time of 1st COVID dx)
--  - VaccineDose1Date (DDMMYYYY)
--  - VaccineDose2Date (DDMMYYYY)
--  - VaccineDose3Date (DDMMYYYY)
--  - VaccineDose4Date (DDMMYYYY)
--  - VaccineDose5Date (DDMMYYYY)
--  - IMD2019Decile1IsMostDeprived10IsLeastDeprived
--  - Occupation (realises may be poorly coded)
