--┌─────────────────────────────────┐
--│ Cancer Skin Non-melanoma        │
--└─────────────────────────────────┘


-- OUTPUT: A single table with the following:
--       [PK_Skin_Non-melanoma_ID]
--       ,[ExternalID]
--       ,[CreateDate]
--       ,[ModifDate]
--       ,[LoadID]
--       ,[Deleted]
--       ,[HDMModifDate]
--       ,[FK_Reference_Tenancy_ID]
--       ,[FK_Patient_Link_ID]
--       ,[FK_Patient_ID]
--       ,[NhsNo]
--       ,[FormInstance]
--       ,[FormDataID]
--       ,[FormID]
--       ,[ExamKey]
--       ,[CRISOrderNo]
--       ,[StatusID]
--       ,[Date]
--       ,[FormLoadedTS]
--       ,[EventKey]
--       ,[DeleteFlag]
--       ,[TStemp]
--       ,[ConsultantID]
--       ,[BatchUpdate]
--       ,[DateCreated]
--       ,[CreatedBy]
--       ,[DateModified]
--       ,[ModifiedBy]
--       ,[ACEComorbidities]
--       ,[ActionFollowingReferralForSecondOpinion]
--       ,[AnalDefunctioning]
--       ,[BasisOfDiagnosis]
--       ,[CauseOfImmunosuppression]
--       ,[ClinicalStage]
--       ,[ConsultantConferred]
--       ,[CurrentDiseaseStatusForThisCancer]
--       ,[CurrentProgressiveDisease]
--       ,[DateLesionFirstNoticed]
--       ,[DateOfDiagnosis]
--       ,[DateOfDiseaseProgression]
--       ,[DateOfOriginalDiagnosis]
--       ,[DateOfRelapse]
--       ,[DateOfSurgery]
--       ,[DateSeen]
--       ,[DefinitiveSurgeryPlanned]
--       ,[DefinitiveTreatmentPlanned]
--       ,[Diagnosis]
--       ,[Differentiation]
--       ,[DifferentiationFromNewBiopsy]
--       ,[DiseaseFreeFollowingPrimaryTreatment]
--       ,[EntryIntoAClinicalTrial]
--       ,[ExtracapsularExtension]
--       ,[GorlinSyndrome]
--       ,[GrowthPattern]
--       ,[Histology]
--       ,[HistologyFromNewBiopsy]
--       ,[HIVStatus]
--       ,[ImmediateProposedManagement]
--       ,[Immunosuppression]
--       ,[KaposisStaging]
--       ,[LesionThickness]
--       ,[ManagementDeclinedByPatient]
--       ,[MetastaticDiseaseIndicator]
--       ,[NewBiopsy]
--       ,[NodalStatus]
--       ,[NumberOfPositiveNodesLeft]
--       ,[NumberOfPositiveNodesRight]
--       ,[NumberOfPreviouslyTreatedLesions]
--       ,[PathStage]
--       ,[PatientAppropriateForGoldStandardsFramework]
--       ,[PatientWasReferredForSecondOpinion]
--       ,[PDTLaserFibre]
--       ,[PDTLight]
--       ,[PDTSensitiser]
--       ,[PerformanceStatus]
--       ,[PlannedChemotherapyRegimen]
--       ,[PlannedDefinitiveTreatment]
--       ,[PlannedRadiotherapyType]
--       ,[PlannedSurgery]
--       ,[PresumedHistology]
--       ,[PreviousRadiotherapySiteS]
--       ,[PreviousSurgeryForThisCancer]
--       ,[PreviousSystemicChemotherapyRegimens]
--       ,[PreviousTreatmentForThisCancer]
--       ,[PreviouslyTreatedSkinLesions]
--       ,[PrimaryDiseaseSite]
--       ,[PrimaryTreatmentGivenWithCurativeIntent]
--       ,[ReferralSource]
--       ,[ReferredBy]
--       ,[ReferringHospital]
--       ,[ResectionMarginDistance]
--       ,[ResponsibleConsultant]
--       ,[SeenBy]
--       ,[Side]
--       ,[SiteOfLesion]
--       ,[SitesOfCurrentDisease]
--       ,[SitesOfPlannedRadiotherapy]
--       ,[SitesOfPreviouslyTreatedLesions]
--       ,[SkinSite]
--       ,[TreatmentIntent]
--       ,[TreatmentStatusForThisCancer]
--       ,[TrialName]
--       ,[UltrasoundScanned]
--       ,[CreatedBySurname]
--       ,[CreatedByForename]
--       ,[CreatedByUserDepartment]
--       ,[CreatedByUserEmployer]
--       ,[ModifiedBySurname]
--       ,[ModifiedByForename]
--       ,[ModifiedByUserDepartment]
--       ,[ModifiedByUserEmployer]

--Just want the output, not the messages
SET NOCOUNT ON;


/* simulating a select * except one column */
IF OBJECT_ID('tempdb..#TempTable') IS NOT NULL DROP TABLE #TempTable;
SELECT [FK_Patient_Link_ID] AS PatientId, * INTO #TempTable
FROM [SharedCare].[Cancer_Skin_Non-Melanoma];

/* Drop the columns that are not needed */
ALTER TABLE #TempTable
DROP COLUMN [PK_Skin_Non-melanoma_ID], [FK_Patient_Link_ID], [FK_Patient_ID];

SELECT * FROM #TempTable;