--┌─────────────────────────────────┐
--│ Cancer ovary                    │
--└─────────────────────────────────┘


-- OUTPUT: A single table with the following:
--       [PK_Ovary_Cancer_ID]
--       ,[ExternalID]
--       ,[CreateDate]
--       ,[ModifDate]
--       ,[LoadID]
--       ,[Deleted]
--       ,[HDMModifDate]
--       ,[FK_Reference_Tenancy_ID]
--       ,[FK_Patient_Link_ID]
--       ,[FK_Patient_ID]
--       ,[NhsNo]
--       ,[FormInstance]
--       ,[FormDataID]
--       ,[FormID]
--       ,[ExamKey]
--       ,[CRISOrderNo]
--       ,[StatusID]
--       ,[Date]
--       ,[FormLoadedTS]
--       ,[EventKey]
--       ,[DeleteFlag]
--       ,[TStemp]
--       ,[ConsultantID]
--       ,[BatchUpdate]
--       ,[DateCreated]
--       ,[CreatedBy]
--       ,[DateModified]
--       ,[ModifiedBy]
--       ,[ACEComorbidities]
--       ,[ActionFollowingReferralForSecondOpinion]
--       ,[BasisOfDiagnosis]
--       ,[BowelFunction]
--       ,[Ca125AtDiagnosis]
--       ,[Ca125PriorToThisReferral]
--       ,[ClinicalFrailtyScale]
--       ,[ClinicalStage]
--       ,[ClosestMarginSite]
--       ,[ConsultantConferred]
--       ,[CurrentDiseaseStatusForThisCancer]
--       ,[CurrentProgressiveDisease]
--       ,[DateOfBiopsy]
--       ,[DateOfDiagnosis]
--       ,[DateOfDiseaseProgression]
--       ,[DateOfOriginalDiagnosis]
--       ,[DateOfRelapse]
--       ,[DateOfSurgery]
--       ,[DateSeen]
--       ,[DateSymptomsFirstNoted]
--       ,[DefinitiveSurgeryPlanned]
--       ,[Diagnosis]
--       ,[Differentiation]
--       ,[DifferentiationFromNewBiopsy]
--       ,[DiseaseFreeFollowingPrimaryTreatment]
--       ,[EntryIntoAClinicalTrial]
--       ,[GeneticStatus]
--       ,[Histology]
--       ,[HistologyFromNewBiopsy]
--       ,[HIVStatus]
--       ,[ImmediateProposedManagement]
--       ,[InhibinLevelPriorToPrimaryTreatment]
--       ,[InvolvedNodes]
--       ,[IsBrachytherapyPlanned]
--       ,[IsSubsequentChemotherapyPlanned]
--       ,[IsThisTheDateOfDiagnosis]
--       ,[KeyWorkerName]
--       ,[LVSI]
--       ,[LVSIFromNewBiopsy]
--       ,[ManagementDeclinedByPatient]
--       ,[MetastaticDiseaseIndicator]
--       ,[MostRecentInhibinLevel]
--       ,[MostRecentTestosteroneLevel]
--       ,[NewBiopsy]
--       ,[NumberOfProceduresForThisCancer]
--       ,[NumberOfSurgicalOperationsForThisCancer]
--       ,[OtherInvolvedNodes]
--       ,[OtherSiteSOfCurrentDisease]
--       ,[PathStage]
--       ,[PatientAppropriateForGoldStandardsFramework]
--       ,[PatientWasReferredForSecondOpinion]
--       ,[PerformanceStatus]
--       ,[PlannedAccess]
--       ,[PlannedBiologicalTherapyType]
--       ,[PlannedChemotherapyRegimen]
--       ,[PlannedSurgicalProcedures]
--       ,[PlatinumResistance]
--       ,[PreviousBiologicalTherapy]
--       ,[PreviousChemotherapyLines]
--       ,[PreviousChemotherapyRegimen2]
--       ,[PreviousChemotherapyRegimen3]
--       ,[PreviousNeoAdjuvantSACTRegime]
--       ,[PreviousPelvicSurgery]
--       ,[PreviousRadiotherapyCentre]
--       ,[PreviousSACTRegimen]
--       ,[PreviousSurgicalProcedureForThisCancer2]
--       ,[PreviousSurgicalProceduresForThisCancer]
--       ,[PreviousTreatmentForThisCancer]
--       ,[PrimaryDiseaseSite]
--       ,[PrimaryTreatmentGivenWithCurativeIntent]
--       ,[ReferredBy]
--       ,[ReferredForGeneticOpinion]
--       ,[ReferringHospital]
--       ,[ResectionMarginDistance]
--       ,[ResponsibleConsultant]
--       ,[SeenBy]
--       ,[SeenByKeyWorker]
--       ,[SexualFunction]
--       ,[Side]
--       ,[SitesOfCurrentDisease]
--       ,[SourceOfTissueDiagnosis]
--       ,[SurgicalCompleteness]
--       ,[SynchronousEndometrialCancer]
--       ,[TestosteroneLevelPriorToPrimaryTreatment]
--       ,[TreatmentIntent]
--       ,[TreatmentStatusForThisCancer]
--       ,[TrialName]
--       ,[TumourSizeCm]
--       ,[UrinaryFunction]
--       ,[CreatedBySurname]
--       ,[CreatedByForename]
--       ,[CreatedByUserDepartment]
--       ,[CreatedByUserEmployer]
--       ,[ModifiedBySurname]
--       ,[ModifiedByForename]
--       ,[ModifiedByUserDepartment]
--       ,[ModifiedByUserEmployer]

--Just want the output, not the messages
SET NOCOUNT ON;


/* simulating a select * except one column */
IF OBJECT_ID('tempdb..#TempTable') IS NOT NULL DROP TABLE #TempTable;
SELECT [FK_Patient_Link_ID] AS PatientID, * INTO #TempTable
FROM [SharedCare].[Cancer_Ovary];

/* Drop the columns that are not needed */
ALTER TABLE #TempTable
DROP COLUMN [FK_Patient_Link_ID], [FK_Patient_ID];

SELECT * FROM #TempTable;