--┌────────────────────────────────────┐
--│ Covid Test Outcomes	               │
--└────────────────────────────────────┘

------------ RESEARCH DATA ENGINEER CHECK ------------
-- 

-- OUTPUT: Data with the following fields
-- Patient Id
-- TestOutcome (positive/negative/inconclusive)
-- TestDate (DD-MM-YYYY)

-- Set the start date
DECLARE @StartDate datetime;
DECLARE @EndDate datetime;
SET @StartDate = '2020-03-01';
SET @EndDate = '2022-03-01';

--Just want the output, not the messages
SET NOCOUNT ON;

-- Find all patients alive at start date
IF OBJECT_ID('tempdb..#PossiblePatients') IS NOT NULL DROP TABLE #PossiblePatients;
SELECT PK_Patient_Link_ID as FK_Patient_Link_ID, EthnicMainGroup, DeathDate INTO #PossiblePatients FROM [RLS].vw_Patient_Link
WHERE (DeathDate IS NULL OR DeathDate >= @StartDate);

-- Find all patients registered with a GP
IF OBJECT_ID('tempdb..#PatientsWithGP') IS NOT NULL DROP TABLE #PatientsWithGP;
SELECT DISTINCT FK_Patient_Link_ID INTO #PatientsWithGP FROM [RLS].vw_Patient
where FK_Reference_Tenancy_ID = 2;

-- Make cohort from patients alive at start date and registered with a GP
IF OBJECT_ID('tempdb..#Patients') IS NOT NULL DROP TABLE #Patients;
SELECT pp.* INTO #Patients FROM #PossiblePatients pp
INNER JOIN #PatientsWithGP gp on gp.FK_Patient_Link_ID = pp.FK_Patient_Link_ID;


--------------------------------------------------------------------------------------------------------
----------------------------------- DEFINE MAIN COHORT -- ----------------------------------------------
--------------------------------------------------------------------------------------------------------

-- LOAD CODESETS FOR CONDITIONS THAT INDICATE RISK OF CKD

-- >>> Codesets required... Inserting the code set code
--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘

-- OBJECTIVE: To populate temporary tables with the existing clinical code sets.
--            See the [SQL-generation-process.md](SQL-generation-process.md) for more details.

-- INPUT: No pre-requisites

-- OUTPUT: Five temp tables as follows:
--  #AllCodes (Concept, Version, Code)
--  #CodeSets (FK_Reference_Coding_ID, Concept)
--  #SnomedSets (FK_Reference_SnomedCT_ID, FK_SNOMED_ID)
--  #VersionedCodeSets (FK_Reference_Coding_ID, Concept, Version)
--  #VersionedSnomedSets (FK_Reference_SnomedCT_ID, Version, FK_SNOMED_ID)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

IF OBJECT_ID('tempdb..#AllCodes') IS NOT NULL DROP TABLE #AllCodes;
CREATE TABLE #AllCodes (
  [Concept] [varchar](255) NOT NULL,
  [Version] INT NOT NULL,
  [Code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
  [description] [varchar] (255) NULL 
);

IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('diabetes',1,'C10..',NULL,'Diabetes mellitus'),('diabetes',1,'C10..00',NULL,'Diabetes mellitus'),('diabetes',1,'C100.',NULL,'Diabetes mellitus with no mention of complication'),('diabetes',1,'C100.00',NULL,'Diabetes mellitus with no mention of complication'),('diabetes',1,'C1000',NULL,'Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes',1,'C100000',NULL,'Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes',1,'C1001',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes',1,'C100100',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes',1,'C100z',NULL,'Diabetes mellitus NOS with no mention of complication'),('diabetes',1,'C100z00',NULL,'Diabetes mellitus NOS with no mention of complication'),('diabetes',1,'C101.',NULL,'Diabetes mellitus with ketoacidosis'),('diabetes',1,'C101.00',NULL,'Diabetes mellitus with ketoacidosis'),('diabetes',1,'C1010',NULL,'Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes',1,'C101000',NULL,'Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes',1,'C101100',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes',1,'C101y',NULL,'Other specified diabetes mellitus with ketoacidosis'),('diabetes',1,'C101y00',NULL,'Other specified diabetes mellitus with ketoacidosis'),('diabetes',1,'C101z',NULL,'Diabetes mellitus NOS with ketoacidosis'),('diabetes',1,'C101z00',NULL,'Diabetes mellitus NOS with ketoacidosis'),('diabetes',1,'C102.',NULL,'Diabetes mellitus with hyperosmolar coma'),('diabetes',1,'C102.00',NULL,'Diabetes mellitus with hyperosmolar coma'),('diabetes',1,'C1020',NULL,'Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes',1,'C102000',NULL,'Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes',1,'C102100',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes',1,'C102z',NULL,'Diabetes mellitus NOS with hyperosmolar coma'),('diabetes',1,'C102z00',NULL,'Diabetes mellitus NOS with hyperosmolar coma'),('diabetes',1,'C103.',NULL,'Diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C103.00',NULL,'Diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C1030',NULL,'Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes',1,'C103000',NULL,'Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes',1,'C103100',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes',1,'C103y',NULL,'Other specified diabetes mellitus with coma'),('diabetes',1,'C103y00',NULL,'Other specified diabetes mellitus with coma'),('diabetes',1,'C103z',NULL,'Diabetes mellitus NOS with ketoacidotic coma'),('diabetes',1,'C103z00',NULL,'Diabetes mellitus NOS with ketoacidotic coma'),('diabetes',1,'C104.',NULL,'Diabetes mellitus with renal manifestation'),('diabetes',1,'C104.00',NULL,'Diabetes mellitus with renal manifestation'),('diabetes',1,'C1040',NULL,'Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes',1,'C104000',NULL,'Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes',1,'C104100',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes',1,'C104y',NULL,'Other specified diabetes mellitus with renal complications'),('diabetes',1,'C104y00',NULL,'Other specified diabetes mellitus with renal complications'),('diabetes',1,'C104z',NULL,'Diabetes mellitus with nephropathy NOS'),('diabetes',1,'C104z00',NULL,'Diabetes mellitus with nephropathy NOS'),('diabetes',1,'C105.',NULL,'Diabetes mellitus with ophthalmic manifestation'),('diabetes',1,'C105.00',NULL,'Diabetes mellitus with ophthalmic manifestation'),('diabetes',1,'C1050',NULL,'Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes',1,'C105000',NULL,'Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes',1,'C105100',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes',1,'C105y',NULL,'Other specified diabetes mellitus with ophthalmic complications'),('diabetes',1,'C105y00',NULL,'Other specified diabetes mellitus with ophthalmic complications'),('diabetes',1,'C105z',NULL,'Diabetes mellitus NOS with ophthalmic manifestation'),('diabetes',1,'C105z00',NULL,'Diabetes mellitus NOS with ophthalmic manifestation'),('diabetes',1,'C106.',NULL,'Diabetes mellitus with neurological manifestation'),('diabetes',1,'C106.00',NULL,'Diabetes mellitus with neurological manifestation'),('diabetes',1,'C1060',NULL,'Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes',1,'C106000',NULL,'Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes',1,'C106100',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes',1,'C106y',NULL,'Other specified diabetes mellitus with neurological complications'),('diabetes',1,'C106y00',NULL,'Other specified diabetes mellitus with neurological complications'),('diabetes',1,'C106z',NULL,'Diabetes mellitus NOS with neurological manifestation'),('diabetes',1,'C106z00',NULL,'Diabetes mellitus NOS with neurological manifestation'),('diabetes',1,'C107.',NULL,'Diabetes mellitus with peripheral circulatory disorder'),('diabetes',1,'C107.00',NULL,'Diabetes mellitus with peripheral circulatory disorder'),('diabetes',1,'C1070',NULL,'Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes',1,'C107000',NULL,'Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes',1,'C107100',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes',1,'C1072',NULL,'Diabetes mellitus, adult with gangrene'),('diabetes',1,'C107200',NULL,'Diabetes mellitus, adult with gangrene'),('diabetes',1,'C107y',NULL,'Other specified diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C107y00',NULL,'Other specified diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C107z',NULL,'Diabetes mellitus NOS with peripheral circulatory disorder'),('diabetes',1,'C107z00',NULL,'Diabetes mellitus NOS with peripheral circulatory disorder'),('diabetes',1,'C108.',NULL,'Insulin dependent diabetes mellitus'),('diabetes',1,'C108.00',NULL,'Insulin dependent diabetes mellitus'),('diabetes',1,'C1080',NULL,'Insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C108000',NULL,'Insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C1081',NULL,'Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C108100',NULL,'Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C1082',NULL,'Insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C108200',NULL,'Insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C1083',NULL,'Insulin dependent diabetes mellitus with multiple complications'),('diabetes',1,'C108300',NULL,'Insulin dependent diabetes mellitus with multiple complications'),('diabetes',1,'C1084',NULL,'Unstable insulin dependent diabetes mellitus'),('diabetes',1,'C108400',NULL,'Unstable insulin dependent diabetes mellitus'),('diabetes',1,'C1085',NULL,'Insulin dependent diabetes mellitus with ulcer'),('diabetes',1,'C108500',NULL,'Insulin dependent diabetes mellitus with ulcer'),('diabetes',1,'C1086',NULL,'Insulin dependent diabetes mellitus with gangrene'),('diabetes',1,'C108600',NULL,'Insulin dependent diabetes mellitus with gangrene'),('diabetes',1,'C1087',NULL,'Insulin dependent diabetes mellitus with retinopathy'),('diabetes',1,'C108700',NULL,'Insulin dependent diabetes mellitus with retinopathy'),('diabetes',1,'C1088',NULL,'Insulin dependent diabetes mellitus - poor control'),('diabetes',1,'C108800',NULL,'Insulin dependent diabetes mellitus - poor control'),('diabetes',1,'C1089',NULL,'Insulin dependent diabetes maturity onset'),('diabetes',1,'C108900',NULL,'Insulin dependent diabetes maturity onset'),('diabetes',1,'C108A',NULL,'Insulin-dependent diabetes without complication'),('diabetes',1,'C108A00',NULL,'Insulin-dependent diabetes without complication'),('diabetes',1,'C108B',NULL,'Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes',1,'C108B00',NULL,'Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes',1,'C108C',NULL,'Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes',1,'C108C00',NULL,'Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes',1,'C108D',NULL,'Insulin dependent diabetes mellitus with nephropathy'),('diabetes',1,'C108D00',NULL,'Insulin dependent diabetes mellitus with nephropathy'),('diabetes',1,'C108E',NULL,'Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C108E00',NULL,'Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C108F',NULL,'Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes',1,'C108F00',NULL,'Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes',1,'C108G',NULL,'Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C108G00',NULL,'Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C108H',NULL,'Insulin dependent diabetes mellitus with arthropathy'),
('diabetes',1,'C108H00',NULL,'Insulin dependent diabetes mellitus with arthropathy'),('diabetes',1,'C108J',NULL,'Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C108J00',NULL,'Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C108y',NULL,'Other specified diabetes mellitus with multiple complications'),('diabetes',1,'C108y00',NULL,'Other specified diabetes mellitus with multiple complications'),('diabetes',1,'C108z',NULL,'Unspecified diabetes mellitus with multiple complications'),('diabetes',1,'C108z00',NULL,'Unspecified diabetes mellitus with multiple complications'),('diabetes',1,'C109.',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes',1,'C109.00',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C109000',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C109100',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C109200',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes',1,'C109300',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes',1,'C1094',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes',1,'C109400',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes',1,'C1095',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes',1,'C109500',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes',1,'C1096',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes',1,'C109600',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes',1,'C1097',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes',1,'C109700',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes',1,'C1098',NULL,'Reavens syndrome'),('diabetes',1,'C109800',NULL,'Reavens syndrome'),('diabetes',1,'C1099',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes',1,'C109900',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes',1,'C109A',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes',1,'C109A00',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes',1,'C109B',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes',1,'C109B00',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes',1,'C109C',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes',1,'C109C00',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes',1,'C109D',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C109D00',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C109E',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes',1,'C109E00',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes',1,'C109F',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C109F00',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C109G',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes',1,'C109G00',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes',1,'C109H',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C109H00',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C109J',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes',1,'C109J00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes',1,'C109K',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes',1,'C109K00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes',1,'C10A.',NULL,'Malnutrition-related diabetes mellitus'),('diabetes',1,'C10A.00',NULL,'Malnutrition-related diabetes mellitus'),('diabetes',1,'C10A0',NULL,'Malnutrition-related diabetes mellitus with coma'),('diabetes',1,'C10A000',NULL,'Malnutrition-related diabetes mellitus with coma'),('diabetes',1,'C10A1',NULL,'Malnutrition-related diabetes mellitus with ketoacidosis'),('diabetes',1,'C10A100',NULL,'Malnutrition-related diabetes mellitus with ketoacidosis'),('diabetes',1,'C10A2',NULL,'Malnutrition-related diabetes mellitus with renal complications'),('diabetes',1,'C10A200',NULL,'Malnutrition-related diabetes mellitus with renal complications'),('diabetes',1,'C10A3',NULL,'Malnutrition-related diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10A300',NULL,'Malnutrition-related diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10A4',NULL,'Malnutrition-related diabetes mellitus with neurological complications'),('diabetes',1,'C10A400',NULL,'Malnutrition-related diabetes mellitus with neurological complications'),('diabetes',1,'C10A5',NULL,'Malnutrition-related diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C10A500',NULL,'Malnutrition-related diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C10A6',NULL,'Malnutrition-related diabetes mellitus with multiple complications'),('diabetes',1,'C10A600',NULL,'Malnutrition-related diabetes mellitus with multiple complications'),('diabetes',1,'C10A7',NULL,'Malnutrition-related diabetes mellitus without complications'),('diabetes',1,'C10A700',NULL,'Malnutrition-related diabetes mellitus without complications'),('diabetes',1,'C10AW',NULL,'Malnutrition-related diabetes mellitus with unspecified complications'),('diabetes',1,'C10AW00',NULL,'Malnutrition-related diabetes mellitus with unspecified complications'),('diabetes',1,'C10AX',NULL,'Malnutrition-related diabetes mellitus with other specified complications'),('diabetes',1,'C10AX00',NULL,'Malnutrition-related diabetes mellitus with other specified complications'),('diabetes',1,'C10B.',NULL,'Diabetes mellitus induced by steroids'),('diabetes',1,'C10B.00',NULL,'Diabetes mellitus induced by steroids'),('diabetes',1,'C10B0',NULL,'Steroid induced diabetes mellitus without complication'),('diabetes',1,'C10B000',NULL,'Steroid induced diabetes mellitus without complication'),('diabetes',1,'C10C.',NULL,'Diabetes mellitus autosomal dominant'),('diabetes',1,'C10C.00',NULL,'Diabetes mellitus autosomal dominant'),('diabetes',1,'C10D.',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes',1,'C10D.00',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes',1,'C10E.',NULL,'Type 1 diabetes mellitus'),('diabetes',1,'C10E.00',NULL,'Type 1 diabetes mellitus'),('diabetes',1,'C10E0',NULL,'Type 1 diabetes mellitus with renal complications'),('diabetes',1,'C10E000',NULL,'Type 1 diabetes mellitus with renal complications'),('diabetes',1,'C10E1',NULL,'Type 1 diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10E100',NULL,'Type 1 diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10E2',NULL,'Type 1 diabetes mellitus with neurological complications'),('diabetes',1,'C10E200',NULL,'Type 1 diabetes mellitus with neurological complications'),('diabetes',1,'C10E3',NULL,'Type 1 diabetes mellitus with multiple complications'),('diabetes',1,'C10E300',NULL,'Type 1 diabetes mellitus with multiple complications'),('diabetes',1,'C10E4',NULL,'Unstable type 1 diabetes mellitus'),('diabetes',1,'C10E400',NULL,'Unstable type 1 diabetes mellitus'),('diabetes',1,'C10E5',NULL,'Type 1 diabetes mellitus with ulcer'),('diabetes',1,'C10E500',NULL,'Type 1 diabetes mellitus with ulcer'),('diabetes',1,'C10E6',NULL,'Type 1 diabetes mellitus with gangrene'),('diabetes',1,'C10E600',NULL,'Type 1 diabetes mellitus with gangrene'),('diabetes',1,'C10E7',NULL,'Type 1 diabetes mellitus with retinopathy'),('diabetes',1,'C10E700',NULL,'Type 1 diabetes mellitus with retinopathy'),('diabetes',1,'C10E8',NULL,'Type 1 diabetes mellitus - poor control'),('diabetes',1,'C10E800',NULL,'Type 1 diabetes mellitus - poor control'),('diabetes',1,'C10E9',NULL,'Type 1 diabetes mellitus maturity onset'),('diabetes',1,'C10E900',NULL,'Type 1 diabetes mellitus maturity onset'),('diabetes',1,'C10EA',NULL,'Type 1 diabetes mellitus without complication'),('diabetes',1,'C10EA00',NULL,'Type 1 diabetes mellitus without complication'),('diabetes',1,'C10EB',NULL,'Type 1 diabetes mellitus with mononeuropathy'),('diabetes',1,'C10EB00',NULL,'Type 1 diabetes mellitus with mononeuropathy'),('diabetes',1,'C10EC',NULL,'Type 1 diabetes mellitus with polyneuropathy'),('diabetes',1,'C10EC00',NULL,'Type 1 diabetes mellitus with polyneuropathy'),('diabetes',1,'C10ED',NULL,'Type 1 diabetes mellitus with nephropathy'),('diabetes',1,'C10ED00',NULL,'Type 1 diabetes mellitus with nephropathy'),('diabetes',1,'C10EE',NULL,'Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C10EE00',NULL,'Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C10EF',NULL,'Type 1 diabetes mellitus with diabetic cataract'),('diabetes',1,'C10EF00',NULL,'Type 1 diabetes mellitus with diabetic cataract'),('diabetes',1,'C10EG',NULL,'Type 1 diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C10EG00',NULL,'Type 1 diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C10EH',NULL,'Type 1 diabetes mellitus with arthropathy'),('diabetes',1,'C10EH00',NULL,'Type 1 diabetes mellitus with arthropathy'),('diabetes',1,'C10EJ',NULL,'Type 1 diabetes mellitus with neuropathic arthropathy'),
('diabetes',1,'C10EJ00',NULL,'Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C10EK',NULL,'Type 1 diabetes mellitus with persistent proteinuria'),('diabetes',1,'C10EK00',NULL,'Type 1 diabetes mellitus with persistent proteinuria'),('diabetes',1,'C10EL',NULL,'Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'C10EL00',NULL,'Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'C10EM',NULL,'Type 1 diabetes mellitus with ketoacidosis'),('diabetes',1,'C10EM00',NULL,'Type 1 diabetes mellitus with ketoacidosis'),('diabetes',1,'C10EN',NULL,'Type 1 diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C10EN00',NULL,'Type 1 diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C10EP',NULL,'Type 1 diabetes mellitus with exudative maculopathy'),('diabetes',1,'C10EP00',NULL,'Type 1 diabetes mellitus with exudative maculopathy'),('diabetes',1,'C10EQ',NULL,'Type 1 diabetes mellitus with gastroparesis'),('diabetes',1,'C10EQ00',NULL,'Type 1 diabetes mellitus with gastroparesis'),('diabetes',1,'C10ER',NULL,'Latent autoimmune diabetes mellitus in adult'),('diabetes',1,'C10ER00',NULL,'Latent autoimmune diabetes mellitus in adult'),('diabetes',1,'C10F.',NULL,'Type 2 diabetes mellitus'),('diabetes',1,'C10F.00',NULL,'Type 2 diabetes mellitus'),('diabetes',1,'C10F0',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes',1,'C10F000',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes',1,'C10F1',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10F100',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10F2',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes',1,'C10F200',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes',1,'C10F3',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes',1,'C10F300',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes',1,'C10F4',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes',1,'C10F400',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes',1,'C10F5',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes',1,'C10F500',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes',1,'C10F6',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes',1,'C10F600',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes',1,'C10F7',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes',1,'C10F700',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes',1,'C10F8',NULL,'Reavens syndrome'),('diabetes',1,'C10F800',NULL,'Reavens syndrome'),('diabetes',1,'C10F9',NULL,'Type 2 diabetes mellitus without complication'),('diabetes',1,'C10F900',NULL,'Type 2 diabetes mellitus without complication'),('diabetes',1,'C10FA',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes',1,'C10FA00',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes',1,'C10FB',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes',1,'C10FB00',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes',1,'C10FC',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes',1,'C10FC00',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes',1,'C10FD',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C10FD00',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'C10FE',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes',1,'C10FE00',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes',1,'C10FF',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C10FF00',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes',1,'C10FG',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes',1,'C10FG00',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes',1,'C10FH',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C10FH00',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'C10FJ',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes',1,'C10FJ00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes',1,'C10FK',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes',1,'C10FK00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes',1,'C10FL',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes',1,'C10FL00',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes',1,'C10FM',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'C10FM00',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'C10FN',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes',1,'C10FN00',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes',1,'C10FP',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C10FP00',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C10FQ',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),('diabetes',1,'C10FQ00',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),('diabetes',1,'C10FR',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes',1,'C10FR00',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes',1,'C10FS',NULL,'Maternally inherited diabetes mellitus'),('diabetes',1,'C10FS00',NULL,'Maternally inherited diabetes mellitus'),('diabetes',1,'C10G.',NULL,'Secondary pancreatic diabetes mellitus'),('diabetes',1,'C10G.00',NULL,'Secondary pancreatic diabetes mellitus'),('diabetes',1,'C10G0',NULL,'Secondary pancreatic diabetes mellitus without complication'),('diabetes',1,'C10G000',NULL,'Secondary pancreatic diabetes mellitus without complication'),('diabetes',1,'C10H.',NULL,'Diabetes mellitus induced by non-steroid drugs'),('diabetes',1,'C10H.00',NULL,'Diabetes mellitus induced by non-steroid drugs'),('diabetes',1,'C10H0',NULL,'Diabetes mellitus induced by non-steroid drugs without complication'),('diabetes',1,'C10H000',NULL,'Diabetes mellitus induced by non-steroid drugs without complication'),('diabetes',1,'C10M.',NULL,'Lipoatrophic diabetes mellitus'),('diabetes',1,'C10M.00',NULL,'Lipoatrophic diabetes mellitus'),('diabetes',1,'C10M0',NULL,'Lipoatrophic diabetes mellitus without complication'),('diabetes',1,'C10M000',NULL,'Lipoatrophic diabetes mellitus without complication'),('diabetes',1,'C10N.',NULL,'Secondary diabetes mellitus'),('diabetes',1,'C10N.00',NULL,'Secondary diabetes mellitus'),('diabetes',1,'C10N0',NULL,'Secondary diabetes mellitus without complication'),('diabetes',1,'C10N000',NULL,'Secondary diabetes mellitus without complication'),('diabetes',1,'C10N1',NULL,'Cystic fibrosis related diabetes mellitus'),('diabetes',1,'C10N100',NULL,'Cystic fibrosis related diabetes mellitus'),('diabetes',1,'C10Q.',NULL,'Maturity onset diabetes of the young type 5'),('diabetes',1,'C10Q.00',NULL,'Maturity onset diabetes of the young type 5'),('diabetes',1,'C10y.',NULL,'Diabetes mellitus with other specified manifestation'),('diabetes',1,'C10y.00',NULL,'Diabetes mellitus with other specified manifestation'),('diabetes',1,'C10y0',NULL,'Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes',1,'C10y000',NULL,'Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes',1,'C10y100',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes',1,'C10yy',NULL,'Other specified diabetes mellitus with other specified complications'),('diabetes',1,'C10yy00',NULL,'Other specified diabetes mellitus with other specified complications'),('diabetes',1,'C10yz',NULL,'Diabetes mellitus NOS with other specified manifestation'),('diabetes',1,'C10yz00',NULL,'Diabetes mellitus NOS with other specified manifestation'),('diabetes',1,'C10z.',NULL,'Diabetes mellitus with unspecified complication'),('diabetes',1,'C10z.00',NULL,'Diabetes mellitus with unspecified complication'),('diabetes',1,'C10z0',NULL,'Diabetes mellitus, juvenile type, with unspecified complication'),('diabetes',1,'C10z000',NULL,'Diabetes mellitus, juvenile type, with unspecified complication'),('diabetes',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes',1,'C10z100',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes',1,'C10zy',NULL,'Other specified diabetes mellitus with unspecified complications'),('diabetes',1,'C10zy00',NULL,'Other specified diabetes mellitus with unspecified complications'),('diabetes',1,'C10zz',NULL,'Diabetes mellitus NOS with unspecified complication'),('diabetes',1,'C10zz00',NULL,'Diabetes mellitus NOS with unspecified complication'),('diabetes',1,'C1A0.',NULL,'Metabolic syndrome'),('diabetes',1,'C1A0.00',NULL,'Metabolic syndrome'),('diabetes',1,'Cyu2.',NULL,'[X]Diabetes mellitus'),('diabetes',1,'Cyu2.00',NULL,'[X]Diabetes mellitus'),('diabetes',1,'Cyu20',NULL,'[X]Other specified diabetes mellitus'),('diabetes',1,'Cyu2000',NULL,'[X]Other specified diabetes mellitus'),('diabetes',1,'Cyu21',NULL,'[X]Malnutrition-related diabetes mellitus with other specified complications'),('diabetes',1,'Cyu2100',NULL,'[X]Malnutrition-related diabetes mellitus with other specified complications'),('diabetes',1,'Cyu22',NULL,'[X]Malnutrition-related diabetes mellitus with unspecified complications'),('diabetes',1,'Cyu2200',NULL,'[X]Malnutrition-related diabetes mellitus with unspecified complications'),('diabetes',1,'Cyu23',NULL,'[X]Unspecified diabetes mellitus with renal complications'),('diabetes',1,'Cyu2300',NULL,'[X]Unspecified diabetes mellitus with renal complications'),('diabetes',1,'L180.',NULL,'Diabetes mellitus during pregnancy, childbirth and the puerperium'),('diabetes',1,'L180.00',NULL,'Diabetes mellitus during pregnancy, childbirth and the puerperium'),
('diabetes',1,'L1800',NULL,'Diabetes mellitus - unspecified whether during pregnancy or the puerperium'),('diabetes',1,'L180000',NULL,'Diabetes mellitus - unspecified whether during pregnancy or the puerperium'),('diabetes',1,'L1801',NULL,'Diabetes mellitus during pregnancy - baby delivered'),('diabetes',1,'L180100',NULL,'Diabetes mellitus during pregnancy - baby delivered'),('diabetes',1,'L1802',NULL,'Diabetes mellitus in the puerperium - baby delivered during current episode of care'),('diabetes',1,'L180200',NULL,'Diabetes mellitus in the puerperium - baby delivered during current episode of care'),('diabetes',1,'L1803',NULL,'Diabetes mellitus during pregnancy - baby not yet delivered'),('diabetes',1,'L180300',NULL,'Diabetes mellitus during pregnancy - baby not yet delivered'),('diabetes',1,'L1804',NULL,'Diabetes mellitus in the pueperium - baby delivered during previous episode of care'),('diabetes',1,'L180400',NULL,'Diabetes mellitus in the pueperium - baby delivered during previous episode of care'),('diabetes',1,'L1805',NULL,'Pre-existing diabetes mellitus, insulin-dependent'),('diabetes',1,'L180500',NULL,'Pre-existing diabetes mellitus, insulin-dependent'),('diabetes',1,'L1806',NULL,'Pre-existing diabetes mellitus, non-insulin-dependent'),('diabetes',1,'L180600',NULL,'Pre-existing diabetes mellitus, non-insulin-dependent'),('diabetes',1,'L1807',NULL,'Pre-existing malnutrition-related diabetes mellitus'),('diabetes',1,'L180700',NULL,'Pre-existing malnutrition-related diabetes mellitus'),('diabetes',1,'L1808',NULL,'Diabetes mellitus arising in pregnancy'),('diabetes',1,'L180800',NULL,'Diabetes mellitus arising in pregnancy'),('diabetes',1,'L1809',NULL,'Gestational diabetes mellitus'),('diabetes',1,'L180900',NULL,'Gestational diabetes mellitus'),('diabetes',1,'L180A',NULL,'Pre-existing type 1 diabetes mellitus in pregnancy'),('diabetes',1,'L180A00',NULL,'Pre-existing type 1 diabetes mellitus in pregnancy'),('diabetes',1,'L180B',NULL,'Pre-existing type 2 diabetes mellitus in pregnancy'),('diabetes',1,'L180B00',NULL,'Pre-existing type 2 diabetes mellitus in pregnancy'),('diabetes',1,'L180X',NULL,'Pre-existing diabetes mellitus, unspecified'),('diabetes',1,'L180X00',NULL,'Pre-existing diabetes mellitus, unspecified'),('diabetes',1,'L180z',NULL,'Diabetes mellitus during pregnancy, childbirth or the puerperium NOS'),('diabetes',1,'L180z00',NULL,'Diabetes mellitus during pregnancy, childbirth or the puerperium NOS'),('diabetes',1,'Lyu29',NULL,'[X]Pre-existing diabetes mellitus, unspecified'),('diabetes',1,'Lyu2900',NULL,'[X]Pre-existing diabetes mellitus, unspecified'),('diabetes',1,'PKyP.',NULL,'Diabetes insipidus, diabetes mellitus, optic atrophy and deafness'),('diabetes',1,'PKyP.00',NULL,'Diabetes insipidus, diabetes mellitus, optic atrophy and deafness'),('diabetes',1,'Q441.',NULL,'Neonatal diabetes mellitus'),('diabetes',1,'Q441.00',NULL,'Neonatal diabetes mellitus'),('diabetes',1,'ZV13F',NULL,'[V]Personal history of gestational diabetes mellitus'),('diabetes',1,'ZV13F00',NULL,'[V]Personal history of gestational diabetes mellitus');
INSERT INTO #codesreadv2
VALUES ('hypertension',1,'G2...',NULL,'Hypertensive disease'),('hypertension',1,'G2...00',NULL,'Hypertensive disease'),('hypertension',1,'G2z..',NULL,'Hypertensive disease NOS'),('hypertension',1,'G2z..00',NULL,'Hypertensive disease NOS'),('hypertension',1,'G2y..',NULL,'Other specified hypertensive disease'),('hypertension',1,'G2y..00',NULL,'Other specified hypertensive disease'),('hypertension',1,'G28..',NULL,'Stage 2 hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G28..00',NULL,'Stage 2 hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G26..',NULL,'Severe hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G26..00',NULL,'Severe hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G25..',NULL,'Stage 1 hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G25..00',NULL,'Stage 1 hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'G251.',NULL,'Stage 1 hypertension (NICE 2011) with evidence of end organ damage'),('hypertension',1,'G251.00',NULL,'Stage 1 hypertension (NICE 2011) with evidence of end organ damage'),('hypertension',1,'G250.',NULL,'Stage 1 hypertension (NICE 2011) without evidence of end organ damage'),('hypertension',1,'G250.00',NULL,'Stage 1 hypertension (NICE 2011) without evidence of end organ damage'),('hypertension',1,'G24..',NULL,'Secondary hypertension'),('hypertension',1,'G24..00',NULL,'Secondary hypertension'),('hypertension',1,'G24z.',NULL,'Secondary hypertension NOS'),('hypertension',1,'G24z.00',NULL,'Secondary hypertension NOS'),('hypertension',1,'G24zz',NULL,'Secondary hypertension NOS'),('hypertension',1,'G24zz00',NULL,'Secondary hypertension NOS'),('hypertension',1,'G24z0',NULL,'Secondary renovascular hypertension NOS'),('hypertension',1,'G24z000',NULL,'Secondary renovascular hypertension NOS'),('hypertension',1,'G244.',NULL,'Hypertension secondary to endocrine disorders'),('hypertension',1,'G244.00',NULL,'Hypertension secondary to endocrine disorders'),('hypertension',1,'G241.',NULL,'Secondary benign hypertension'),('hypertension',1,'G241.00',NULL,'Secondary benign hypertension'),('hypertension',1,'G241z',NULL,'Secondary benign hypertension NOS'),('hypertension',1,'G241z00',NULL,'Secondary benign hypertension NOS'),('hypertension',1,'G2410',NULL,'Secondary benign renovascular hypertension'),('hypertension',1,'G241000',NULL,'Secondary benign renovascular hypertension'),('hypertension',1,'G240.',NULL,'Secondary malignant hypertension'),('hypertension',1,'G240.00',NULL,'Secondary malignant hypertension'),('hypertension',1,'G240z',NULL,'Secondary malignant hypertension NOS'),('hypertension',1,'G240z00',NULL,'Secondary malignant hypertension NOS'),('hypertension',1,'G2400',NULL,'Secondary malignant renovascular hypertension'),('hypertension',1,'G240000',NULL,'Secondary malignant renovascular hypertension'),('hypertension',1,'G20..',NULL,'Essential hypertension'),('hypertension',1,'G20..00',NULL,'Essential hypertension'),('hypertension',1,'G20z.',NULL,'Essential hypertension NOS'),('hypertension',1,'G20z.00',NULL,'Essential hypertension NOS'),('hypertension',1,'G203.',NULL,'Diastolic hypertension'),('hypertension',1,'G203.00',NULL,'Diastolic hypertension'),('hypertension',1,'G202.',NULL,'Systolic hypertension'),('hypertension',1,'G202.00',NULL,'Systolic hypertension'),('hypertension',1,'G201.',NULL,'Benign essential hypertension'),('hypertension',1,'G201.00',NULL,'Benign essential hypertension'),('hypertension',1,'G200.',NULL,'Malignant essential hypertension'),('hypertension',1,'G200.00',NULL,'Malignant essential hypertension'),('hypertension',1,'Gyu2.',NULL,'[X]Hypertensive diseases'),('hypertension',1,'Gyu2.00',NULL,'[X]Hypertensive diseases'),('hypertension',1,'Gyu21',NULL,'[X]Hypertension secondary to other renal disorders'),('hypertension',1,'Gyu2100',NULL,'[X]Hypertension secondary to other renal disorders'),('hypertension',1,'Gyu20',NULL,'[X]Other secondary hypertension'),('hypertension',1,'Gyu2000',NULL,'[X]Other secondary hypertension');
INSERT INTO #codesreadv2
VALUES ('covid-positive-antigen-test',1,'43kB1',NULL,'SARS-CoV-2 antigen positive'),('covid-positive-antigen-test',1,'43kB100',NULL,'SARS-CoV-2 antigen positive');
INSERT INTO #codesreadv2
VALUES ('covid-positive-pcr-test',1,'4J3R6',NULL,'SARS-CoV-2 RNA pos lim detect'),('covid-positive-pcr-test',1,'4J3R600',NULL,'SARS-CoV-2 RNA pos lim detect'),('covid-positive-pcr-test',1,'A7952',NULL,'COVID-19 confirmed by laboratory test'),('covid-positive-pcr-test',1,'A795200',NULL,'COVID-19 confirmed by laboratory test'),('covid-positive-pcr-test',1,'43hF.',NULL,'Detection of SARS-CoV-2 by PCR'),('covid-positive-pcr-test',1,'43hF.00',NULL,'Detection of SARS-CoV-2 by PCR');
INSERT INTO #codesreadv2
VALUES ('covid-positive-test-other',1,'4J3R1',NULL,'2019-nCoV (novel coronavirus) detected'),('covid-positive-test-other',1,'4J3R100',NULL,'2019-nCoV (novel coronavirus) detected');
INSERT INTO #codesreadv2
VALUES ('egfr',1,'451E.',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'451E.00',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'451G.',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'451G.00',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'451K.',NULL,'Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'451K.00',NULL,'Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'451M.',NULL,'Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451M.00',NULL,'Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451N.',NULL,'Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'451N.00',NULL,'Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres');
INSERT INTO #codesreadv2
VALUES ('urinary-albumin-creatinine-ratio',1,'46TC.',NULL,'Urine albumin:creatinine ratio'),('urinary-albumin-creatinine-ratio',1,'46TC.00',NULL,'Urine albumin:creatinine ratio')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesreadv2;

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('diabetes',1,'C10..',NULL,'DM - Diabetes mellitus'),('diabetes',1,'C100.',NULL,'Diabetes mellitus with no mention of complication'),('diabetes',1,'C1000',NULL,'Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes',1,'C1001',NULL,'Maturity onset diabetes'),('diabetes',1,'C100z',NULL,'Diabetes mellitus NOS with no mention of complication'),('diabetes',1,'C101.',NULL,'Diabetic ketoacidosis'),('diabetes',1,'C1010',NULL,'Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes',1,'C101y',NULL,'Other specified diabetes mellitus with ketoacidosis'),('diabetes',1,'C101z',NULL,'Diabetes mellitus NOS with ketoacidosis'),('diabetes',1,'C102.',NULL,'Diabetes mellitus with hyperosmolar coma'),('diabetes',1,'C1020',NULL,'Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes',1,'C102z',NULL,'Diabetes mellitus NOS with hyperosmolar coma'),('diabetes',1,'C103.',NULL,'Diabetes mellitus with ketoacidotic coma'),('diabetes',1,'C1030',NULL,'Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes',1,'C103y',NULL,'Other specified diabetes mellitus with coma'),('diabetes',1,'C103z',NULL,'Diabetes mellitus NOS with ketoacidotic coma'),('diabetes',1,'C1040',NULL,'Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes',1,'C104y',NULL,'Other specified diabetes mellitus with renal complications'),('diabetes',1,'C104z',NULL,'Diabetes mellitus with nephropathy NOS'),('diabetes',1,'C105.',NULL,'Diabetes mellitus with ophthalmic manifestation'),('diabetes',1,'C1050',NULL,'Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes',1,'C105y',NULL,'Other specified diabetes mellitus with ophthalmic complications'),('diabetes',1,'C105z',NULL,'Diabetes mellitus NOS with ophthalmic manifestation'),('diabetes',1,'C1060',NULL,'Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes',1,'C106y',NULL,'Other specified diabetes mellitus with neurological complications'),('diabetes',1,'C106z',NULL,'Diabetes mellitus NOS with neurological manifestation'),('diabetes',1,'C1070',NULL,'Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes',1,'C1072',NULL,'Diabetes mellitus, adult with gangrene'),('diabetes',1,'C107y',NULL,'Other specified diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C107z',NULL,'Diabetes mellitus NOS with peripheral circulatory disorder'),('diabetes',1,'C1080',NULL,'Insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C1081',NULL,'Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C1082',NULL,'Insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C1083',NULL,'Insulin-dependent diabetes mellitus with multiple complications'),('diabetes',1,'C1085',NULL,'Insulin-dependent diabetes mellitus with ulcer'),('diabetes',1,'C1086',NULL,'Insulin-dependent diabetes mellitus with gangrene'),('diabetes',1,'C1087',NULL,'IDDM - Insulin-dependent diabetes mellitus with retinopathy'),('diabetes',1,'C1088',NULL,'Insulin-dependent diabetes mellitus - poor control'),('diabetes',1,'C1089',NULL,'Insulin-dependent diabetes maturity onset'),('diabetes',1,'C108y',NULL,'Other specified diabetes mellitus with multiple complications'),('diabetes',1,'C108z',NULL,'Unspecified diabetes mellitus with multiple complications'),('diabetes',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes',1,'C1094',NULL,'Non-insulin-dependent diabetes mellitus with ulcer'),('diabetes',1,'C1095',NULL,'Non-insulin-dependent diabetes mellitus with gangrene'),('diabetes',1,'C1096',NULL,'NIDDM - Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes',1,'C1097',NULL,'Non-insulin-dependent diabetes mellitus - poor control'),('diabetes',1,'C10A0',NULL,'Malnutrition-related diabetes mellitus with coma'),('diabetes',1,'C10A1',NULL,'Malnutrition-related diabetes mellitus with ketoacidosis'),('diabetes',1,'C10A2',NULL,'Malnutrition-related diabetes mellitus with renal complications'),('diabetes',1,'C10A3',NULL,'Malnutrition-related diabetes mellitus with ophthalmic complications'),('diabetes',1,'C10A4',NULL,'Malnutrition-related diabetes mellitus with neurological complications'),('diabetes',1,'C10A5',NULL,'Malnutrition-related diabetes mellitus with peripheral circulatory complications'),('diabetes',1,'C10A6',NULL,'Malnutrition-related diabetes mellitus with multiple complications'),('diabetes',1,'C10A7',NULL,'Malnutrition-related diabetes mellitus without complications'),('diabetes',1,'C10B0',NULL,'Steroid-induced diabetes mellitus without complication'),('diabetes',1,'C10y.',NULL,'Diabetes mellitus with other specified manifestation'),('diabetes',1,'C10y0',NULL,'Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes',1,'C10yy',NULL,'Other specified diabetes mellitus with other specified complications'),('diabetes',1,'C10yz',NULL,'Diabetes mellitus NOS with other specified manifestation'),('diabetes',1,'C10z.',NULL,'Diabetes mellitus with unspecified complication'),('diabetes',1,'C10z0',NULL,'Diabetes mellitus, juvenile type, with unspecified complication'),('diabetes',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes',1,'C10zy',NULL,'Other specified diabetes mellitus with unspecified complications'),('diabetes',1,'C10zz',NULL,'Diabetes mellitus NOS with unspecified complication'),('diabetes',1,'Cyu20',NULL,'[X]Other specified diabetes mellitus'),('diabetes',1,'Cyu21',NULL,'[X]Malnutrition-related diabetes mellitus with other specified complications'),('diabetes',1,'Cyu22',NULL,'[X]Malnutrition-related diabetes mellitus with unspecified complications'),('diabetes',1,'Cyu23',NULL,'[X]Unspecified diabetes mellitus with renal complications'),('diabetes',1,'L180.',NULL,'Diabetes mellitus during pregnancy, childbirth and the puerperium'),('diabetes',1,'L1800',NULL,'Diabetes mellitus - unspecified whether during pregnancy or the puerperium'),('diabetes',1,'L1801',NULL,'Diabetes mellitus during pregnancy - baby delivered'),('diabetes',1,'L1802',NULL,'Diabetes mellitus in the puerperium - baby delivered during current episode of care'),('diabetes',1,'L1803',NULL,'Diabetes mellitus during pregnancy - baby not yet delivered'),('diabetes',1,'L1804',NULL,'Diabetes mellitus in the puerperium - baby delivered during previous episode of care'),('diabetes',1,'L1805',NULL,'Pre-existing diabetes mellitus, insulin-dependent'),('diabetes',1,'L1806',NULL,'Pre-existing diabetes mellitus, non-insulin-dependent'),('diabetes',1,'L1807',NULL,'Pre-existing malnutrition-related diabetes mellitus'),('diabetes',1,'L1808',NULL,'Diabetes mellitus arising in pregnancy'),('diabetes',1,'L180z',NULL,'Diabetes mellitus during pregnancy, childbirth or the puerperium NOS'),('diabetes',1,'Lyu29',NULL,'[X]Pre-existing diabetes mellitus, unspecified'),('diabetes',1,'Q441.',NULL,'Neonatal diabetes mellitus'),('diabetes',1,'X40J4',NULL,'Insulin-dependent diabetes mellitus'),('diabetes',1,'X40J5',NULL,'Non-insulin-dependent diabetes mellitus'),('diabetes',1,'X40J6',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes',1,'X40J7',NULL,'Malnutrition-related diabetes mellitus'),('diabetes',1,'X40J8',NULL,'Malnutrition-related diabetes mellitus - fibrocalculous'),('diabetes',1,'X40J9',NULL,'Malnutrition-related diabetes mellitus - protein-deficient'),('diabetes',1,'X40JA',NULL,'Secondary diabetes mellitus'),('diabetes',1,'X40JB',NULL,'Secondary pancreatic diabetes mellitus'),('diabetes',1,'X40JC',NULL,'Secondary endocrine diabetes mellitus'),('diabetes',1,'X40JE',NULL,'Reavens syndrome'),('diabetes',1,'X40JF',NULL,'Transitory neonatal diabetes mellitus'),('diabetes',1,'X40JG',NULL,'Genetic syndromes of diabetes mellitus'),('diabetes',1,'X40JI',NULL,'Maturity onset diabetes in youth type 1'),('diabetes',1,'X40JJ',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes',1,'X40JN',NULL,'Lipodystrophy, partial, with Reiger anomaly, short stature, and insulinopenic diabetes mellitus'),('diabetes',1,'X40JQ',NULL,'Muscular atrophy, ataxia, retinitis pigmentosa, and diabetes mellitus'),('diabetes',1,'X40JV',NULL,'Hypogonadism, diabetes mellitus, alopecia ,mental retardation and electrocardiographic abnormalities'),('diabetes',1,'X40JX',NULL,'Pineal hyperplasia, insulin-resistant diabetes mellitus and somatic abnormalities'),('diabetes',1,'X40JY',NULL,'Congenital insulin-dependent diabetes mellitus with fatal secretory diarrhoea'),('diabetes',1,'X40Ja',NULL,'Abnormal metabolic state in diabetes mellitus'),('diabetes',1,'X50GO',NULL,'Soft tissue complication of diabetes mellitus'),('diabetes',1,'XE10E',NULL,'Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes',1,'XE10F',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),
('diabetes',1,'XE10G',NULL,'Diabetes mellitus with renal manifestation'),('diabetes',1,'XE10H',NULL,'Diabetes mellitus with neurological manifestation'),('diabetes',1,'XE10I',NULL,'Diabetes mellitus with peripheral circulatory disorder'),('diabetes',1,'XE12C',NULL,'Insulin dependent diabetes mel'),('diabetes',1,'XE15k',NULL,'Diabetes mellitus with polyneuropathy'),('diabetes',1,'XM19i',NULL,'[EDTA] Diabetes Type I (insulin dependent) associated with renal failure'),('diabetes',1,'XM19j',NULL,'[EDTA] Diabetes Type II (non-insulin-dependent) associated with renal failure'),('diabetes',1,'XM1Qx',NULL,'Diabetes mellitus with gangrene'),('diabetes',1,'XSETH',NULL,'Maturity onset diabetes mellitus in young'),('diabetes',1,'XSETK',NULL,'Drug-induced diabetes mellitus'),('diabetes',1,'XSETp',NULL,'Diabetes mellitus due to insulin receptor antibodies'),('diabetes',1,'Xa08a',NULL,'Small for gestation neonatal diabetes mellitus'),('diabetes',1,'Xa4g7',NULL,'Unstable type 1 diabetes mellitus'),('diabetes',1,'Xa9FG',NULL,'Postpancreatectomy diabetes mellitus'),('diabetes',1,'XaA6b',NULL,'Perceived control of insulin-dependent diabetes'),('diabetes',1,'XaELP',NULL,'Insulin-dependent diabetes without complication'),('diabetes',1,'XaELQ',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes',1,'XaEnn',NULL,'Type I diabetes mellitus with mononeuropathy'),('diabetes',1,'XaEno',NULL,'Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes',1,'XaEnp',NULL,'Type II diabetes mellitus with mononeuropathy'),('diabetes',1,'XaEnq',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes',1,'XaF04',NULL,'Type 1 diabetes mellitus with nephropathy'),('diabetes',1,'XaF05',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes',1,'XaFWG',NULL,'Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'XaFWI',NULL,'Type II diabetes mellitus with hypoglycaemic coma'),('diabetes',1,'XaFm8',NULL,'Type 1 diabetes mellitus with diabetic cataract'),('diabetes',1,'XaFmA',NULL,'Type II diabetes mellitus with diabetic cataract'),('diabetes',1,'XaFmK',NULL,'Type I diabetes mellitus with peripheral angiopathy'),('diabetes',1,'XaFmL',NULL,'Type 1 diabetes mellitus with arthropathy'),('diabetes',1,'XaFmM',NULL,'Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'XaFn7',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes',1,'XaFn8',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes',1,'XaFn9',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes',1,'XaIrf',NULL,'Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes',1,'XaIyz',NULL,'Diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'XaIz0',NULL,'Diabetes mellitus with persistent proteinuria'),('diabetes',1,'XaIzM',NULL,'Type 1 diabetes mellitus with persistent proteinuria'),('diabetes',1,'XaIzN',NULL,'Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'XaIzQ',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes',1,'XaIzR',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes',1,'XaJQp',NULL,'Type II diabetes mellitus with exudative maculopathy'),('diabetes',1,'XaJSr',NULL,'Type I diabetes mellitus with exudative maculopathy'),('diabetes',1,'XaJUI',NULL,'Diabetes mellitus induced by non-steroid drugs'),('diabetes',1,'XaJlL',NULL,'Secondary pancreatic diabetes mellitus without complication'),('diabetes',1,'XaJlM',NULL,'Diabetes mellitus induced by non-steroid drugs without complication'),('diabetes',1,'XaJlQ',NULL,'Lipoatrophic diabetes mellitus without complication'),('diabetes',1,'XaJlR',NULL,'Secondary diabetes mellitus without complication'),('diabetes',1,'XaKyW',NULL,'Type I diabetes mellitus with gastroparesis'),('diabetes',1,'XaKyX',NULL,'Type II diabetes mellitus with gastroparesis'),('diabetes',1,'XaMzI',NULL,'Cystic fibrosis related diabetes mellitus'),('diabetes',1,'XaOPt',NULL,'Maternally inherited diabetes mellitus'),('diabetes',1,'XaOPu',NULL,'Latent autoimmune diabetes mellitus in adult'),('diabetes',1,'XacoB',NULL,'Maturity onset diabetes of the young type 5'),('diabetes',1,'XaIfG',NULL,'Type II diabetes on insulin'),('diabetes',1,'XaIfI',NULL,'Type II diabetes on diet only');
INSERT INTO #codesctv3
VALUES ('hypertension',1,'G24..',NULL,'Secondary hypertension'),('hypertension',1,'G240.',NULL,'Malignant secondary hypertension'),('hypertension',1,'G241.',NULL,'Secondary benign hypertension'),('hypertension',1,'G244.',NULL,'Hypertension secondary to endocrine disorders'),('hypertension',1,'G24z.',NULL,'Secondary hypertension NOS'),('hypertension',1,'Gyu20',NULL,'[X]Other secondary hypertension'),('hypertension',1,'Gyu21',NULL,'[X]Hypertension secondary to other renal disorders'),('hypertension',1,'Xa0kX',NULL,'Hypertension due to renovascular disease'),('hypertension',1,'XE0Ub',NULL,'Systemic arterial hypertension'),('hypertension',1,'G2400',NULL,'Secondary malignant renovascular hypertension'),('hypertension',1,'G240z',NULL,'Secondary malignant hypertension NOS'),('hypertension',1,'G2410',NULL,'Secondary benign renovascular hypertension'),('hypertension',1,'G241z',NULL,'Secondary benign hypertension NOS'),('hypertension',1,'G24z0',NULL,'Secondary renovascular hypertension NOS'),('hypertension',1,'G20..',NULL,'Primary hypertension'),('hypertension',1,'G202.',NULL,'Systolic hypertension'),('hypertension',1,'G20z.',NULL,'Essential hypertension NOS'),('hypertension',1,'XE0Uc',NULL,'Primary hypertension'),('hypertension',1,'XE0W8',NULL,'Hypertension'),('hypertension',1,'XSDSb',NULL,'Diastolic hypertension'),('hypertension',1,'Xa0Cs',NULL,'Labile hypertension'),('hypertension',1,'Xa3fQ',NULL,'Malignant hypertension'),('hypertension',1,'XaZWm',NULL,'Stage 1 hypertension'),('hypertension',1,'XaZWn',NULL,'Severe hypertension'),('hypertension',1,'XaZbz',NULL,'Stage 2 hypertension (NICE - National Institute for Health and Clinical Excellence 2011)'),('hypertension',1,'XaZzo',NULL,'Nocturnal hypertension'),('hypertension',1,'G2...',NULL,'Hypertensive disease'),('hypertension',1,'G200.',NULL,'Malignant essential hypertension'),('hypertension',1,'G201.',NULL,'Benign essential hypertension'),('hypertension',1,'XE0Ud',NULL,'Essential hypertension NOS'),('hypertension',1,'Xa41E',NULL,'Maternal hypertension'),('hypertension',1,'Xab9L',NULL,'Stage 1 hypertension (NICE 2011) without evidence of end organ damage'),('hypertension',1,'Xab9M',NULL,'Stage 1 hypertension (NICE 2011) with evidence of end organ damage'),('hypertension',1,'G2y..',NULL,'Other specified hypertensive disease'),('hypertension',1,'G2z..',NULL,'Hypertensive disease NOS'),('hypertension',1,'Gyu2.',NULL,'[X]Hypertensive diseases'),('hypertension',1,'XM19D',NULL,'[EDTA] Renal vascular disease due to hypertension (no primary renal disease) associated with renal failure'),('hypertension',1,'XM19E',NULL,'[EDTA] Renal vascular disease due to malignant hypertension (no primary renal disease) associated with renal failure');
INSERT INTO #codesctv3
VALUES ('covid-positive-antigen-test',1,'Y269d',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) antigen detection result positive'),('covid-positive-antigen-test',1,'43kB1',NULL,'SARS-CoV-2 antigen positive');
INSERT INTO #codesctv3
VALUES ('covid-positive-pcr-test',1,'4J3R6',NULL,'SARS-CoV-2 RNA pos lim detect'),('covid-positive-pcr-test',1,'Y240b',NULL,'Severe acute respiratory syndrome coronavirus 2 qualitative existence in specimen (observable entity)'),('covid-positive-pcr-test',1,'Y2a3b',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive'),('covid-positive-pcr-test',1,'A7952',NULL,'COVID-19 confirmed by laboratory test'),('covid-positive-pcr-test',1,'Y228d',NULL,'Coronavirus disease 19 caused by severe acute respiratory syndrome coronavirus 2 confirmed by laboratory test (situation)'),('covid-positive-pcr-test',1,'Y210e',NULL,'Detection of 2019-nCoV (novel coronavirus) using polymerase chain reaction technique'),('covid-positive-pcr-test',1,'43hF.',NULL,'Detection of SARS-CoV-2 by PCR'),('covid-positive-pcr-test',1,'Y2a3d',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive at the limit of detection');
INSERT INTO #codesctv3
VALUES ('covid-positive-test-other',1,'4J3R1',NULL,'2019-nCoV (novel coronavirus) detected'),('covid-positive-test-other',1,'Y20d1',NULL,'Confirmed 2019-nCov (Wuhan) infection'),('covid-positive-test-other',1,'Y23f7',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detection result positive');
INSERT INTO #codesctv3
VALUES ('egfr',1,'X70kK',NULL,'Tc99m-DTPA clearance - GFR'),('egfr',1,'X70kL',NULL,'Cr51- EDTA clearance - GFR'),('egfr',1,'X90kf',NULL,'With GFR'),('egfr',1,'XaK8y',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'XaMDA',NULL,'Glomerular filtration rate calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin'),('egfr',1,'XaZpN',NULL,'Estimated glomerular filtration rate using Chronic Kidney Disease Epidemiology Collaboration formula per 1.73 square metres'),('egfr',1,'XacUJ',NULL,'Estimated glomerular filtration rate using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'XacUK',NULL,'Estimated glomerular filtration rate using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres');
INSERT INTO #codesctv3
VALUES ('urinary-albumin-creatinine-ratio',1,'46TC.',NULL,'Urine albumin:creatinine ratio'),('urinary-albumin-creatinine-ratio',1,'XE2n3',NULL,'Urine albumin:creatinine ratio')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesctv3;

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codessnomed
VALUES ('egfr',1,'1011481000000105',NULL,'eGFR (estimated glomerular filtration rate) using creatinine Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'1011491000000107',NULL,'eGFR (estimated glomerular filtration rate) using cystatin C Chronic Kidney Disease Epidemiology Collaboration equation per 1.73 square metres'),('egfr',1,'1020291000000106',NULL,'GFR (glomerular filtration rate) calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation'),('egfr',1,'1107411000000104',NULL,'eGFR (estimated glomerular filtration rate) by laboratory calculation'),('egfr',1,'241373003',NULL,'Technetium-99m-diethylenetriamine pentaacetic acid clearance - glomerular filtration rate (procedure)'),('egfr',1,'262300005',NULL,'With glomerular filtration rate'),('egfr',1,'737105002',NULL,'GFR (glomerular filtration rate) calculation technique'),('egfr',1,'80274001',NULL,'Glomerular filtration rate (observable entity)'),('egfr',1,'996231000000108',NULL,'GFR (glomerular filtration rate) calculated by abbreviated Modification of Diet in Renal Disease Study Group calculation adjusted for African American origin');
INSERT INTO #codessnomed
VALUES ('urinary-albumin-creatinine-ratio',1,'271075006',NULL,'Urine albumin/creatinine ratio measurement')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codessnomed;

IF OBJECT_ID('tempdb..#codesemis') IS NOT NULL DROP TABLE #codesemis;
CREATE TABLE #codesemis (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesemis
VALUES ('diabetes',1,'^ESCTGE801661',NULL,'Gestational diabetes, delivered'),('diabetes',1,'^ESCTGE801662',NULL,'Gestational diabetes mellitus complicating pregnancy'),('diabetes',1,'^ESCTMA257526',NULL,'Maternal diabetes mellitus with hypoglycaemia affecting foetus OR newborn'),('diabetes',1,'EMISQNU2',NULL,'Number of admissions for ketoacidosis'),('diabetes',1,'ESCTDI20',NULL,'Diabetic ketoacidosis without coma'),('diabetes',1,'ESCTDI22',NULL,'Diabetic severe hyperglycaemia'),('diabetes',1,'ESCTDI23',NULL,'Diabetic hyperosmolar non-ketotic state'),('diabetes',1,'ESCTDR3',NULL,'Drug-induced diabetes mellitus'),('diabetes',1,'ESCTSE11',NULL,'Secondary endocrine diabetes mellitus');
INSERT INTO #codesemis
VALUES ('hypertension',1,'EMISNQST25',NULL,'Stage 2 hypertension'),('hypertension',1,'^ESCTMA364280',NULL,'Malignant hypertension'),('hypertension',1,'EMISNQST25',NULL,'Stage 2 hypertension');
INSERT INTO #codesemis
VALUES ('covid-positive-antigen-test',1,'^ESCT1305304',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) antigen detection result positive'),('covid-positive-antigen-test',1,'^ESCT1348538',NULL,'Detection of SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) antigen');
INSERT INTO #codesemis
VALUES ('covid-positive-pcr-test',1,'^ESCT1305238',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) qualitative existence in specimen'),('covid-positive-pcr-test',1,'^ESCT1348314',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive'),('covid-positive-pcr-test',1,'^ESCT1305235',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive'),('covid-positive-pcr-test',1,'^ESCT1300228',NULL,'COVID-19 confirmed by laboratory test GP COVID-19'),('covid-positive-pcr-test',1,'^ESCT1348316',NULL,'2019-nCoV (novel coronavirus) ribonucleic acid detected'),('covid-positive-pcr-test',1,'^ESCT1301223',NULL,'Detection of SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) using polymerase chain reaction technique'),('covid-positive-pcr-test',1,'^ESCT1348359',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive at the limit of detection'),('covid-positive-pcr-test',1,'^ESCT1299053',NULL,'Detection of 2019-nCoV (novel coronavirus) using polymerase chain reaction technique'),('covid-positive-pcr-test',1,'^ESCT1300228',NULL,'COVID-19 confirmed by laboratory test'),('covid-positive-pcr-test',1,'^ESCT1348359',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive at the limit of detection');
INSERT INTO #codesemis
VALUES ('covid-positive-test-other',1,'^ESCT1303928',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detection result positive'),('covid-positive-test-other',1,'^ESCT1299074',NULL,'2019-nCoV (novel coronavirus) detected'),('covid-positive-test-other',1,'^ESCT1301230',NULL,'SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detected'),('covid-positive-test-other',1,'EMISNQCO303',NULL,'Confirmed 2019-nCoV (Wuhan) infectio'),('covid-positive-test-other',1,'^ESCT1299075',NULL,'Wuhan 2019-nCoV (novel coronavirus) detected'),('covid-positive-test-other',1,'^ESCT1300229',NULL,'COVID-19 confirmed using clinical diagnostic criteria'),('covid-positive-test-other',1,'^ESCT1348575',NULL,'Detection of SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2)'),('covid-positive-test-other',1,'^ESCT1299074',NULL,'2019-nCoV (novel coronavirus) detected'),('covid-positive-test-other',1,'^ESCT1300229',NULL,'COVID-19 confirmed using clinical diagnostic criteria'),('covid-positive-test-other',1,'EMISNQCO303',NULL,'Confirmed 2019-nCoV (novel coronavirus) infection'),('covid-positive-test-other',1,'EMISNQCO303',NULL,'Confirmed 2019-nCoV (novel coronavirus) infection'),('covid-positive-test-other',1,'^ESCT1348575',NULL,'Detection of SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2)')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesemis;


IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, version INT NOT NULL, [description] VARCHAR(255));

-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.concept, dcr.[version], dcr.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
AND (dcr.term IS NULL OR dcr.term = rc.Term)
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.concept, dcc.[version], dcc.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

-- EMIS codes with a FK Reference Coding ID
INSERT INTO #TempRefCodes
SELECT FK_Reference_Coding_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [version] INT NOT NULL, [description] VARCHAR(255));

-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.concept, dcs.[version], dcs.[description]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- EMIS codes with a FK SNOMED ID but without a FK Reference Coding ID
INSERT INTO #TempSNOMEDRefCodes
SELECT FK_Reference_SnomedCT_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID = -1
AND FK_Reference_SnomedCT_ID != -1;

-- De-duped tables
IF OBJECT_ID('tempdb..#CodeSets') IS NOT NULL DROP TABLE #CodeSets;
CREATE TABLE #CodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#SnomedSets') IS NOT NULL DROP TABLE #SnomedSets;
CREATE TABLE #SnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedCodeSets') IS NOT NULL DROP TABLE #VersionedCodeSets;
CREATE TABLE #VersionedCodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedSnomedSets') IS NOT NULL DROP TABLE #VersionedSnomedSets;
CREATE TABLE #VersionedSnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

INSERT INTO #VersionedCodeSets
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #VersionedSnomedSets
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

INSERT INTO #CodeSets
SELECT FK_Reference_Coding_ID, c.concept, [description]
FROM #VersionedCodeSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedCodeSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

INSERT INTO #SnomedSets
SELECT FK_Reference_SnomedCT_ID, c.concept, [description]
FROM #VersionedSnomedSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedSnomedSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

-- >>> Following code sets injected: hypertension v1/diabetes v1

-- LOAD CODESETS FOR TESTS USED TO INDICATE CKD

-- >>> Following code sets injected: egfr v1/urinary-albumin-creatinine-ratio v1


---- FIND PATIENTS WITH BIOCHEMICAL EVIDENCE OF CKD

---- find all eGFR and ACR tests

IF OBJECT_ID('tempdb..#EGFR_ACR_TESTS') IS NOT NULL DROP TABLE #EGFR_ACR_TESTS;
SELECT gp.FK_Patient_Link_ID, 
	CAST(GP.EventDate AS DATE) AS EventDate, 
	SuppliedCode, 
	[value] = TRY_CONVERT(NUMERIC (18,5), [Value]),  
	[Units],
	egfr_Code = CASE WHEN SuppliedCode IN (
		SELECT [Code] FROM #AllCodes WHERE [Concept] IN ('egfr') AND [Version] = 1 ) THEN 1 ELSE 0 END,
	acr_Code = CASE WHEN SuppliedCode IN (
		SELECT [Code] FROM #AllCodes WHERE [Concept] IN ('urinary-albumin-creatinine-ratio') AND [Version] = 1 ) THEN 1 ELSE 0 END
INTO #EGFR_ACR_TESTS
FROM [RLS].[vw_GP_Events] gp
WHERE (
		gp.FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept IN ('egfr', 'urinary-albumin-creatinine-ratio')  AND [Version]=1) OR
		gp.FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept IN ('egfr', 'urinary-albumin-creatinine-ratio')  AND [Version]=1)
	  )
	AND gp.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
	AND (gp.EventDate) BETWEEN '2016-01-01' and @EndDate
	AND [Value] IS NOT NULL AND UPPER([Value]) NOT LIKE '%[A-Z]%' 

-- CREATE TABLE OF EGFR TESTS THAT MEET CKD CRITERIA (VARIOUS STAGEs)

IF OBJECT_ID('tempdb..#ckd_stages_egfr') IS NOT NULL DROP TABLE #ckd_stages_egfr;
SELECT FK_Patient_Link_ID,
	EventDate,
	egfr_evidence = CASE WHEN egfr_Code = 1 AND [Value] >= 90   THEN 'G1' 
		WHEN egfr_Code = 1 AND [Value] BETWEEN 60 AND 89 		THEN 'G2'
		WHEN egfr_Code = 1 AND [Value] BETWEEN 45 AND 59 		THEN 'G3a'
		WHEN egfr_Code = 1 AND [Value] BETWEEN 30 AND 44 		THEN 'G3b'
		WHEN egfr_Code = 1 AND [Value] BETWEEN 15 AND 29 		THEN 'G4'
		WHEN egfr_Code = 1 AND [Value] BETWEEN  0 AND 15 		THEN 'G5'
			ELSE NULL END
INTO #ckd_stages_egfr
FROM #EGFR_ACR_TESTS

-- FIND EGFR TESTS INDICATIVE OF CKD STAGE 3-5, WITH THE DATES OF THE PREVIOUS TEST

IF OBJECT_ID('tempdb..#egfr_dates') IS NOT NULL DROP TABLE #egfr_dates;
SELECT *, 
	stage_previous_egfr = LAG(egfr_evidence, 1, NULL) OVER (PARTITION BY FK_Patient_Link_ID ORDER BY EventDate),
	date_previous_egfr = LAG(EventDate, 1, NULL) OVER (PARTITION BY FK_Patient_Link_ID ORDER BY EventDate)
INTO #egfr_dates
FROM #ckd_stages_egfr
where egfr_evidence in ('G3a', 'G3b', 'G4', 'G5')
ORDER BY FK_Patient_Link_ID, EventDate

-- CREATE TABLE OF PATIENTS THAT HAD TWO EGFR TESTS INDICATIVE OF CKD STAGE 3-5, WITHIN 3 MONTHS OF EACH OTHER

IF OBJECT_ID('tempdb..#egfr_ckd_evidence') IS NOT NULL DROP TABLE #egfr_ckd_evidence;
SELECT *
INTO #egfr_ckd_evidence
FROM #egfr_dates
WHERE datediff(month, date_previous_egfr, EventDate) <=  3 --only find patients with two tests in three months

-- FIND PATIENTS THAT MEET THE FOLLOWING: "ACR > 3mg/mmol lasting for at least 3 months”

-- CREATE TABLE OF ACR TESTS

IF OBJECT_ID('tempdb..#ckd_stages_acr') IS NOT NULL DROP TABLE #ckd_stages_acr;
SELECT FK_Patient_Link_ID,
	EventDate, 
	acr_evidence = CASE WHEN acr_Code = 1 AND [Value] > 30  	THEN 'A3' 
		WHEN acr_Code = 1 AND [Value] BETWEEN 3 AND 30 			THEN 'A2'
		WHEN acr_Code = 1 AND [Value] BETWEEN  0 AND 3 			THEN 'A1'
			ELSE NULL END 
INTO #ckd_stages_acr
FROM #EGFR_ACR_TESTS

-- FIND TESTS THAT ARE >3mg/mmol AND SHOW DATE OF PREVIOUS TEST

IF OBJECT_ID('tempdb..#acr_dates') IS NOT NULL DROP TABLE #acr_dates;
SELECT *, 
	stage_previous_acr = LAG(acr_evidence, 1, NULL) OVER (PARTITION BY FK_Patient_Link_ID ORDER BY EventDate),
	date_previous_acr = LAG(EventDate, 1, NULL) OVER (PARTITION BY FK_Patient_Link_ID ORDER BY EventDate)
INTO #acr_dates
FROM #ckd_stages_acr
WHERE acr_evidence in ('A3','A2')
ORDER BY FK_Patient_Link_ID, EventDate

IF OBJECT_ID('tempdb..#acr_ckd_evidence') IS NOT NULL DROP TABLE #acr_ckd_evidence;
SELECT *
INTO #acr_ckd_evidence
FROM #acr_dates
WHERE datediff(month, date_previous_acr, EventDate) >=  3 --only find patients with acr stages A1/A2 lasting at least 3 months


-- CREATE TABLE OF PATIENTS AT RISK OF CKD: DIABETES OR HYPERTENSION

-- IF OBJECT_ID('tempdb..#ckd_risk') IS NOT NULL DROP TABLE #ckd_risk;
-- SELECT DISTINCT FK_Patient_Link_ID
-- INTO #ckd_risk
-- FROM [RLS].[vw_GP_Events] gp
-- LEFT OUTER JOIN #VersionedSnomedSets s ON s.FK_Reference_SnomedCT_ID = gp.FK_Reference_SnomedCT_ID
-- LEFT OUTER JOIN #VersionedCodeSets c ON c.FK_Reference_Coding_ID = gp.FK_Reference_Coding_ID
-- WHERE  gp.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
-- AND (
-- 	gp.FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept IN ('diabetes', 'hypertension') AND [Version]=1) OR
--     gp.FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept IN ('diabetes', 'hypertension') AND [Version]=1)
-- 	);

-- CREATE TABLE ONLY INCLUDING THE REQUIRED COHORT, WHICH INCLUDES THOSE WITH EVIDENCE OF CKD AND THOSE AT RISK OF CKD

IF OBJECT_ID('tempdb..#Cohort') IS NOT NULL DROP TABLE #Cohort;
SELECT p.FK_Patient_Link_ID,
		p.EthnicMainGroup,
		p.DeathDate,
		EvidenceOfCKD_egfr = CASE WHEN p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #egfr_ckd_evidence) THEN 1 ELSE 0 END,
		EvidenceOfCKD_acr = CASE WHEN p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #acr_ckd_evidence) THEN 1 ELSE 0 END
		--,AtRiskOfCKD = CASE WHEN p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #ckd_risk) THEN 1 ELSE 0 END
INTO #Cohort
FROM #Patients p
WHERE p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #egfr_ckd_evidence) 
	OR p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #acr_ckd_evidence) 
	--OR p.FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #ckd_risk) 

---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

-- REDUCE THE #Patients TABLE SO THAT IT ONLY INCLUDES THE COHORT, AND REUSABLE QUERIES CAN USE IT TO BE RUN QUICKER 

DELETE FROM #Patients
WHERE FK_Patient_Link_ID NOT IN (SELECT FK_Patient_Link_ID FROM #Cohort)

--┌─────────────────────┐
--│ Patients with COVID │
--└─────────────────────┘

-- OBJECTIVE: To get tables of all patients with a COVID diagnosis in their record. This now includes a table
-- that has reinfections. This uses a 90 day cut-off to rule out patients that get multiple tests for
-- a single infection. This 90 day cut-off is also used in the government COVID dashboard. In the first wave,
-- prior to widespread COVID testing, and prior to the correct clinical codes being	available to clinicians,
-- infections were recorded in a variety of ways. We therefore take the first diagnosis from any code indicative
-- of COVID. However, for subsequent infections we insist on the presence of a positive COVID test (PCR or antigen)
-- as opposed to simply a diagnosis code. This is to avoid the situation where a hospital diagnosis code gets 
-- entered into the primary care record several months after the actual infection.

-- INPUT: Takes three parameters
--  - start-date: string - (YYYY-MM-DD) the date to count diagnoses from. Usually this should be 2020-01-01.
--	-	all-patients: boolean - (true/false) if true, then all patients are included, otherwise only those in the pre-existing #Patients table.
--	- gp-events-table: string - (table name) the name of the table containing the GP events. Usually is "RLS.vw_GP_Events" but can be anything with the columns: FK_Patient_Link_ID, EventDate, and SuppliedCode

-- OUTPUT: Three temp tables as follows:
-- #CovidPatients (FK_Patient_Link_ID, FirstCovidPositiveDate)
-- 	- FK_Patient_Link_ID - unique patient id
--	- FirstCovidPositiveDate - earliest COVID diagnosis
-- #CovidPatientsAllDiagnoses (FK_Patient_Link_ID, CovidPositiveDate)
-- 	- FK_Patient_Link_ID - unique patient id
--	- CovidPositiveDate - any COVID diagnosis
-- #CovidPatientsMultipleDiagnoses
--	-	FK_Patient_Link_ID - unique patient id
--	-	FirstCovidPositiveDate - date of first COVID diagnosis
--	-	SecondCovidPositiveDate - date of second COVID diagnosis
--	-	ThirdCovidPositiveDate - date of third COVID diagnosis
--	-	FourthCovidPositiveDate - date of fourth COVID diagnosis
--	-	FifthCovidPositiveDate - date of fifth COVID diagnosis

-- >>> Following code sets injected: covid-positive-antigen-test v1/covid-positive-pcr-test v1/covid-positive-test-other v1

IF OBJECT_ID('tempdb..#CovidPatientsAllDiagnoses') IS NOT NULL DROP TABLE #CovidPatientsAllDiagnoses;
CREATE TABLE #CovidPatientsAllDiagnoses (
	FK_Patient_Link_ID BIGINT,
	CovidPositiveDate DATE
);
BEGIN
	IF 'false'='true'
		INSERT INTO #CovidPatientsAllDiagnoses
		SELECT DISTINCT FK_Patient_Link_ID, CONVERT(DATE, [EventDate]) AS CovidPositiveDate
		FROM [RLS].[vw_COVID19]
		WHERE (
			(GroupDescription = 'Confirmed' AND SubGroupDescription != 'Negative') OR
			(GroupDescription = 'Tested' AND SubGroupDescription = 'Positive')
		)
		AND EventDate > '2020-01-01'
		AND EventDate <= GETDATE();
	ELSE 
		INSERT INTO #CovidPatientsAllDiagnoses
		SELECT DISTINCT FK_Patient_Link_ID, CONVERT(DATE, [EventDate]) AS CovidPositiveDate
		FROM [RLS].[vw_COVID19]
		WHERE (
			(GroupDescription = 'Confirmed' AND SubGroupDescription != 'Negative') OR
			(GroupDescription = 'Tested' AND SubGroupDescription = 'Positive')
		)
		AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
		AND EventDate > '2020-01-01'
		AND EventDate <= GETDATE();
END

-- We can rely on the GraphNet table for first diagnosis.
IF OBJECT_ID('tempdb..#CovidPatients') IS NOT NULL DROP TABLE #CovidPatients;
SELECT FK_Patient_Link_ID, MIN(CovidPositiveDate) AS FirstCovidPositiveDate INTO #CovidPatients
FROM #CovidPatientsAllDiagnoses
GROUP BY FK_Patient_Link_ID;

-- Now let's get the dates of any positive test (i.e. not things like suspected, or historic)
IF OBJECT_ID('tempdb..#AllPositiveTestsTemp') IS NOT NULL DROP TABLE #AllPositiveTestsTemp;
CREATE TABLE #AllPositiveTestsTemp (
	FK_Patient_Link_ID BIGINT,
	TestDate DATE
);
BEGIN
	IF 'false'='true'
		INSERT INTO #AllPositiveTestsTemp
		SELECT DISTINCT FK_Patient_Link_ID, CAST(EventDate AS DATE) AS TestDate
		FROM RLS.vw_GP_Events
		WHERE SuppliedCode IN (
			select Code from #AllCodes 
			where Concept in ('covid-positive-antigen-test','covid-positive-pcr-test','covid-positive-test-other') 
			AND Version = 1
		);
	ELSE 
		INSERT INTO #AllPositiveTestsTemp
		SELECT DISTINCT FK_Patient_Link_ID, CAST(EventDate AS DATE) AS TestDate
		FROM RLS.vw_GP_Events
		WHERE SuppliedCode IN (
			select Code from #AllCodes 
			where Concept in ('covid-positive-antigen-test','covid-positive-pcr-test','covid-positive-test-other') 
			AND Version = 1
		)
		AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients);
END

IF OBJECT_ID('tempdb..#CovidPatientsMultipleDiagnoses') IS NOT NULL DROP TABLE #CovidPatientsMultipleDiagnoses;
CREATE TABLE #CovidPatientsMultipleDiagnoses (
	FK_Patient_Link_ID BIGINT,
	FirstCovidPositiveDate DATE,
	SecondCovidPositiveDate DATE,
	ThirdCovidPositiveDate DATE,
	FourthCovidPositiveDate DATE,
	FifthCovidPositiveDate DATE
);

-- Populate first diagnosis
INSERT INTO #CovidPatientsMultipleDiagnoses (FK_Patient_Link_ID, FirstCovidPositiveDate)
SELECT FK_Patient_Link_ID, MIN(FirstCovidPositiveDate) FROM
(
	SELECT * FROM #CovidPatients
	UNION
	SELECT * FROM #AllPositiveTestsTemp
) sub
GROUP BY FK_Patient_Link_ID;

-- Now let's get second tests.
UPDATE t1
SET t1.SecondCovidPositiveDate = NextTestDate
FROM #CovidPatientsMultipleDiagnoses AS t1
INNER JOIN (
SELECT cp.FK_Patient_Link_ID, MIN(apt.TestDate) AS NextTestDate FROM #CovidPatients cp
INNER JOIN #AllPositiveTestsTemp apt ON cp.FK_Patient_Link_ID = apt.FK_Patient_Link_ID AND apt.TestDate >= DATEADD(day, 90, FirstCovidPositiveDate)
GROUP BY cp.FK_Patient_Link_ID) AS sub ON sub.FK_Patient_Link_ID = t1.FK_Patient_Link_ID;

-- Now let's get third tests.
UPDATE t1
SET t1.ThirdCovidPositiveDate = NextTestDate
FROM #CovidPatientsMultipleDiagnoses AS t1
INNER JOIN (
SELECT cp.FK_Patient_Link_ID, MIN(apt.TestDate) AS NextTestDate FROM #CovidPatientsMultipleDiagnoses cp
INNER JOIN #AllPositiveTestsTemp apt ON cp.FK_Patient_Link_ID = apt.FK_Patient_Link_ID AND apt.TestDate >= DATEADD(day, 90, SecondCovidPositiveDate)
GROUP BY cp.FK_Patient_Link_ID) AS sub ON sub.FK_Patient_Link_ID = t1.FK_Patient_Link_ID;

-- Now let's get fourth tests.
UPDATE t1
SET t1.FourthCovidPositiveDate = NextTestDate
FROM #CovidPatientsMultipleDiagnoses AS t1
INNER JOIN (
SELECT cp.FK_Patient_Link_ID, MIN(apt.TestDate) AS NextTestDate FROM #CovidPatientsMultipleDiagnoses cp
INNER JOIN #AllPositiveTestsTemp apt ON cp.FK_Patient_Link_ID = apt.FK_Patient_Link_ID AND apt.TestDate >= DATEADD(day, 90, ThirdCovidPositiveDate)
GROUP BY cp.FK_Patient_Link_ID) AS sub ON sub.FK_Patient_Link_ID = t1.FK_Patient_Link_ID;

-- Now let's get fifth tests.
UPDATE t1
SET t1.FifthCovidPositiveDate = NextTestDate
FROM #CovidPatientsMultipleDiagnoses AS t1
INNER JOIN (
SELECT cp.FK_Patient_Link_ID, MIN(apt.TestDate) AS NextTestDate FROM #CovidPatientsMultipleDiagnoses cp
INNER JOIN #AllPositiveTestsTemp apt ON cp.FK_Patient_Link_ID = apt.FK_Patient_Link_ID AND apt.TestDate >= DATEADD(day, 90, FourthCovidPositiveDate)
GROUP BY cp.FK_Patient_Link_ID) AS sub ON sub.FK_Patient_Link_ID = t1.FK_Patient_Link_ID;

--bring together for final output
SELECT 
	PatientId = FK_Patient_Link_ID,
	FirstCovidPositiveDate,
	SecondCovidPositiveDate, 
	ThirdCovidPositiveDate, 
	FourthCovidPositiveDate, 
	FifthCovidPositiveDate
FROM #CovidPatientsMultipleDiagnoses cv



