--┌──────────────────────┐
--│ Patient demographics │
--└──────────────────────┘

TODO CKD code set

-- OUTPUT: Data with the following fields
--  - PatientID
--  - Practice (P27001/P27001/etc..)
--  - 2019IMDDecile1IsMostDeprived10IsLeastDeprived (integer 1-10)
--  - QuarterOfBirth (YYYY-MM-DD)
--  - YearMonthOfT2DDiagnosis (earliest diagnosis date - YYYY-MM)
--  - Sex (M/F)
--  - Height (most recent)
--  - Ethnicity (suppressed grouping is sufficient)
--  - YearMonthFirstSGLT2i prescription
--  - YearMonthFirstACE-I prescription
--  - YearMonthFirstARB prescription
--  - YearMonthCKDstage 3-5 diagnosis (earliest diagnosis date)
--  - YearMonthHFdiagnosis (earliest diagnosis date)
--  - YearMonthCVDdiagnosis (earliest diagnosis date)
--  - YearMonthCancerdiagnosis (earliest diagnosis date)
--  - YearMonthDeath
--  - YearMonthRegistrationwith a GM primary care practice (only to be provided if not registered at index date)
--  - YearMonthDeregistration from GM primary care practice (only to be provided if not registered at extract date)


--Just want the output, not the messages
SET NOCOUNT ON;


--┌───────────────────────────────────────────────────────────────────┐
--│ Define Cohort for Gendius project: patients with T2D but no CKD   │
--└───────────────────────────────────────────────────────────────────┘

-- OBJECTIVE: To build the cohort of patients needed for the Gendius
--						project. This reduces duplication of code in the template 
--						scripts.

-- COHORT: Index date: 2.5 years prior to extract. Adults who have a
--					type 2 diabetes diagnosis before the date of extraction, 
-- 					were registered with a GP in GM between the index and
--					extraction date, at the index date:	are alive,and do not
--					have a diagnosis of CKD stage 3-5.

-- INPUT: A single variable:
--  - index-date: date - (YYYY-MM-DD) the date of the extract

-- OUTPUT: TODO A temp table as follows:
-- #Cohort (FK_Patient_Link_ID)
-- #PatientEventData

-- Table of all patients (not necessarily with a GP record yet)
IF OBJECT_ID('tempdb..#Patients') IS NOT NULL DROP TABLE #Patients;
SELECT DISTINCT FK_Patient_Link_ID
INTO #Patients
FROM SharedCare.Patient
WHERE FK_Reference_Tenancy_ID=2;

-- Get first T2D diagnosis date

-- >>> Codesets required... Inserting the code set code
--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘

-- OBJECTIVE: To populate temporary tables with the existing clinical code sets.
--            See the [SQL-generation-process.md](SQL-generation-process.md) for more details.

-- INPUT: No pre-requisites

-- OUTPUT: Five temp tables as follows:
--  #AllCodes (Concept, Version, Code)
--  #CodeSets (FK_Reference_Coding_ID, Concept)
--  #SnomedSets (FK_Reference_SnomedCT_ID, FK_SNOMED_ID)
--  #VersionedCodeSets (FK_Reference_Coding_ID, Concept, Version)
--  #VersionedSnomedSets (FK_Reference_SnomedCT_ID, Version, FK_SNOMED_ID)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

--#region Clinical code sets

IF OBJECT_ID('tempdb..#AllCodes') IS NOT NULL DROP TABLE #AllCodes;
CREATE TABLE #AllCodes (
  [Concept] [varchar](255) NOT NULL,
  [Version] INT NOT NULL,
  [Code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
  [description] [varchar] (255) NULL 
);

IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('chronic-kidney-disease',1,'1Z1f.',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1f.00',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1e.',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1e.00',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1d.',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1d.00',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1c.',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1c.00',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1b.',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1b.00',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1a.',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1a.00',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1Z.',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1Z.00',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1Y.',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1Y.00',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1X.',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1X.00',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1W.',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1W.00',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1V.',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1V.00',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1T.',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1T.00',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1S.',NULL,'CKD G2A3 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1S.00',NULL,'CKD G2A3 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1R.',NULL,'CKD G2A2 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1R.00',NULL,'CKD G2A2 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1Q.',NULL,'CKD G2A1 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1Q.00',NULL,'CKD G2A1 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1P.',NULL,'CKD G1A3 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1P.00',NULL,'CKD G1A3 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A3'),('chronic-kidney-disease',1,'1Z1N.',NULL,'CKD G1A2 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1N.00',NULL,'CKD G1A2 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A2'),('chronic-kidney-disease',1,'1Z1M.',NULL,'CKD G1A1 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z1M.00',NULL,'CKD G1A1 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A1'),('chronic-kidney-disease',1,'1Z16.',NULL,'Chronic kidney disease stage 3B'),('chronic-kidney-disease',1,'1Z16.00',NULL,'Chronic kidney disease stage 3B'),('chronic-kidney-disease',1,'1Z15.',NULL,'Chronic kidney disease stage 3A'),('chronic-kidney-disease',1,'1Z15.00',NULL,'Chronic kidney disease stage 3A'),('chronic-kidney-disease',1,'1Z14.',NULL,'Chronic kidney disease stage 5'),('chronic-kidney-disease',1,'1Z14.00',NULL,'Chronic kidney disease stage 5'),('chronic-kidney-disease',1,'1Z13.',NULL,'Chronic kidney disease stage 4'),('chronic-kidney-disease',1,'1Z13.00',NULL,'Chronic kidney disease stage 4'),('chronic-kidney-disease',1,'1Z12.',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'1Z12.00',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'1Z11.',NULL,'Chronic kidney disease stage 2'),('chronic-kidney-disease',1,'1Z11.00',NULL,'Chronic kidney disease stage 2'),('chronic-kidney-disease',1,'1Z10.',NULL,'Chronic kidney disease stage 1'),('chronic-kidney-disease',1,'1Z10.00',NULL,'Chronic kidney disease stage 1'),('chronic-kidney-disease',1,'1Z1L.',NULL,'Chronic kidney disease stage 5 without proteinuria'),('chronic-kidney-disease',1,'1Z1L.00',NULL,'Chronic kidney disease stage 5 without proteinuria'),('chronic-kidney-disease',1,'1Z1K.',NULL,'Chronic kidney disease stage 5 with proteinuria'),('chronic-kidney-disease',1,'1Z1K.00',NULL,'Chronic kidney disease stage 5 with proteinuria'),('chronic-kidney-disease',1,'1Z1J.',NULL,'Chronic kidney disease stage 4 without proteinuria'),('chronic-kidney-disease',1,'1Z1J.00',NULL,'Chronic kidney disease stage 4 without proteinuria'),('chronic-kidney-disease',1,'1Z1H.',NULL,'Chronic kidney disease stage 4 with proteinuria'),('chronic-kidney-disease',1,'1Z1H.00',NULL,'Chronic kidney disease stage 4 with proteinuria'),('chronic-kidney-disease',1,'1Z1G.',NULL,'Chronic kidney disease stage 3B without proteinuria'),('chronic-kidney-disease',1,'1Z1G.00',NULL,'Chronic kidney disease stage 3B without proteinuria'),('chronic-kidney-disease',1,'1Z1F.',NULL,'Chronic kidney disease stage 3B with proteinuria'),('chronic-kidney-disease',1,'1Z1F.00',NULL,'Chronic kidney disease stage 3B with proteinuria'),('chronic-kidney-disease',1,'1Z1E.',NULL,'Chronic kidney disease stage 3A without proteinuria'),('chronic-kidney-disease',1,'1Z1E.00',NULL,'Chronic kidney disease stage 3A without proteinuria'),('chronic-kidney-disease',1,'1Z1D.',NULL,'Chronic kidney disease stage 3A with proteinuria'),('chronic-kidney-disease',1,'1Z1D.00',NULL,'Chronic kidney disease stage 3A with proteinuria'),('chronic-kidney-disease',1,'1Z1C.',NULL,'Chronic kidney disease stage 3 without proteinuria'),('chronic-kidney-disease',1,'1Z1C.00',NULL,'Chronic kidney disease stage 3 without proteinuria'),('chronic-kidney-disease',1,'1Z1B.',NULL,'Chronic kidney disease stage 3 with proteinuria'),('chronic-kidney-disease',1,'1Z1B.00',NULL,'Chronic kidney disease stage 3 with proteinuria'),('chronic-kidney-disease',1,'1Z1A.',NULL,'Chronic kidney disease stage 2 without proteinuria'),('chronic-kidney-disease',1,'1Z1A.00',NULL,'Chronic kidney disease stage 2 without proteinuria'),('chronic-kidney-disease',1,'1Z19.',NULL,'Chronic kidney disease stage 2 with proteinuria'),('chronic-kidney-disease',1,'1Z19.00',NULL,'Chronic kidney disease stage 2 with proteinuria'),('chronic-kidney-disease',1,'1Z18.',NULL,'Chronic kidney disease stage 1 without proteinuria'),('chronic-kidney-disease',1,'1Z18.00',NULL,'Chronic kidney disease stage 1 without proteinuria'),('chronic-kidney-disease',1,'1Z17.',NULL,'Chronic kidney disease stage 1 with proteinuria'),('chronic-kidney-disease',1,'1Z17.00',NULL,'Chronic kidney disease stage 1 with proteinuria'),('chronic-kidney-disease',1,'K05..',NULL,'Chronic renal failure'),('chronic-kidney-disease',1,'K05..00',NULL,'Chronic renal failure'),('chronic-kidney-disease',1,'K055.',NULL,'Chronic kidney disease stage 5'),('chronic-kidney-disease',1,'K055.00',NULL,'Chronic kidney disease stage 5'),('chronic-kidney-disease',1,'K054.',NULL,'Chronic kidney disease stage 4'),('chronic-kidney-disease',1,'K054.00',NULL,'Chronic kidney disease stage 4'),('chronic-kidney-disease',1,'K053.',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'K053.00',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'K052.',NULL,'Chronic kidney disease stage 2'),('chronic-kidney-disease',1,'K052.00',NULL,'Chronic kidney disease stage 2'),
('chronic-kidney-disease',1,'K051.',NULL,'Chronic kidney disease stage 1'),('chronic-kidney-disease',1,'K051.00',NULL,'Chronic kidney disease stage 1'),('chronic-kidney-disease',1,'1Z1..',NULL,'Chronic renal impairment'),('chronic-kidney-disease',1,'1Z1..00',NULL,'Chronic renal impairment'),('chronic-kidney-disease',1,'K050.',NULL,'End stage renal failure'),('chronic-kidney-disease',1,'K050.00',NULL,'End stage renal failure'),('chronic-kidney-disease',1,'K0D..',NULL,'End-stage renal disease'),('chronic-kidney-disease',1,'K0D..00',NULL,'End-stage renal disease');
INSERT INTO #codesreadv2
VALUES ('diabetes-type-ii',1,'C1001',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C100100',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C101100',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C102100',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C103100',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C104100',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C105100',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C106100',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C107100',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C109.',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.00',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C109000',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C109100',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C109200',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C109300',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1094',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C109400',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1095',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C109500',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1096',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C109600',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1097',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C109700',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C1099',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C109900',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C109A',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A00',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109B',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B00',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109C',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C00',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109D',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D00',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109E',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E00',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109F',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F00',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109G',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G00',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109H',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H00',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109J',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109J00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109K',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109K00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10D.',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10D.00',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10F.',NULL,'Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F.00',NULL,'Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F0',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F000',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F1',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F100',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F2',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F200',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F3',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F300',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F4',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F400',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F5',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F500',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F6',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F600',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F7',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F700',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F9',NULL,'Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10F900',NULL,'Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10FA',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FA00',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FB',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FB00',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FC',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FC00',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FD',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FD00',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FE',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FE00',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FF',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FF00',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FG',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FG00',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FH',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FH00',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FJ',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FJ00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FL',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FL00',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FM',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FM00',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FN',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FN00',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FP',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FP00',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FQ',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'C10FQ00',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),
('diabetes-type-ii',1,'C10FR',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10FR00',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10y100',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'C10z100',NULL,'Diabetes mellitus, adult onset, with unspecified complication')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesreadv2;

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('chronic-kidney-disease',1,'X30In',NULL,'Chronic kidney disease'),('chronic-kidney-disease',1,'XaLHG',NULL,'Chronic kidney disease stage 1'),('chronic-kidney-disease',1,'XaLHH',NULL,'Chronic kidney disease stage 2'),('chronic-kidney-disease',1,'XaLHI',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'XaLHJ',NULL,'Chronic kidney disease stage 4'),('chronic-kidney-disease',1,'XaLHK',NULL,'Chronic kidney disease stage 5'),('chronic-kidney-disease',1,'Xac9y',NULL,'CKD G1A1 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A1'),('chronic-kidney-disease',1,'Xac9z',NULL,'CKD G1A2 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A2'),('chronic-kidney-disease',1,'XacA2',NULL,'CKD G1A3 - chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A3'),('chronic-kidney-disease',1,'XacA4',NULL,'CKD G2A1 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A1'),('chronic-kidney-disease',1,'XacA6',NULL,'CKD G2A2 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A2'),('chronic-kidney-disease',1,'XacA9',NULL,'CKD G2A3 - chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A3'),('chronic-kidney-disease',1,'XacAM',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('chronic-kidney-disease',1,'XacAN',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('chronic-kidney-disease',1,'XacAO',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('chronic-kidney-disease',1,'XacAV',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('chronic-kidney-disease',1,'XacAW',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('chronic-kidney-disease',1,'XacAX',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('chronic-kidney-disease',1,'XacAb',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('chronic-kidney-disease',1,'XacAd',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('chronic-kidney-disease',1,'XacAe',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('chronic-kidney-disease',1,'XacAf',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('chronic-kidney-disease',1,'XacAh',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('chronic-kidney-disease',1,'XacAi',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('chronic-kidney-disease',1,'XaO3p',NULL,'Chronic kidney disease stage 1 with proteinuria'),('chronic-kidney-disease',1,'XaO3s',NULL,'Chronic kidney disease stage 2 without proteinuria'),('chronic-kidney-disease',1,'XaNbn',NULL,'Chronic kidney disease stage 3A'),('chronic-kidney-disease',1,'XaNbo',NULL,'Chronic kidney disease stage 3B'),('chronic-kidney-disease',1,'XaO3t',NULL,'Chronic kidney disease stage 3 with proteinuria'),('chronic-kidney-disease',1,'XaO3u',NULL,'Chronic kidney disease stage 3 without proteinuria'),('chronic-kidney-disease',1,'XaO40',NULL,'Chronic kidney disease stage 4 without proteinuria'),('chronic-kidney-disease',1,'XaO3w',NULL,'Chronic kidney disease stage 3A without proteinuria'),('chronic-kidney-disease',1,'XaO3x',NULL,'Chronic kidney disease stage 3B with proteinuria'),('chronic-kidney-disease',1,'XaO3y',NULL,'Chronic kidney disease stage 3B without proteinuria'),('chronic-kidney-disease',1,'XaMFs',NULL,'Chronic kidney disease monitoring administration'),('chronic-kidney-disease',1,'XaMFt',NULL,'Chronic kidney disease monitoring first letter'),('chronic-kidney-disease',1,'XaMFu',NULL,'Chronic kidney disease monitoring second letter'),('chronic-kidney-disease',1,'XaMFv',NULL,'Chronic kidney disease monitoring third letter'),('chronic-kidney-disease',1,'XaMFw',NULL,'Chronic kidney disease monitoring verbal invite'),('chronic-kidney-disease',1,'XaMFx',NULL,'Chronic kidney disease monitoring telephone invite'),('chronic-kidney-disease',1,'XaMLh',NULL,'Predicted stage chronic kidney disease'),('chronic-kidney-disease',1,'X30J0',NULL,'ESCRF - End stage chronic renal failure'),('chronic-kidney-disease',1,'XaO3q',NULL,'Chronic kidney disease stage 1 without proteinuria'),('chronic-kidney-disease',1,'XaO3r',NULL,'Chronic kidney disease stage 2 with proteinuria'),('chronic-kidney-disease',1,'XaO3v',NULL,'Chronic kidney disease stage 3A with proteinuria'),('chronic-kidney-disease',1,'XaO3z',NULL,'Chronic kidney disease stage 4 with proteinuria'),('chronic-kidney-disease',1,'XaO41',NULL,'Chronic kidney disease stage 5 with proteinuria'),('chronic-kidney-disease',1,'XaO42',NULL,'Chronic kidney disease stage 5 without proteinuria');
INSERT INTO #codesctv3
VALUES ('diabetes-type-ii',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1094',NULL,'Non-insulin-dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1095',NULL,'Non-insulin-dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1096',NULL,'NIDDM - Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1097',NULL,'Non-insulin-dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'X40J5',NULL,'Non-insulin-dependent diabetes mellitus'),('diabetes-type-ii',1,'X40J6',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'X40JJ',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'XE10F',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'XM19j',NULL,'[EDTA] Diabetes Type II (non-insulin-dependent) associated with renal failure'),('diabetes-type-ii',1,'XaELQ',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'XaEnp',NULL,'Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'XaEnq',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'XaF05',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'XaFWI',NULL,'Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'XaFmA',NULL,'Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'XaFn7',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'XaFn8',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'XaFn9',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'XaIfG',NULL,'Type II diabetes on insulin'),('diabetes-type-ii',1,'XaIfI',NULL,'Type II diabetes on diet only'),('diabetes-type-ii',1,'XaIrf',NULL,'Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes-type-ii',1,'XaIzQ',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'XaIzR',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'XaJQp',NULL,'Type II diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'XaKyX',NULL,'Type II diabetes mellitus with gastroparesis')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesctv3;

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codessnomed
VALUES ('chronic-kidney-disease',1,'46177005',NULL,'End-stage renal disease'),('chronic-kidney-disease',1,'431855005',NULL,'CKD stage 1'),('chronic-kidney-disease',1,'431856006',NULL,'CKD stage 2'),('chronic-kidney-disease',1,'431857002',NULL,'CKD stage 4'),('chronic-kidney-disease',1,'433144002',NULL,'CKD stage 3'),('chronic-kidney-disease',1,'433146000',NULL,'CKD stage 5'),('chronic-kidney-disease',1,'700378005',NULL,'Chronic kidney disease stage 3A (disorder)'),('chronic-kidney-disease',1,'700379002',NULL,'Chronic kidney disease stage 3B (disorder)'),('chronic-kidney-disease',1,'707323002',NULL,'Anemia in chronic kidney disease'),('chronic-kidney-disease',1,'709044004',NULL,'Chronic renal disease'),('chronic-kidney-disease',1,'713313000',NULL,'Chronic kidney disease mineral and bone disorder (disorder)'),('chronic-kidney-disease',1,'714152005',NULL,'Chronic kidney disease stage 5 on dialysis'),('chronic-kidney-disease',1,'714153000',NULL,'CKD (chronic kidney disease) stage 5t'),('chronic-kidney-disease',1,'722098007',NULL,'Chronic kidney disease following donor nephrectomy'),('chronic-kidney-disease',1,'722149000',NULL,'Chronic kidney disease due to tumour nephrectomy'),('chronic-kidney-disease',1,'722150000',NULL,'Chronic kidney disease due to systemic infection'),('chronic-kidney-disease',1,'722467000',NULL,'Chronic kidney disease due to traumatic loss of kidney'),('chronic-kidney-disease',1,'140121000119100',NULL,'Hypertension in chronic kidney disease stage 3 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'140131000119102',NULL,'Hypertension in chronic kidney disease stage 2 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'140101000119109',NULL,'Hypertension in chronic kidney disease stage 5 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'140111000119107',NULL,'Hypertension in chronic kidney disease stage 4 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'71701000119105',NULL,'Hypertension in chronic kidney disease due to type I diabetes mellitus'),('chronic-kidney-disease',1,'71421000119105',NULL,'Hypertension in chronic kidney disease due to type II diabetes mellitus'),('chronic-kidney-disease',1,'104931000119100',NULL,'Chronic kidney disease due to hypertension (disorder)'),('chronic-kidney-disease',1,'731000119105',NULL,'Chronic kidney disease stage 3 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'741000119101',NULL,'Chronic kidney disease stage 2 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'711000119100',NULL,'Chronic kidney disease stage 5 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'721000119107',NULL,'Chronic kidney disease stage 4 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'96441000119101',NULL,'Chronic kidney disease due to type I diabetes mellitus'),('chronic-kidney-disease',1,'771000119108',NULL,'Chronic kidney disease due to type 2 diabetes mellitus (disorder)'),('chronic-kidney-disease',1,'10757481000119107',NULL,'Preexisting hypertensive heart and chronic kidney disease in pregnancy'),('chronic-kidney-disease',1,'285831000119108',NULL,'Malignant hypertensive chronic kidney disease (disorder)'),('chronic-kidney-disease',1,'129161000119100',NULL,'Chronic kidney disease stage 5 due to hypertension (disorder)'),('chronic-kidney-disease',1,'117681000119102',NULL,'Chronic kidney disease stage 1 due to hypertension (disorder)'),('chronic-kidney-disease',1,'129171000119106',NULL,'Chronic kidney disease stage 3 due to hypertension (disorder)'),('chronic-kidney-disease',1,'129181000119109',NULL,'Chronic kidney disease stage 2 due to hypertension (disorder)'),('chronic-kidney-disease',1,'129151000119102',NULL,'Chronic kidney disease stage 4 due to hypertension (disorder)'),('chronic-kidney-disease',1,'8501000119104',NULL,'Hypertensive heart and chronic kidney disease (disorder)'),('chronic-kidney-disease',1,'96701000119107',NULL,'Hypertensive heart AND chronic kidney disease on dialysis (disorder)'),('chronic-kidney-disease',1,'284961000119106',NULL,'Chronic kidney disease due to benign hypertension (disorder)'),('chronic-kidney-disease',1,'324281000000104',NULL,'Chronic kidney disease stage 3 without proteinuria'),('chronic-kidney-disease',1,'324251000000105',NULL,'Chronic kidney disease stage 3 with proteinuria'),('chronic-kidney-disease',1,'285871000119106',NULL,'Malignant hypertensive chronic kidney disease stage 3 (disorder)'),('chronic-kidney-disease',1,'96731000119100',NULL,'Hypertensive heart AND chronic kidney disease stage 3 (disorder)'),('chronic-kidney-disease',1,'90741000119107',NULL,'Chronic kidney disease stage 3 due to type I diabetes mellitus'),('chronic-kidney-disease',1,'284991000119104',NULL,'Chronic kidney disease stage 3 due to benign hypertension'),('chronic-kidney-disease',1,'691421000119108',NULL,'Anemia co-occurrent and due to chronic kidney disease stage 3'),('chronic-kidney-disease',1,'324211000000106',NULL,'Chronic kidney disease stage 2 without proteinuria'),('chronic-kidney-disease',1,'324181000000105',NULL,'Chronic kidney disease stage 2 with proteinuria'),('chronic-kidney-disease',1,'285861000119100',NULL,'Malignant hypertensive chronic kidney disease stage 2 (disorder)'),('chronic-kidney-disease',1,'96741000119109',NULL,'Hypertensive heart AND chronic kidney disease stage 2 (disorder)'),('chronic-kidney-disease',1,'90731000119103',NULL,'Chronic kidney disease stage 2 due to type I diabetes mellitus'),('chronic-kidney-disease',1,'284981000119102',NULL,'Chronic kidney disease stage 2 due to benign hypertension (disorder)'),('chronic-kidney-disease',1,'324541000000105',NULL,'Chronic kidney disease stage 5 without proteinuria'),('chronic-kidney-disease',1,'324501000000107',NULL,'Chronic kidney disease stage 5 with proteinuria'),('chronic-kidney-disease',1,'153851000119106',NULL,'Malignant hypertensive chronic kidney disease stage 5 (disorder)'),('chronic-kidney-disease',1,'96711000119105',NULL,'Hypertensive heart AND chronic kidney disease stage 5 (disorder)'),('chronic-kidney-disease',1,'90761000119106',NULL,'Chronic kidney disease stage 5 due to type I diabetes mellitus'),('chronic-kidney-disease',1,'285011000119108',NULL,'Chronic kidney disease stage 5 due to benign hypertension'),('chronic-kidney-disease',1,'324441000000106',NULL,'Chronic kidney disease stage 4 with proteinuria'),('chronic-kidney-disease',1,'324471000000100',NULL,'Chronic kidney disease stage 4 without proteinuria'),('chronic-kidney-disease',1,'285881000119109',NULL,'Malignant hypertensive chronic kidney disease stage 4 (disorder)'),('chronic-kidney-disease',1,'96721000119103',NULL,'Hypertensive heart AND chronic kidney disease stage 4 (disorder)'),('chronic-kidney-disease',1,'90751000119109',NULL,'Chronic kidney disease stage 4 due to type I diabetes mellitus'),('chronic-kidney-disease',1,'285001000119105',NULL,'Chronic kidney disease stage 4 due to benign hypertension (disorder)'),('chronic-kidney-disease',1,'90721000119101',NULL,'Chronic kidney disease stage 1 due to type I diabetes mellitus'),('chronic-kidney-disease',1,'751000119104',NULL,'Chronic kidney disease stage 1 due to type II diabetes mellitus'),('chronic-kidney-disease',1,'285851000119102',NULL,'Malignant hypertensive chronic kidney disease stage 1 (disorder)'),('chronic-kidney-disease',1,'96751000119106',NULL,'Hypertensive heart AND chronic kidney disease stage 1 (disorder)'),('chronic-kidney-disease',1,'284971000119100',NULL,'Chronic kidney disease stage 1 due to benign hypertension (disorder)'),('chronic-kidney-disease',1,'10757401000119104',NULL,'Pre-existing hypertensive heart and chronic kidney disease in mother complicating childbirth'),('chronic-kidney-disease',1,'324311000000101',NULL,'Chronic kidney disease stage 3A with proteinuria'),('chronic-kidney-disease',1,'324341000000100',NULL,'Chronic kidney disease stage 3A without proteinuria'),('chronic-kidney-disease',1,'324371000000106',NULL,'Chronic kidney disease stage 3B with proteinuria'),('chronic-kidney-disease',1,'324411000000105',NULL,'Chronic kidney disease stage 3B without proteinuria'),('chronic-kidney-disease',1,'949521000000108',NULL,'Chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A1'),('chronic-kidney-disease',1,'949561000000100',NULL,'Chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A2'),('chronic-kidney-disease',1,'949621000000109',NULL,'Chronic kidney disease with glomerular filtration rate category G2 and albuminuria category A3'),('chronic-kidney-disease',1,'950251000000106',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('chronic-kidney-disease',1,'950291000000103',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('chronic-kidney-disease',1,'950311000000102',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('chronic-kidney-disease',1,'950181000000106',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('chronic-kidney-disease',1,'950211000000107',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('chronic-kidney-disease',1,'950231000000104',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('chronic-kidney-disease',1,'324151000000104',NULL,'Chronic kidney disease stage 1 without proteinuria'),('chronic-kidney-disease',1,'324121000000109',NULL,'Chronic kidney disease stage 1 with proteinuria'),('chronic-kidney-disease',1,'949881000000106',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('chronic-kidney-disease',1,'949901000000109',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),
('chronic-kidney-disease',1,'949921000000100',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('chronic-kidney-disease',1,'950061000000103',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('chronic-kidney-disease',1,'950081000000107',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('chronic-kidney-disease',1,'950101000000101',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('chronic-kidney-disease',1,'949401000000103',NULL,'Chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A1'),('chronic-kidney-disease',1,'949421000000107',NULL,'Chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A2'),('chronic-kidney-disease',1,'949481000000108',NULL,'Chronic kidney disease with glomerular filtration rate category G1 and albuminuria category A3'),('chronic-kidney-disease',1,'691401000119104',NULL,'Anaemia in chronic kidney disease stage 4'),('chronic-kidney-disease',1,'691411000119101',NULL,'Anaemia in chronic kidney disease stage 5'),('chronic-kidney-disease',1,'444271000',NULL,'Erythropoietin resistance in anemia of chronic kidney disease'),('chronic-kidney-disease',1,'15781000119107',NULL,'Hypertensive heart AND chronic kidney disease with congestive heart failure (disorder)');
INSERT INTO #codessnomed
VALUES ('diabetes-type-ii',1,'190331003',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma (disorder)'),('diabetes-type-ii',1,'190388001',NULL,'Type II diabetes mellitus with multiple complications (disorder)'),('diabetes-type-ii',1,'190389009',NULL,'Type II diabetes mellitus with ulcer (disorder)'),('diabetes-type-ii',1,'237599002',NULL,'Insulin-treated non-insulin-dependent diabetes mellitus (disorder)'),('diabetes-type-ii',1,'237604008',NULL,'Diabetes mellitus autosomal dominant type II (disorder)'),('diabetes-type-ii',1,'24471000000103',NULL,'Type 2 diabetes on insulin (finding)'),('diabetes-type-ii',1,'24481000000101',NULL,'Type 2 diabetes on diet only (finding)'),('diabetes-type-ii',1,'313436004',NULL,'Type II diabetes mellitus without complication (disorder)'),('diabetes-type-ii',1,'314902007',NULL,'Type II diabetes mellitus with peripheral angiopathy (disorder)'),('diabetes-type-ii',1,'314903002',NULL,'Type II diabetes mellitus with arthropathy (disorder)'),('diabetes-type-ii',1,'314904008',NULL,'Type II diabetes mellitus with neuropathic arthropathy (disorder)'),('diabetes-type-ii',1,'44054006',NULL,'Diabetes mellitus type 2 (disorder)'),('diabetes-type-ii',1,'443694000',NULL,'Type II diabetes mellitus uncontrolled (finding)'),('diabetes-type-ii',1,'190390000',NULL,'Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'1481000119100',NULL,'Diabetes mellitus type 2 without retinopathy'),('diabetes-type-ii',1,'445353002',NULL,'Brittle type II diabetes mellitus')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codessnomed;

IF OBJECT_ID('tempdb..#codesemis') IS NOT NULL DROP TABLE #codesemis;
CREATE TABLE #codesemis (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesemis
VALUES ('chronic-kidney-disease',1,'EMISNQCH20',NULL,'Chronic kidney disease stage 3'),('chronic-kidney-disease',1,'EMISNQCH17',NULL,'Chronic kidney disease stage')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesemis;


IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, version INT NOT NULL, [description] VARCHAR(255));

-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.concept, dcr.[version], dcr.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
AND (dcr.term IS NULL OR dcr.term = rc.Term)
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.concept, dcc.[version], dcc.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

-- EMIS codes with a FK Reference Coding ID
INSERT INTO #TempRefCodes
SELECT FK_Reference_Coding_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [version] INT NOT NULL, [description] VARCHAR(255));

-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.concept, dcs.[version], dcs.[description]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- EMIS codes with a FK SNOMED ID but without a FK Reference Coding ID
INSERT INTO #TempSNOMEDRefCodes
SELECT FK_Reference_SnomedCT_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID = -1
AND FK_Reference_SnomedCT_ID != -1;

-- De-duped tables
IF OBJECT_ID('tempdb..#CodeSets') IS NOT NULL DROP TABLE #CodeSets;
CREATE TABLE #CodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#SnomedSets') IS NOT NULL DROP TABLE #SnomedSets;
CREATE TABLE #SnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedCodeSets') IS NOT NULL DROP TABLE #VersionedCodeSets;
CREATE TABLE #VersionedCodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedSnomedSets') IS NOT NULL DROP TABLE #VersionedSnomedSets;
CREATE TABLE #VersionedSnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

INSERT INTO #VersionedCodeSets
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #VersionedSnomedSets
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

INSERT INTO #CodeSets
SELECT FK_Reference_Coding_ID, c.concept, [description]
FROM #VersionedCodeSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedCodeSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

INSERT INTO #SnomedSets
SELECT FK_Reference_SnomedCT_ID, c.concept, [description]
FROM #VersionedSnomedSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedSnomedSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

--#endregion

-- >>> Following code sets injected: diabetes-type-ii v1
IF OBJECT_ID('tempdb..#PatientT2Dtemppart1') IS NOT NULL DROP TABLE #PatientT2Dtemppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientT2Dtemppart1
FROM SharedCare.GP_Events
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'diabetes-type-ii' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientT2Dtemppart2') IS NOT NULL DROP TABLE #PatientT2Dtemppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientT2Dtemppart2
FROM SharedCare.GP_Events
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'diabetes-type-ii' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientT2D') IS NOT NULL DROP TABLE #PatientT2D;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientT2D
FROM #PatientT2Dtemppart1 p1
FULL JOIN #PatientT2Dtemppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID


-- Get first CKD diagnosis date

-- >>> Following code sets injected: chronic-kidney-disease v1
IF OBJECT_ID('tempdb..#PatientCKDtemppart1') IS NOT NULL DROP TABLE #PatientCKDtemppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKDtemppart1
FROM SharedCare.GP_Events
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'chronic-kidney-disease' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKDtemppart2') IS NOT NULL DROP TABLE #PatientCKDtemppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKDtemppart2
FROM SharedCare.GP_Events
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'chronic-kidney-disease' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD') IS NOT NULL DROP TABLE #PatientCKD;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientCKD
FROM #PatientCKDtemppart1 p1
FULL JOIN #PatientCKDtemppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID


IF OBJECT_ID('tempdb..#Cohort') IS NOT NULL DROP TABLE #Cohort;
SELECT 
	t2d.FK_Patient_Link_ID,
	YEAR(t2d.DateOfFirstDiagnosis) * 100 + MONTH(t2d.DateOfFirstDiagnosis) AS YearMonthOfFirstT2DDiagnosis, 
	YEAR(ckd.DateOfFirstDiagnosis) * 100 + MONTH(ckd.DateOfFirstDiagnosis) AS YearMonthOfFirstCKDDiagnosis
INTO #Cohort
FROM #PatientT2D t2d
LEFT OUTER JOIN #PatientCKD ckd ON t2d.FK_Patient_Link_ID = ckd.FK_Patient_Link_ID
WHERE t2d.DateOfFirstDiagnosis < '2023-09-19'
AND (ckd.DateOfFirstDiagnosis IS NULL OR ckd.DateOfFirstDiagnosis > DATEADD(month, -30, '2023-09-19'));

TRUNCATE TABLE #Patients
INSERT INTO #Patients
SELECT FK_Patient_Link_ID FROM #Cohorot;

