--┌────────────┐
--│ GP history │
--└────────────┘

-- OBJECTIVE: To get the GP history for each patient. NB the first start
--            date for each person may either be the date they started at
--            the practice OR the date they were first loaded into the database.

-- OUTPUT: Data with the following fields
--  - PatientId
--  - StartDate - date (YYYY/MM/DD) - start date at practice
--  - EndDate - date (YYYY/MM/DD) - end date at practice
--  - GPPracticeCode - practice code

--Just want the output, not the messages
SET NOCOUNT ON;

--┌───────────────────────────────────────────────────────────────────┐
--│ Define Cohort for Gendius project: patients with T2D but no CKD   │
--└───────────────────────────────────────────────────────────────────┘

-- OBJECTIVE: To build the cohort of patients needed for the Gendius
--		project. This reduces duplication of code in the template scripts.
--            
--    Index date = 2.5 years prior to extraction date. Adults who
--      (1) have a type 2 diabetes diagnosis before the date of extraction, 
-- 			(2) were registered with a GP in GM between the index and
--			    extraction date,
--      (3) at the index date:
--        - are alive,and
--        - do not have a diagnosis of CKD stage 3-5.

-- INPUT: A single variable:
--  - extraction-date: date - (YYYY-MM-DD) the date of the extract

-- OUTPUT: Four temp tables:
--  - #Patients - list of all patients in the cohort
--  -   - FK_Patient_Link_ID - int
--  - #Cohort - table with each patient in the cohort and dx details
--  -   - FK_Patient_Link_ID - int
--  -   - FirstT2dDiagnosisYear - int
--  -   - FirstT2dDiagnosisMonth  - int
--  -   - FirstCkdDiagnosisYear - int
--  -   - FirstCkdDiagnosisMonth - int
--  -   - DeathDate - date (YYYY-MM-DD)
--  - #PatientEventData - table with all GP_Event codes for cohort
--  - #PatientMedicationDate - table with all GP_Medication codes for cohort

-- Table of all patients (not necessarily with a GP record yet)
IF OBJECT_ID('tempdb..#Patients') IS NOT NULL DROP TABLE #Patients;
SELECT DISTINCT FK_Patient_Link_ID
INTO #Patients
FROM SharedCare.Patient
WHERE FK_Reference_Tenancy_ID=2;

-- Get first T2D diagnosis date

-- >>> Codesets required... Inserting the code set code
--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘

-- OBJECTIVE: To populate temporary tables with the existing clinical code sets.
--            See the [SQL-generation-process.md](SQL-generation-process.md) for more details.

-- INPUT: No pre-requisites

-- OUTPUT: Five temp tables as follows:
--  #AllCodes (Concept, Version, Code)
--  #CodeSets (FK_Reference_Coding_ID, Concept)
--  #SnomedSets (FK_Reference_SnomedCT_ID, FK_SNOMED_ID)
--  #VersionedCodeSets (FK_Reference_Coding_ID, Concept, Version)
--  #VersionedSnomedSets (FK_Reference_SnomedCT_ID, Version, FK_SNOMED_ID)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

--#region Clinical code sets

IF OBJECT_ID('tempdb..#AllCodes') IS NOT NULL DROP TABLE #AllCodes;
CREATE TABLE #AllCodes (
  [Concept] [varchar](255) NOT NULL,
  [Version] INT NOT NULL,
  [Code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
  [description] [varchar] (255) NULL 
);

IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('ckd-stage-3',1,'1Z1Z.',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('ckd-stage-3',1,'1Z1Z.00',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('ckd-stage-3',1,'1Z1Y.',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('ckd-stage-3',1,'1Z1Y.00',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('ckd-stage-3',1,'1Z1X.',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('ckd-stage-3',1,'1Z1X.00',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('ckd-stage-3',1,'1Z1W.',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('ckd-stage-3',1,'1Z1W.00',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('ckd-stage-3',1,'1Z1V.',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('ckd-stage-3',1,'1Z1V.00',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('ckd-stage-3',1,'1Z1T.',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('ckd-stage-3',1,'1Z1T.00',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('ckd-stage-3',1,'1Z16.',NULL,'Chronic kidney disease stage 3B'),('ckd-stage-3',1,'1Z16.00',NULL,'Chronic kidney disease stage 3B'),('ckd-stage-3',1,'1Z15.',NULL,'Chronic kidney disease stage 3A'),('ckd-stage-3',1,'1Z15.00',NULL,'Chronic kidney disease stage 3A'),('ckd-stage-3',1,'1Z12.',NULL,'Chronic kidney disease stage 3'),('ckd-stage-3',1,'1Z12.00',NULL,'Chronic kidney disease stage 3'),('ckd-stage-3',1,'1Z1G.',NULL,'Chronic kidney disease stage 3B without proteinuria'),('ckd-stage-3',1,'1Z1G.00',NULL,'Chronic kidney disease stage 3B without proteinuria'),('ckd-stage-3',1,'1Z1F.',NULL,'Chronic kidney disease stage 3B with proteinuria'),('ckd-stage-3',1,'1Z1F.00',NULL,'Chronic kidney disease stage 3B with proteinuria'),('ckd-stage-3',1,'1Z1E.',NULL,'Chronic kidney disease stage 3A without proteinuria'),('ckd-stage-3',1,'1Z1E.00',NULL,'Chronic kidney disease stage 3A without proteinuria'),('ckd-stage-3',1,'1Z1D.',NULL,'Chronic kidney disease stage 3A with proteinuria'),('ckd-stage-3',1,'1Z1D.00',NULL,'Chronic kidney disease stage 3A with proteinuria'),('ckd-stage-3',1,'1Z1C.',NULL,'Chronic kidney disease stage 3 without proteinuria'),('ckd-stage-3',1,'1Z1C.00',NULL,'Chronic kidney disease stage 3 without proteinuria'),('ckd-stage-3',1,'1Z1B.',NULL,'Chronic kidney disease stage 3 with proteinuria'),('ckd-stage-3',1,'1Z1B.00',NULL,'Chronic kidney disease stage 3 with proteinuria'),('ckd-stage-3',1,'K053.',NULL,'Chronic kidney disease stage 3'),('ckd-stage-3',1,'K053.00',NULL,'Chronic kidney disease stage 3');
INSERT INTO #codesreadv2
VALUES ('ckd-stage-4',1,'1Z1c.',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('ckd-stage-4',1,'1Z1c.00',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('ckd-stage-4',1,'1Z1b.',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('ckd-stage-4',1,'1Z1b.00',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('ckd-stage-4',1,'1Z1a.',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('ckd-stage-4',1,'1Z1a.00',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('ckd-stage-4',1,'1Z13.',NULL,'Chronic kidney disease stage 4'),('ckd-stage-4',1,'1Z13.00',NULL,'Chronic kidney disease stage 4'),('ckd-stage-4',1,'1Z1J.',NULL,'Chronic kidney disease stage 4 without proteinuria'),('ckd-stage-4',1,'1Z1J.00',NULL,'Chronic kidney disease stage 4 without proteinuria'),('ckd-stage-4',1,'1Z1H.',NULL,'Chronic kidney disease stage 4 with proteinuria'),('ckd-stage-4',1,'1Z1H.00',NULL,'Chronic kidney disease stage 4 with proteinuria'),('ckd-stage-4',1,'K054.',NULL,'Chronic kidney disease stage 4'),('ckd-stage-4',1,'K054.00',NULL,'Chronic kidney disease stage 4');
INSERT INTO #codesreadv2
VALUES ('ckd-stage-5',1,'1Z1f.',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('ckd-stage-5',1,'1Z1f.00',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('ckd-stage-5',1,'1Z1e.',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('ckd-stage-5',1,'1Z1e.00',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('ckd-stage-5',1,'1Z1d.',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('ckd-stage-5',1,'1Z1d.00',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('ckd-stage-5',1,'1Z14.',NULL,'Chronic kidney disease stage 5'),('ckd-stage-5',1,'1Z14.00',NULL,'Chronic kidney disease stage 5'),('ckd-stage-5',1,'1Z1L.',NULL,'Chronic kidney disease stage 5 without proteinuria'),('ckd-stage-5',1,'1Z1L.00',NULL,'Chronic kidney disease stage 5 without proteinuria'),('ckd-stage-5',1,'1Z1K.',NULL,'Chronic kidney disease stage 5 with proteinuria'),('ckd-stage-5',1,'1Z1K.00',NULL,'Chronic kidney disease stage 5 with proteinuria'),('ckd-stage-5',1,'K055.',NULL,'Chronic kidney disease stage 5'),('ckd-stage-5',1,'K055.00',NULL,'Chronic kidney disease stage 5'),('ckd-stage-5',1,'K0D..',NULL,'End-stage renal disease'),('ckd-stage-5',1,'K0D..00',NULL,'End-stage renal disease'),('ckd-stage-5',1,'K050.',NULL,'End stage renal failure'),('ckd-stage-5',1,'K050.00',NULL,'End stage renal failure');
INSERT INTO #codesreadv2
VALUES ('diabetes-type-ii',1,'C1001',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C100100',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C101100',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C102100',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C103100',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C104100',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C105100',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C106100',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C107100',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C109.',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.00',NULL,'Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C109000',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C109100',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C109200',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C109300',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1094',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C109400',NULL,'Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1095',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C109500',NULL,'Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1096',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C109600',NULL,'Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1097',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C109700',NULL,'Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C1099',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C109900',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C109A',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A00',NULL,'Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109B',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B00',NULL,'Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109C',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C00',NULL,'Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109D',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D00',NULL,'Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109E',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E00',NULL,'Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109F',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F00',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109G',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G00',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109H',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H00',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109J',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109J00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109K',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109K00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10D.',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10D.00',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10F.',NULL,'Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F.00',NULL,'Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F0',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F000',NULL,'Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F1',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F100',NULL,'Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F2',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F200',NULL,'Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F3',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F300',NULL,'Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F4',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F400',NULL,'Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F5',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F500',NULL,'Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F6',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F600',NULL,'Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F7',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F700',NULL,'Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F9',NULL,'Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10F900',NULL,'Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10FA',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FA00',NULL,'Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FB',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FB00',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FC',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FC00',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FD',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FD00',NULL,'Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FE',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FE00',NULL,'Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FF',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FF00',NULL,'Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FG',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FG00',NULL,'Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FH',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FH00',NULL,'Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FJ',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FJ00',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK00',NULL,'Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FL',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FL00',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FM',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FM00',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FN',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FN00',NULL,'Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FP',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FP00',NULL,'Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FQ',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'C10FQ00',NULL,'Type 2 diabetes mellitus with exudative maculopathy'),
('diabetes-type-ii',1,'C10FR',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10FR00',NULL,'Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10y100',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'C10z100',NULL,'Diabetes mellitus, adult onset, with unspecified complication')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesreadv2;

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('ckd-stage-3',1,'XaLHI',NULL,'Chronic kidney disease stage 3'),('ckd-stage-3',1,'XacAM',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('ckd-stage-3',1,'XacAN',NULL,'CKD G3aA2 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('ckd-stage-3',1,'XacAO',NULL,'CKD G3aA3 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('ckd-stage-3',1,'XacAV',NULL,'CKD G3bA1 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('ckd-stage-3',1,'XacAW',NULL,'CKD G3bA2 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('ckd-stage-3',1,'XacAX',NULL,'CKD G3bA3 - chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('ckd-stage-3',1,'XaNbn',NULL,'Chronic kidney disease stage 3A'),('ckd-stage-3',1,'XaNbo',NULL,'Chronic kidney disease stage 3B'),('ckd-stage-3',1,'XaO3t',NULL,'Chronic kidney disease stage 3 with proteinuria'),('ckd-stage-3',1,'XaO3u',NULL,'Chronic kidney disease stage 3 without proteinuria'),('ckd-stage-3',1,'XaO3w',NULL,'Chronic kidney disease stage 3A without proteinuria'),('ckd-stage-3',1,'XaO3x',NULL,'Chronic kidney disease stage 3B with proteinuria'),('ckd-stage-3',1,'XaO3y',NULL,'Chronic kidney disease stage 3B without proteinuria'),('ckd-stage-3',1,'XaO3v',NULL,'Chronic kidney disease stage 3A with proteinuria');
INSERT INTO #codesctv3
VALUES ('ckd-stage-4',1,'XaLHJ',NULL,'Chronic kidney disease stage 4'),('ckd-stage-4',1,'XacAb',NULL,'CKD G4A1 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('ckd-stage-4',1,'XacAd',NULL,'CKD G4A2 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('ckd-stage-4',1,'XacAe',NULL,'CKD G4A3 - chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('ckd-stage-4',1,'XaO40',NULL,'Chronic kidney disease stage 4 without proteinuria'),('ckd-stage-4',1,'XaO3z',NULL,'Chronic kidney disease stage 4 with proteinuria');
INSERT INTO #codesctv3
VALUES ('ckd-stage-5',1,'XaLHK',NULL,'Chronic kidney disease stage 5'),('ckd-stage-5',1,'XacAf',NULL,'CKD G5A1 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('ckd-stage-5',1,'XacAh',NULL,'CKD G5A2 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('ckd-stage-5',1,'XacAi',NULL,'CKD G5A3 - chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('ckd-stage-5',1,'XaO41',NULL,'Chronic kidney disease stage 5 with proteinuria'),('ckd-stage-5',1,'XaO42',NULL,'Chronic kidney disease stage 5 without proteinuria'),('ckd-stage-5',1,'X30J0',NULL,'ESCRF - End stage chronic renal failure'),('ckd-stage-5',1,'X30J1',NULL,'End stage renal failure untreated by renal replacement therapy'),('ckd-stage-5',1,'X30J2',NULL,'End stage renal failure on dialysis'),('ckd-stage-5',1,'X30J3',NULL,'End stage renal failure with renal transplant');
INSERT INTO #codesctv3
VALUES ('diabetes-type-ii',1,'C1011',NULL,'Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1021',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1031',NULL,'Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1041',NULL,'Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1051',NULL,'Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1061',NULL,'Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1071',NULL,'Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C1090',NULL,'Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1091',NULL,'Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1092',NULL,'Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1093',NULL,'Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1094',NULL,'Non-insulin-dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1095',NULL,'Non-insulin-dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1096',NULL,'NIDDM - Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1097',NULL,'Non-insulin-dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10y1',NULL,'Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z1',NULL,'Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'X40J5',NULL,'Non-insulin-dependent diabetes mellitus'),('diabetes-type-ii',1,'X40J6',NULL,'Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'X40JJ',NULL,'Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'XE10F',NULL,'Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'XM19j',NULL,'[EDTA] Diabetes Type II (non-insulin-dependent) associated with renal failure'),('diabetes-type-ii',1,'XaELQ',NULL,'Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'XaEnp',NULL,'Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'XaEnq',NULL,'Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'XaF05',NULL,'Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'XaFWI',NULL,'Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'XaFmA',NULL,'Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'XaFn7',NULL,'Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'XaFn8',NULL,'Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'XaFn9',NULL,'Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'XaIfG',NULL,'Type II diabetes on insulin'),('diabetes-type-ii',1,'XaIfI',NULL,'Type II diabetes on diet only'),('diabetes-type-ii',1,'XaIrf',NULL,'Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes-type-ii',1,'XaIzQ',NULL,'Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'XaIzR',NULL,'Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'XaJQp',NULL,'Type II diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'XaKyX',NULL,'Type II diabetes mellitus with gastroparesis')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesctv3;

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codessnomed
VALUES ('ckd-stage-3',1,'433144002',NULL,'CKD stage 3'),('ckd-stage-3',1,'700378005',NULL,'Chronic kidney disease stage 3A (disorder)'),('ckd-stage-3',1,'700379002',NULL,'Chronic kidney disease stage 3B (disorder)'),('ckd-stage-3',1,'140121000119100',NULL,'Hypertension in chronic kidney disease stage 3 due to type II diabetes mellitus'),('ckd-stage-3',1,'731000119105',NULL,'Chronic kidney disease stage 3 due to type II diabetes mellitus'),('ckd-stage-3',1,'129171000119106',NULL,'Chronic kidney disease stage 3 due to hypertension (disorder)'),('ckd-stage-3',1,'324281000000104',NULL,'Chronic kidney disease stage 3 without proteinuria'),('ckd-stage-3',1,'324251000000105',NULL,'Chronic kidney disease stage 3 with proteinuria'),('ckd-stage-3',1,'285871000119106',NULL,'Malignant hypertensive chronic kidney disease stage 3 (disorder)'),('ckd-stage-3',1,'96731000119100',NULL,'Hypertensive heart AND chronic kidney disease stage 3 (disorder)'),('ckd-stage-3',1,'90741000119107',NULL,'Chronic kidney disease stage 3 due to type I diabetes mellitus'),('ckd-stage-3',1,'284991000119104',NULL,'Chronic kidney disease stage 3 due to benign hypertension'),('ckd-stage-3',1,'691421000119108',NULL,'Anemia co-occurrent and due to chronic kidney disease stage 3'),('ckd-stage-3',1,'324311000000101',NULL,'Chronic kidney disease stage 3A with proteinuria'),('ckd-stage-3',1,'324341000000100',NULL,'Chronic kidney disease stage 3A without proteinuria'),('ckd-stage-3',1,'324371000000106',NULL,'Chronic kidney disease stage 3B with proteinuria'),('ckd-stage-3',1,'324411000000105',NULL,'Chronic kidney disease stage 3B without proteinuria'),('ckd-stage-3',1,'949881000000106',NULL,'CKD G3aA1 - chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('ckd-stage-3',1,'949901000000109',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('ckd-stage-3',1,'949921000000100',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('ckd-stage-3',1,'950061000000103',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('ckd-stage-3',1,'950081000000107',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('ckd-stage-3',1,'950101000000101',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3');
INSERT INTO #codessnomed
VALUES ('ckd-stage-4',1,'431857002',NULL,'CKD stage 4'),('ckd-stage-4',1,'140111000119107',NULL,'Hypertension in chronic kidney disease stage 4 due to type II diabetes mellitus'),('ckd-stage-4',1,'721000119107',NULL,'Chronic kidney disease stage 4 due to type II diabetes mellitus'),('ckd-stage-4',1,'129151000119102',NULL,'Chronic kidney disease stage 4 due to hypertension (disorder)'),('ckd-stage-4',1,'324441000000106',NULL,'Chronic kidney disease stage 4 with proteinuria'),('ckd-stage-4',1,'324471000000100',NULL,'Chronic kidney disease stage 4 without proteinuria'),('ckd-stage-4',1,'285881000119109',NULL,'Malignant hypertensive chronic kidney disease stage 4 (disorder)'),('ckd-stage-4',1,'96721000119103',NULL,'Hypertensive heart AND chronic kidney disease stage 4 (disorder)'),('ckd-stage-4',1,'90751000119109',NULL,'Chronic kidney disease stage 4 due to type I diabetes mellitus'),('ckd-stage-4',1,'285001000119105',NULL,'Chronic kidney disease stage 4 due to benign hypertension (disorder)'),('ckd-stage-4',1,'950181000000106',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('ckd-stage-4',1,'950211000000107',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('ckd-stage-4',1,'950231000000104',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('ckd-stage-4',1,'691401000119104',NULL,'Anaemia in chronic kidney disease stage 4');
INSERT INTO #codessnomed
VALUES ('ckd-stage-5',1,'433146000',NULL,'CKD stage 5'),('ckd-stage-5',1,'714152005',NULL,'Chronic kidney disease stage 5 on dialysis'),('ckd-stage-5',1,'140101000119109',NULL,'Hypertension in chronic kidney disease stage 5 due to type II diabetes mellitus'),('ckd-stage-5',1,'711000119100',NULL,'Chronic kidney disease stage 5 due to type II diabetes mellitus'),('ckd-stage-5',1,'129161000119100',NULL,'Chronic kidney disease stage 5 due to hypertension (disorder)'),('ckd-stage-5',1,'324541000000105',NULL,'Chronic kidney disease stage 5 without proteinuria'),('ckd-stage-5',1,'324501000000107',NULL,'Chronic kidney disease stage 5 with proteinuria'),('ckd-stage-5',1,'153851000119106',NULL,'Malignant hypertensive chronic kidney disease stage 5 (disorder)'),('ckd-stage-5',1,'96711000119105',NULL,'Hypertensive heart AND chronic kidney disease stage 5 (disorder)'),('ckd-stage-5',1,'90761000119106',NULL,'Chronic kidney disease stage 5 due to type I diabetes mellitus'),('ckd-stage-5',1,'285011000119108',NULL,'Chronic kidney disease stage 5 due to benign hypertension'),('ckd-stage-5',1,'950251000000106',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('ckd-stage-5',1,'950291000000103',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('ckd-stage-5',1,'950311000000102',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('ckd-stage-5',1,'691411000119101',NULL,'Anaemia in chronic kidney disease stage 5'),('ckd-stage-5',1,'46177005',NULL,'End-stage renal disease'),('ckd-stage-5',1,'714153000',NULL,'Chronic kidney disease stage 5 with transplant'),('ckd-stage-5',1,'707324008',NULL,'Anemia co-occurrent and due to end stage renal disease (disorder)'),('ckd-stage-5',1,'16320631000119104',NULL,'Dependence on continuous ambulatory peritoneal dialysis due to end stage renal disease (finding)'),('ckd-stage-5',1,'429075005',NULL,'Dependence on dialysis due to end stage renal disease (finding)'),('ckd-stage-5',1,'428982002',NULL,'Dependence on hemodialysis due to end stage renal disease (finding)'),('ckd-stage-5',1,'428937001',NULL,'Dependence on peritoneal dialysis due to end stage renal disease (finding)'),('ckd-stage-5',1,'111411000119103',NULL,'End stage renal disease due to hypertension (disorder)'),('ckd-stage-5',1,'236435004',NULL,'End stage renal failure on dialysis (disorder)'),('ckd-stage-5',1,'236434000',NULL,'End stage renal failure untreated by renal replacement therapy (disorder)'),('ckd-stage-5',1,'236436003',NULL,'End stage renal failure with renal transplant (disorder)'),('ckd-stage-5',1,'712487000',NULL,'End stage renal disease due to benign hypertension (disorder)'),('ckd-stage-5',1,'153891000119101',NULL,'End stage renal disease on dialysis due to hypertension (disorder)'),('ckd-stage-5',1,'285841000119104',NULL,'Malignant hypertensive end stage renal disease (disorder)'),('ckd-stage-5',1,'286371000119107',NULL,'Malignant hypertensive end stage renal disease on dialysis (disorder)');
INSERT INTO #codessnomed
VALUES ('diabetes-type-ii',1,'190331003',NULL,'Diabetes mellitus, adult onset, with hyperosmolar coma (disorder)'),('diabetes-type-ii',1,'190388001',NULL,'Type II diabetes mellitus with multiple complications (disorder)'),('diabetes-type-ii',1,'190389009',NULL,'Type II diabetes mellitus with ulcer (disorder)'),('diabetes-type-ii',1,'237599002',NULL,'Insulin-treated non-insulin-dependent diabetes mellitus (disorder)'),('diabetes-type-ii',1,'237604008',NULL,'Diabetes mellitus autosomal dominant type II (disorder)'),('diabetes-type-ii',1,'24471000000103',NULL,'Type 2 diabetes on insulin (finding)'),('diabetes-type-ii',1,'24481000000101',NULL,'Type 2 diabetes on diet only (finding)'),('diabetes-type-ii',1,'313436004',NULL,'Type II diabetes mellitus without complication (disorder)'),('diabetes-type-ii',1,'314902007',NULL,'Type II diabetes mellitus with peripheral angiopathy (disorder)'),('diabetes-type-ii',1,'314903002',NULL,'Type II diabetes mellitus with arthropathy (disorder)'),('diabetes-type-ii',1,'314904008',NULL,'Type II diabetes mellitus with neuropathic arthropathy (disorder)'),('diabetes-type-ii',1,'44054006',NULL,'Diabetes mellitus type 2 (disorder)'),('diabetes-type-ii',1,'443694000',NULL,'Type II diabetes mellitus uncontrolled (finding)'),('diabetes-type-ii',1,'190390000',NULL,'Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'1481000119100',NULL,'Diabetes mellitus type 2 without retinopathy'),('diabetes-type-ii',1,'445353002',NULL,'Brittle type II diabetes mellitus')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codessnomed;

IF OBJECT_ID('tempdb..#codesemis') IS NOT NULL DROP TABLE #codesemis;
CREATE TABLE #codesemis (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[term] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesemis
VALUES ('ckd-stage-3',1,'^ESCTAN821240',NULL,'Anaemia co-occurrent and due to chronic kidney disease stage 3'),('ckd-stage-3',1,'^ESCTAN821241',NULL,'Anemia co-occurrent and due to chronic kidney disease stage 3'),('ckd-stage-3',1,'^ESCTCH796669',NULL,'Chronic kidney disease stage 3 due to type 2 diabetes mellitus'),('ckd-stage-3',1,'^ESCTCH796671',NULL,'Chronic kidney disease stage 3 due to type II diabetes mellitus'),('ckd-stage-3',1,'^ESCTCH802745',NULL,'Chronic kidney disease stage 3 due to type 1 diabetes mellitus'),('ckd-stage-3',1,'^ESCTCH802746',NULL,'Chronic kidney disease stage 3 due to type I diabetes mellitus'),('ckd-stage-3',1,'^ESCTCH804068',NULL,'Chronic kidney disease stage 3 due to hypertension'),('ckd-stage-3',1,'^ESCTCH808707',NULL,'Chronic kidney disease stage 3 due to benign hypertension'),('ckd-stage-3',1,'^ESCTCH834588',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A1'),('ckd-stage-3',1,'^ESCTCH834590',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A2'),('ckd-stage-3',1,'^ESCTCH834593',NULL,'Chronic kidney disease with glomerular filtration rate category G3a and albuminuria category A3'),('ckd-stage-3',1,'^ESCTCH834600',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A1'),('ckd-stage-3',1,'^ESCTCH834602',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A2'),('ckd-stage-3',1,'^ESCTCH834604',NULL,'Chronic kidney disease with glomerular filtration rate category G3b and albuminuria category A3'),('ckd-stage-3',1,'^ESCTCK717479',NULL,'CKD stage 3'),('ckd-stage-3',1,'^ESCTCK810423',NULL,'CKD (chronic kidney disease) stage 3 with proteinuria'),('ckd-stage-3',1,'^ESCTCK810426',NULL,'CKD (chronic kidney disease) stage 3 without proteinuria'),('ckd-stage-3',1,'^ESCTCK810430',NULL,'CKD (chronic kidney disease) stage 3A with proteinuria'),('ckd-stage-3',1,'^ESCTCK810435',NULL,'CKD (chronic kidney disease) stage 3A without proteinuria'),('ckd-stage-3',1,'^ESCTCK810438',NULL,'CKD (chronic kidney disease) stage 3B with proteinuria'),('ckd-stage-3',1,'^ESCTCK810441',NULL,'CKD (chronic kidney disease) stage 3B without proteinuria'),('ckd-stage-3',1,'^ESCTDI796670',NULL,'Diabetic stage 3 chronic renal impairment due to type 2 diabetes mellitus'),('ckd-stage-3',1,'^ESCTHY803043',NULL,'Hypertensive heart AND chronic kidney disease stage 3'),('ckd-stage-3',1,'^ESCTHY804406',NULL,'Hypertension in chronic kidney disease stage 3 due to type 2 diabetes mellitus'),('ckd-stage-3',1,'^ESCTHY804407',NULL,'Hypertension in chronic kidney disease stage 3 due to type II diabetes mellitus'),('ckd-stage-3',1,'^ESCTMA808769',NULL,'Malignant hypertensive chronic kidney disease stage 3');
INSERT INTO #codesemis
VALUES ('ckd-stage-4',1,'^ESCTAN821231',NULL,'Anaemia in chronic kidney disease stage 4'),('ckd-stage-4',1,'^ESCTAN821232',NULL,'Anemia co-occurrent and due to chronic kidney disease stage 4'),('ckd-stage-4',1,'^ESCTAN821233',NULL,'Anemia in chronic kidney disease stage 4'),('ckd-stage-4',1,'^ESCTAN821234',NULL,'Anaemia co-occurrent and due to chronic kidney disease stage 4'),('ckd-stage-4',1,'^ESCTCH796664',NULL,'Chronic kidney disease stage 4 due to type 2 diabetes mellitus'),('ckd-stage-4',1,'^ESCTCH796666',NULL,'Chronic kidney disease stage 4 due to type II diabetes mellitus'),('ckd-stage-4',1,'^ESCTCH802747',NULL,'Chronic kidney disease stage 4 due to type 1 diabetes mellitus'),('ckd-stage-4',1,'^ESCTCH802748',NULL,'Chronic kidney disease stage 4 due to type I diabetes mellitus'),('ckd-stage-4',1,'^ESCTCH804066',NULL,'Chronic kidney disease stage 4 due to hypertension'),('ckd-stage-4',1,'^ESCTCH808708',NULL,'Chronic kidney disease stage 4 due to benign hypertension'),('ckd-stage-4',1,'^ESCTCH834610',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A1'),('ckd-stage-4',1,'^ESCTCH834612',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A2'),('ckd-stage-4',1,'^ESCTCH834615',NULL,'Chronic kidney disease with glomerular filtration rate category G4 and albuminuria category A3'),('ckd-stage-4',1,'^ESCTCK714778',NULL,'CKD stage 4'),('ckd-stage-4',1,'^ESCTCK810445',NULL,'CKD (chronic kidney disease) stage 4 with proteinuria'),('ckd-stage-4',1,'^ESCTCK810448',NULL,'CKD (chronic kidney disease) stage 4 without proteinuria'),('ckd-stage-4',1,'^ESCTDI796665',NULL,'Diabetic stage 4 chronic renal impairment due to type 2 diabetes mellitus'),('ckd-stage-4',1,'^ESCTHY803042',NULL,'Hypertensive heart AND chronic kidney disease stage 4'),('ckd-stage-4',1,'^ESCTHY804404',NULL,'Hypertension in chronic kidney disease stage 4 due to type 2 diabetes mellitus'),('ckd-stage-4',1,'^ESCTHY804405',NULL,'Hypertension in chronic kidney disease stage 4 due to type II diabetes mellitus'),('ckd-stage-4',1,'^ESCTMA808770',NULL,'Malignant hypertensive chronic kidney disease stage 4');
INSERT INTO #codesemis
VALUES ('ckd-stage-5',1,'^ESCT1192455',NULL,'End-stage renal disease'),('ckd-stage-5',1,'^ESCT1270447',NULL,'End-stage renal disease'),('ckd-stage-5',1,'^ESCT1371635',NULL,'Dependence on continuous ambulatory peritoneal dialysis due to end stage renal disease'),('ckd-stage-5',1,'^ESCTAN761537',NULL,'Anaemia in end stage renal disease'),('ckd-stage-5',1,'^ESCTAN761538',NULL,'Anemia in end stage renal disease'),('ckd-stage-5',1,'^ESCTAN761539',NULL,'Anemia co-occurrent and due to end stage renal disease'),('ckd-stage-5',1,'^ESCTAN761540',NULL,'Anaemia co-occurrent and due to end stage renal disease'),('ckd-stage-5',1,'^ESCTAN821236',NULL,'Anaemia in chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTAN821237',NULL,'Anemia co-occurrent and due to chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTAN821238',NULL,'Anaemia co-occurrent and due to chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTAN821239',NULL,'Anemia in chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTCH771489',NULL,'Chronic kidney disease stage 5 on dialysis'),('ckd-stage-5',1,'^ESCTCH771490',NULL,'Chronic kidney disease 5d'),('ckd-stage-5',1,'^ESCTCH771492',NULL,'Chronic kidney disease stage 5 with transplant'),('ckd-stage-5',1,'^ESCTCH771493',NULL,'Chronic kidney disease 5t'),('ckd-stage-5',1,'^ESCTCH796661',NULL,'Chronic kidney disease stage 5 due to type 2 diabetes mellitus'),('ckd-stage-5',1,'^ESCTCH796663',NULL,'Chronic kidney disease stage 5 due to type II diabetes mellitus'),('ckd-stage-5',1,'^ESCTCH802749',NULL,'Chronic kidney disease stage 5 due to type 1 diabetes mellitus'),('ckd-stage-5',1,'^ESCTCH802750',NULL,'Chronic kidney disease stage 5 due to type I diabetes mellitus'),('ckd-stage-5',1,'^ESCTCH804067',NULL,'Chronic kidney disease stage 5 due to hypertension'),('ckd-stage-5',1,'^ESCTCH808709',NULL,'Chronic kidney disease stage 5 due to benign hypertension'),('ckd-stage-5',1,'^ESCTCH834617',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A1'),('ckd-stage-5',1,'^ESCTCH834620',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A2'),('ckd-stage-5',1,'^ESCTCH834622',NULL,'Chronic kidney disease with glomerular filtration rate category G5 and albuminuria category A3'),('ckd-stage-5',1,'^ESCTCK717485',NULL,'CKD stage 5'),('ckd-stage-5',1,'^ESCTCK771491',NULL,'CKD (chronic kidney disease) stage 5d'),('ckd-stage-5',1,'^ESCTCK771494',NULL,'CKD (chronic kidney disease) stage 5t'),('ckd-stage-5',1,'^ESCTCK810451',NULL,'CKD (chronic kidney disease) stage 5 with proteinuria'),('ckd-stage-5',1,'^ESCTCK810455',NULL,'CKD (chronic kidney disease) stage 5 without proteinuria'),('ckd-stage-5',1,'^ESCTDE709585',NULL,'Dependence on peritoneal dialysis due to end stage renal disease'),('ckd-stage-5',1,'^ESCTDE709652',NULL,'Dependence on haemodialysis due to end stage renal disease'),('ckd-stage-5',1,'^ESCTDE709653',NULL,'Dependence on hemodialysis due to end stage renal disease'),('ckd-stage-5',1,'^ESCTDE709794',NULL,'Dependence on dialysis due to end stage renal disease'),('ckd-stage-5',1,'^ESCTDI796662',NULL,'Diabetic stage 5 chronic renal impairment due to type 2 diabetes mellitus'),('ckd-stage-5',1,'^ESCTEN324584',NULL,'End stage kidney disease'),('ckd-stage-5',1,'^ESCTEN324588',NULL,'End stage chronic renal failure'),('ckd-stage-5',1,'^ESCTEN509415',NULL,'End stage renal failure untreated by renal replacement therapy'),('ckd-stage-5',1,'^ESCTEN509416',NULL,'End stage renal failure on dialysis'),('ckd-stage-5',1,'^ESCTEN509417',NULL,'End stage renal failure with renal transplant'),('ckd-stage-5',1,'^ESCTEN769149',NULL,'End stage renal disease due to benign hypertension'),('ckd-stage-5',1,'^ESCTEN803525',NULL,'End stage renal disease due to hypertension'),('ckd-stage-5',1,'^ESCTEN804800',NULL,'End stage renal disease on dialysis due to hypertension'),('ckd-stage-5',1,'^ESCTES324585',NULL,'ESRF - End stage renal failure'),('ckd-stage-5',1,'^ESCTES324586',NULL,'ESCRF - End stage chronic renal failure'),('ckd-stage-5',1,'^ESCTES324587',NULL,'ESRD - End stage renal disease'),('ckd-stage-5',1,'^ESCTES769150',NULL,'ESRD (End stage renal disease) due to benign hypertension'),('ckd-stage-5',1,'^ESCTES803526',NULL,'ESRD (End stage renal disease) due to hypertension'),('ckd-stage-5',1,'^ESCTHY803041',NULL,'Hypertensive heart AND chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTHY804401',NULL,'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus'),('ckd-stage-5',1,'^ESCTHY804402',NULL,'Hypertension in chronic kidney disease stage 5 due to type II diabetes mellitus'),('ckd-stage-5',1,'^ESCTMA804797',NULL,'Malignant hypertensive chronic kidney disease stage 5'),('ckd-stage-5',1,'^ESCTMA808765',NULL,'Malignant hypertensive end stage renal disease'),('ckd-stage-5',1,'^ESCTMA808813',NULL,'Malignant hypertensive end stage renal disease on dialysis')

INSERT INTO #AllCodes
SELECT [concept], [version], [code], [description] from #codesemis;


IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, version INT NOT NULL, [description] VARCHAR(255));

-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.concept, dcr.[version], dcr.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
AND (dcr.term IS NULL OR dcr.term = rc.Term)
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.concept, dcc.[version], dcc.[description]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

-- EMIS codes with a FK Reference Coding ID
INSERT INTO #TempRefCodes
SELECT FK_Reference_Coding_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [version] INT NOT NULL, [description] VARCHAR(255));

-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.concept, dcs.[version], dcs.[description]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- EMIS codes with a FK SNOMED ID but without a FK Reference Coding ID
INSERT INTO #TempSNOMEDRefCodes
SELECT FK_Reference_SnomedCT_ID, ce.concept, ce.[version], ce.[description]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID = -1
AND FK_Reference_SnomedCT_ID != -1;

-- De-duped tables
IF OBJECT_ID('tempdb..#CodeSets') IS NOT NULL DROP TABLE #CodeSets;
CREATE TABLE #CodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#SnomedSets') IS NOT NULL DROP TABLE #SnomedSets;
CREATE TABLE #SnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedCodeSets') IS NOT NULL DROP TABLE #VersionedCodeSets;
CREATE TABLE #VersionedCodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

IF OBJECT_ID('tempdb..#VersionedSnomedSets') IS NOT NULL DROP TABLE #VersionedSnomedSets;
CREATE TABLE #VersionedSnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT, [description] VARCHAR(255));

INSERT INTO #VersionedCodeSets
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #VersionedSnomedSets
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

INSERT INTO #CodeSets
SELECT FK_Reference_Coding_ID, c.concept, [description]
FROM #VersionedCodeSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedCodeSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

INSERT INTO #SnomedSets
SELECT FK_Reference_SnomedCT_ID, c.concept, [description]
FROM #VersionedSnomedSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedSnomedSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

--#endregion

-- >>> Following code sets injected: diabetes-type-ii v1
IF OBJECT_ID('tempdb..#PatientT2Dtemppart1') IS NOT NULL DROP TABLE #PatientT2Dtemppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientT2Dtemppart1
FROM SharedCare.GP_Events
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'diabetes-type-ii' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientT2Dtemppart2') IS NOT NULL DROP TABLE #PatientT2Dtemppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientT2Dtemppart2
FROM SharedCare.GP_Events
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'diabetes-type-ii' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientT2D') IS NOT NULL DROP TABLE #PatientT2D;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientT2D
FROM #PatientT2Dtemppart1 p1
FULL JOIN #PatientT2Dtemppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID


-- For improved performance let's get all the events and medications for patients with T2D
TRUNCATE TABLE #Patients
INSERT INTO #Patients
SELECT FK_Patient_Link_ID FROM #PatientT2D;


-- Now we create a table of events for all the people in our cohort.
-- We do this for Ref_Coding_ID and SNOMED_ID separately for performance reasons.
-- 1. Patients with a FK_Reference_Coding_ID
IF OBJECT_ID('tempdb..#PatientEventData1') IS NOT NULL DROP TABLE #PatientEventData1;
SELECT 
  FK_Patient_Link_ID,
  CAST(EventDate AS DATE) AS EventDate,
  CASE WHEN ISNUMERIC([Value]) = 1 THEN CAST([Value] AS float) ELSE NULL END AS [Value],
  Units,
  SuppliedCode,
  FK_Reference_SnomedCT_ID,
  FK_Reference_Coding_ID
INTO #PatientEventData1
FROM [SharedCare].GP_Events
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients);
--23s

-- 2. Patients with a FK_Reference_SnomedCT_ID
IF OBJECT_ID('tempdb..#PatientEventData2') IS NOT NULL DROP TABLE #PatientEventData2;
SELECT 
  FK_Patient_Link_ID,
  CAST(EventDate AS DATE) AS EventDate,
  CASE WHEN ISNUMERIC([Value]) = 1 THEN CAST([Value] AS float) ELSE NULL END AS [Value],
  Units,
  SuppliedCode,
  FK_Reference_SnomedCT_ID,
  FK_Reference_Coding_ID
INTO #PatientEventData2
FROM [SharedCare].GP_Events
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients);
--23s

-- 3. Merge the 2 tables together
IF OBJECT_ID('tempdb..#PatientEventData') IS NOT NULL DROP TABLE #PatientEventData;
SELECT * INTO #PatientEventData FROM #PatientEventData1
UNION
SELECT * FROM #PatientEventData2;
--6s

-- 4. Add indexes for future speed increase
DROP INDEX IF EXISTS eventFKData1 ON #PatientEventData;
CREATE INDEX eventFKData1 ON #PatientEventData (FK_Reference_Coding_ID) INCLUDE (FK_Patient_Link_ID, EventDate, [Value], Units);
DROP INDEX IF EXISTS eventFKData2 ON #PatientEventData;
CREATE INDEX eventFKData2 ON #PatientEventData (FK_Reference_SnomedCT_ID) INCLUDE (FK_Patient_Link_ID, EventDate, [Value], Units);
DROP INDEX IF EXISTS eventFKData3 ON #PatientEventData;
CREATE INDEX eventFKData3 ON #PatientEventData (SuppliedCode) INCLUDE (FK_Patient_Link_ID, EventDate, [Value], Units);
--5s for both

-- Now we create a table of medications for all the people in our cohort.
-- Just using SuppliedCode
-- 1. Patients with a FK_Reference_Coding_ID
IF OBJECT_ID('tempdb..#PatientMedicationData') IS NOT NULL DROP TABLE #PatientMedicationData;
SELECT 
  FK_Patient_Link_ID,
  CAST(MedicationDate AS DATE) AS MedicationDate,
  SuppliedCode
INTO #PatientMedicationData
FROM [SharedCare].GP_Medications
WHERE SuppliedCode IN (SELECT [Code] FROM #AllCodes)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients);
--31s

-- 4. Add indexes for future speed increase
DROP INDEX IF EXISTS medicationData1 ON #PatientMedicationData;
CREATE INDEX medicationData1 ON #PatientMedicationData (SuppliedCode) INCLUDE (FK_Patient_Link_ID, MedicationDate);
--15s

-- Get first CKD stage 3 diagnosis date

-- >>> Following code sets injected: ckd-stage-3 v1
IF OBJECT_ID('tempdb..#PatientCKD3temppart1') IS NOT NULL DROP TABLE #PatientCKD3temppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD3temppart1
FROM #PatientEventData
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'ckd-stage-3' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD3temppart2') IS NOT NULL DROP TABLE #PatientCKD3temppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD3temppart2
FROM #PatientEventData
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'ckd-stage-3' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD3') IS NOT NULL DROP TABLE #PatientCKD3;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientCKD3
FROM #PatientCKD3temppart1 p1
FULL JOIN #PatientCKD3temppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID

-- Get first CKD stage 4 diagnosis date

-- >>> Following code sets injected: ckd-stage-4 v1
IF OBJECT_ID('tempdb..#PatientCKD4temppart1') IS NOT NULL DROP TABLE #PatientCKD4temppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD4temppart1
FROM #PatientEventData
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'ckd-stage-4' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD4temppart2') IS NOT NULL DROP TABLE #PatientCKD4temppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD4temppart2
FROM #PatientEventData
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'ckd-stage-4' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD4') IS NOT NULL DROP TABLE #PatientCKD4;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientCKD4
FROM #PatientCKD4temppart1 p1
FULL JOIN #PatientCKD4temppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID

-- Get first CKD stage 5 diagnosis date

-- >>> Following code sets injected: ckd-stage-5 v1
IF OBJECT_ID('tempdb..#PatientCKD5temppart1') IS NOT NULL DROP TABLE #PatientCKD5temppart1;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD5temppart1
FROM #PatientEventData
WHERE FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept = 'ckd-stage-5' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD5temppart2') IS NOT NULL DROP TABLE #PatientCKD5temppart2;
SELECT FK_Patient_Link_ID, MIN(EventDate) AS DateOfFirstDiagnosis
INTO #PatientCKD5temppart2
FROM #PatientEventData
WHERE FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept = 'ckd-stage-5' AND Version = 1)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#PatientCKD5') IS NOT NULL DROP TABLE #PatientCKD5;
SELECT
	CASE WHEN p1.FK_Patient_Link_ID IS NULL THEN p2.FK_Patient_Link_ID ELSE p1.FK_Patient_Link_ID END AS FK_Patient_Link_ID,
	CASE
		WHEN p1.DateOfFirstDiagnosis IS NULL THEN p2.DateOfFirstDiagnosis
		WHEN p2.DateOfFirstDiagnosis IS NULL THEN p1.DateOfFirstDiagnosis
		WHEN p1.DateOfFirstDiagnosis < p2.DateOfFirstDiagnosis THEN p1.DateOfFirstDiagnosis
		ELSE p2.DateOfFirstDiagnosis
	END AS DateOfFirstDiagnosis
INTO #PatientCKD5
FROM #PatientCKD5temppart1 p1
FULL JOIN #PatientCKD5temppart2 p2 on p1.FK_Patient_Link_ID = p2.FK_Patient_Link_ID


-- Combine the 3 CKD stages into a single table
IF OBJECT_ID('tempdb..#PatientCKDAll') IS NOT NULL DROP TABLE #PatientCKDAll;
SELECT FK_Patient_Link_ID, DateOfFirstDiagnosis 
INTO #PatientCKDAll
FROM #PatientCKD3
UNION
SELECT * FROM #PatientCKD4
UNION
SELECT * FROM #PatientCKD5;

-- Then find the earliest diagnosis date for each patient
IF OBJECT_ID('tempdb..#PatientCKD') IS NOT NULL DROP TABLE #PatientCKD;
SELECT FK_Patient_Link_ID, MIN(DateOfFirstDiagnosis) AS DateOfFirstDiagnosis
INTO #PatientCKD
FROM #PatientCKDAll
GROUP BY FK_Patient_Link_ID;

IF OBJECT_ID('tempdb..#Cohort') IS NOT NULL DROP TABLE #Cohort;
SELECT 
	t2d.FK_Patient_Link_ID,
	YEAR(t2d.DateOfFirstDiagnosis) AS FirstT2dDiagnosisYear,
	MONTH(t2d.DateOfFirstDiagnosis) AS FirstT2dDiagnosisMonth, 
	YEAR(ckd.DateOfFirstDiagnosis) AS FirstCkdDiagnosisYear,
	MONTH(ckd.DateOfFirstDiagnosis) AS FirstCkdDiagnosisMonth,
  DeathDate
INTO #Cohort
FROM #PatientT2D t2d
LEFT OUTER JOIN #PatientCKD ckd ON t2d.FK_Patient_Link_ID = ckd.FK_Patient_Link_ID
LEFT OUTER JOIN SharedCare.Patient_Link pl ON pl.PK_Patient_Link_ID = t2d.FK_Patient_Link_ID
WHERE t2d.DateOfFirstDiagnosis < '2023-09-19'
AND (DeathDate IS NULL OR DeathDate > DATEADD(month, -30, '2023-09-19'))
AND (ckd.DateOfFirstDiagnosis IS NULL OR ckd.DateOfFirstDiagnosis > DATEADD(month, -30, '2023-09-19'));

TRUNCATE TABLE #Patients
INSERT INTO #Patients
SELECT FK_Patient_Link_ID FROM #Cohort;




SELECT
  FK_Patient_Link_ID AS PatientId,
  StartDate,
  EndDate,
  GPPracticeCode
FROM SharedCare.Patient_GP_History
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND FK_Reference_Tenancy_ID = 2
ORDER BY FK_Patient_Link_ID, StartDate;