--┌───────────────────────────────────┐
--│ Summary of death counts per month │
--└───────────────────────────────────┘

------------------------ RDE CHECK -------------------------
-- RDE NAME: ___, DATE OF CHECK: ___ -------
------------------------------------------------------------

-- Cohort is diabetic patients with a positive covid test. Also a 1:5 matched cohort, 
-- matched on year of birth (+-5 years), sex, and date of positive covid test (+-14 days).
-- For each we provide the following:

-- Table with the following columns:
--  - Year
--  - Month
--  - T1Population  - Number of T1DM patients in GM alive at the start of the month
--  - T1Deaths  - Number of T1DM patients in GM dying during the month
--  - T2Population  - Number of T2DM patients in GM alive at the start of the month
--  - T2Deaths  - Number of T2DM patients in GM dying during the month
--  - TotalPopulation  - Number of patients in GM alive at the start of the month
--  - TotalDeaths  - Number of patients in GM dying during the month

--Just want the output, not the messages
SET NOCOUNT ON;

-- Set the start date
DECLARE @StartDate datetime;
SET @StartDate = '2019-01-01';

-- Get all patients with T1DM and the first diagnosis date
-- >>> Codesets required... Inserting the code set code
--
--┌────────────────────┐
--│ Clinical code sets │
--└────────────────────┘

-- OBJECTIVE: To populate temporary tables with the existing clinical code sets.
--            See the [SQL-generation-process.md](SQL-generation-process.md) for more details.

-- INPUT: No pre-requisites

-- OUTPUT: Five temp tables as follows:
--  #AllCodes (Concept, Version, Code)
--  #CodeSets (FK_Reference_Coding_ID, Concept)
--  #SnomedSets (FK_Reference_SnomedCT_ID, FK_SNOMED_ID)
--  #VersionedCodeSets (FK_Reference_Coding_ID, Concept, Version)
--  #VersionedSnomedSets (FK_Reference_SnomedCT_ID, Version, FK_SNOMED_ID)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

IF OBJECT_ID('tempdb..#AllCodes') IS NOT NULL DROP TABLE #AllCodes;
CREATE TABLE #AllCodes (
  [Concept] [varchar](255) NOT NULL,
  [Version] INT NOT NULL,
  [Code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL
);

IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('diabetes-type-i',1,'C100000','Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes-type-i',1,'C1000','Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes-type-i',1,'C100011','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C1000','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C101000','Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes-type-i',1,'C1010','Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes-type-i',1,'C102000','Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes-type-i',1,'C1020','Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes-type-i',1,'C103000','Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes-type-i',1,'C1030','Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes-type-i',1,'C104000','Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes-type-i',1,'C1040','Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes-type-i',1,'C105000','Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes-type-i',1,'C1050','Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes-type-i',1,'C106000','Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes-type-i',1,'C1060','Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes-type-i',1,'C107000','Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes-type-i',1,'C1070','Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes-type-i',1,'C108.00','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C108.','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C108.11','IDDM-Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C108.','IDDM-Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C108.12','Type 1 diabetes mellitus'),('diabetes-type-i',1,'C108.','Type 1 diabetes mellitus'),('diabetes-type-i',1,'C108.13','Type I diabetes mellitus'),('diabetes-type-i',1,'C108.','Type I diabetes mellitus'),('diabetes-type-i',1,'C108000','Insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-i',1,'C1080','Insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-i',1,'C108011','Type I diabetes mellitus with renal complications'),('diabetes-type-i',1,'C1080','Type I diabetes mellitus with renal complications'),('diabetes-type-i',1,'C108012','Type 1 diabetes mellitus with renal complications'),('diabetes-type-i',1,'C1080','Type 1 diabetes mellitus with renal complications'),('diabetes-type-i',1,'C108100','Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C1081','Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C108111','Type I diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C1081','Type I diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C108112','Type 1 diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C1081','Type 1 diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C108200','Insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C1082','Insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C108211','Type I diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C1082','Type I diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C108212','Type 1 diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C1082','Type 1 diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C108300','Insulin dependent diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C1083','Insulin dependent diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C108311','Type I diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C1083','Type I diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C108312','Type 1 diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C1083','Type 1 diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C108400','Unstable insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C1084','Unstable insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C108411','Unstable type I diabetes mellitus'),('diabetes-type-i',1,'C1084','Unstable type I diabetes mellitus'),('diabetes-type-i',1,'C108412','Unstable type 1 diabetes mellitus'),('diabetes-type-i',1,'C1084','Unstable type 1 diabetes mellitus'),('diabetes-type-i',1,'C108500','Insulin dependent diabetes mellitus with ulcer'),('diabetes-type-i',1,'C1085','Insulin dependent diabetes mellitus with ulcer'),('diabetes-type-i',1,'C108511','Type I diabetes mellitus with ulcer'),('diabetes-type-i',1,'C1085','Type I diabetes mellitus with ulcer'),('diabetes-type-i',1,'C108512','Type 1 diabetes mellitus with ulcer'),('diabetes-type-i',1,'C1085','Type 1 diabetes mellitus with ulcer'),('diabetes-type-i',1,'C108600','Insulin dependent diabetes mellitus with gangrene'),('diabetes-type-i',1,'C1086','Insulin dependent diabetes mellitus with gangrene'),('diabetes-type-i',1,'C108611','Type I diabetes mellitus with gangrene'),('diabetes-type-i',1,'C1086','Type I diabetes mellitus with gangrene'),('diabetes-type-i',1,'C108612','Type 1 diabetes mellitus with gangrene'),('diabetes-type-i',1,'C1086','Type 1 diabetes mellitus with gangrene'),('diabetes-type-i',1,'C108700','Insulin dependent diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C1087','Insulin dependent diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C108711','Type I diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C1087','Type I diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C108712','Type 1 diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C1087','Type 1 diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C108800','Insulin dependent diabetes mellitus - poor control'),('diabetes-type-i',1,'C1088','Insulin dependent diabetes mellitus - poor control'),('diabetes-type-i',1,'C108811','Type I diabetes mellitus - poor control'),('diabetes-type-i',1,'C1088','Type I diabetes mellitus - poor control'),('diabetes-type-i',1,'C108812','Type 1 diabetes mellitus - poor control'),('diabetes-type-i',1,'C1088','Type 1 diabetes mellitus - poor control'),('diabetes-type-i',1,'C108900','Insulin dependent diabetes maturity onset'),('diabetes-type-i',1,'C1089','Insulin dependent diabetes maturity onset'),('diabetes-type-i',1,'C108911','Type I diabetes mellitus maturity onset'),('diabetes-type-i',1,'C1089','Type I diabetes mellitus maturity onset'),('diabetes-type-i',1,'C108912','Type 1 diabetes mellitus maturity onset'),('diabetes-type-i',1,'C1089','Type 1 diabetes mellitus maturity onset'),('diabetes-type-i',1,'C108A00','Insulin-dependent diabetes without complication'),('diabetes-type-i',1,'C108A','Insulin-dependent diabetes without complication'),('diabetes-type-i',1,'C108A11','Type I diabetes mellitus without complication'),('diabetes-type-i',1,'C108A','Type I diabetes mellitus without complication'),('diabetes-type-i',1,'C108A12','Type 1 diabetes mellitus without complication'),('diabetes-type-i',1,'C108A','Type 1 diabetes mellitus without complication'),('diabetes-type-i',1,'C108B00','Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108B','Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108B11','Type I diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108B','Type I diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108B12','Type 1 diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108B','Type 1 diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C108C00','Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108C','Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108C11','Type I diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108C','Type I diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108C12','Type 1 diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108C','Type 1 diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C108D00','Insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108D','Insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108D11','Type I diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108D','Type I diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108D12','Type 1 diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108D','Type 1 diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C108E00','Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108E','Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108E11','Type I diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108E','Type I diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108E12','Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108E','Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C108F00','Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C108F','Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C108F11','Type I diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C108F','Type I diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C108F12','Type 1 diabetes mellitus with diabetic cataract'),
('diabetes-type-i',1,'C108F','Type 1 diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C108G00','Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108G','Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108G11','Type I diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108G','Type I diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108G12','Type 1 diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108G','Type 1 diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C108H00','Insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108H','Insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108H11','Type I diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108H','Type I diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108H12','Type 1 diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108H','Type 1 diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C108J00','Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C108J','Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C108J11','Type I diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C108J','Type I diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C108J12','Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C108J','Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10E.00','Type 1 diabetes mellitus'),('diabetes-type-i',1,'C10E.','Type 1 diabetes mellitus'),('diabetes-type-i',1,'C10E.11','Type I diabetes mellitus'),('diabetes-type-i',1,'C10E.','Type I diabetes mellitus'),('diabetes-type-i',1,'C10E.12','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C10E.','Insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C10E000','Type 1 diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E0','Type 1 diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E011','Type I diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E0','Type I diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E012','Insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E0','Insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-i',1,'C10E100','Type 1 diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E1','Type 1 diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E111','Type I diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E1','Type I diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E112','Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E1','Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C10E200','Type 1 diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E2','Type 1 diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E211','Type I diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E2','Type I diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E212','Insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E2','Insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C10E300','Type 1 diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E3','Type 1 diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E311','Type I diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E3','Type I diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E312','Insulin dependent diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E3','Insulin dependent diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C10E400','Unstable type 1 diabetes mellitus'),('diabetes-type-i',1,'C10E4','Unstable type 1 diabetes mellitus'),('diabetes-type-i',1,'C10E411','Unstable type I diabetes mellitus'),('diabetes-type-i',1,'C10E4','Unstable type I diabetes mellitus'),('diabetes-type-i',1,'C10E412','Unstable insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C10E4','Unstable insulin dependent diabetes mellitus'),('diabetes-type-i',1,'C10E500','Type 1 diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E5','Type 1 diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E511','Type I diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E5','Type I diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E512','Insulin dependent diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E5','Insulin dependent diabetes mellitus with ulcer'),('diabetes-type-i',1,'C10E600','Type 1 diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E6','Type 1 diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E611','Type I diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E6','Type I diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E612','Insulin dependent diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E6','Insulin dependent diabetes mellitus with gangrene'),('diabetes-type-i',1,'C10E700','Type 1 diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E7','Type 1 diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E711','Type I diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E7','Type I diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E712','Insulin dependent diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E7','Insulin dependent diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C10E800','Type 1 diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E8','Type 1 diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E811','Type I diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E8','Type I diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E812','Insulin dependent diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E8','Insulin dependent diabetes mellitus - poor control'),('diabetes-type-i',1,'C10E900','Type 1 diabetes mellitus maturity onset'),('diabetes-type-i',1,'C10E9','Type 1 diabetes mellitus maturity onset'),('diabetes-type-i',1,'C10E911','Type I diabetes mellitus maturity onset'),('diabetes-type-i',1,'C10E9','Type I diabetes mellitus maturity onset'),('diabetes-type-i',1,'C10E912','Insulin dependent diabetes maturity onset'),('diabetes-type-i',1,'C10E9','Insulin dependent diabetes maturity onset'),('diabetes-type-i',1,'C10EA00','Type 1 diabetes mellitus without complication'),('diabetes-type-i',1,'C10EA','Type 1 diabetes mellitus without complication'),('diabetes-type-i',1,'C10EA11','Type I diabetes mellitus without complication'),('diabetes-type-i',1,'C10EA','Type I diabetes mellitus without complication'),('diabetes-type-i',1,'C10EA12','Insulin-dependent diabetes without complication'),('diabetes-type-i',1,'C10EA','Insulin-dependent diabetes without complication'),('diabetes-type-i',1,'C10EB00','Type 1 diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EB','Type 1 diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EB11','Type I diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EB','Type I diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EB12','Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EB','Insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'C10EC00','Type 1 diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10EC','Type 1 diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10EC11','Type I diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10EC','Type I diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10EC12','Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10EC','Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'C10ED00','Type 1 diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10ED','Type 1 diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10ED11','Type I diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10ED','Type I diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10ED12','Insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10ED','Insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-i',1,'C10EE00','Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EE','Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EE11','Type I diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EE','Type I diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EE12','Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EE','Insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'C10EF00','Type 1 diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EF','Type 1 diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EF11','Type I diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EF','Type I diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EF12','Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EF','Insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'C10EG00','Type 1 diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C10EG','Type 1 diabetes mellitus with peripheral angiopathy'),
('diabetes-type-i',1,'C10EG11','Type I diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C10EG','Type I diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C10EG12','Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C10EG','Insulin dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'C10EH00','Type 1 diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EH','Type 1 diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EH11','Type I diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EH','Type I diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EH12','Insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EH','Insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-i',1,'C10EJ00','Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EJ','Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EJ11','Type I diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EJ','Type I diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EJ12','Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EJ','Insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'C10EK00','Type 1 diabetes mellitus with persistent proteinuria'),('diabetes-type-i',1,'C10EK','Type 1 diabetes mellitus with persistent proteinuria'),('diabetes-type-i',1,'C10EK11','Type I diabetes mellitus with persistent proteinuria'),('diabetes-type-i',1,'C10EK','Type I diabetes mellitus with persistent proteinuria'),('diabetes-type-i',1,'C10EL00','Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-i',1,'C10EL','Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-i',1,'C10EL11','Type I diabetes mellitus with persistent microalbuminuria'),('diabetes-type-i',1,'C10EL','Type I diabetes mellitus with persistent microalbuminuria'),('diabetes-type-i',1,'C10EM00','Type 1 diabetes mellitus with ketoacidosis'),('diabetes-type-i',1,'C10EM','Type 1 diabetes mellitus with ketoacidosis'),('diabetes-type-i',1,'C10EM11','Type I diabetes mellitus with ketoacidosis'),('diabetes-type-i',1,'C10EM','Type I diabetes mellitus with ketoacidosis'),('diabetes-type-i',1,'C10EN00','Type 1 diabetes mellitus with ketoacidotic coma'),('diabetes-type-i',1,'C10EN','Type 1 diabetes mellitus with ketoacidotic coma'),('diabetes-type-i',1,'C10EN11','Type I diabetes mellitus with ketoacidotic coma'),('diabetes-type-i',1,'C10EN','Type I diabetes mellitus with ketoacidotic coma'),('diabetes-type-i',1,'C10EP00','Type 1 diabetes mellitus with exudative maculopathy'),('diabetes-type-i',1,'C10EP','Type 1 diabetes mellitus with exudative maculopathy'),('diabetes-type-i',1,'C10EP11','Type I diabetes mellitus with exudative maculopathy'),('diabetes-type-i',1,'C10EP','Type I diabetes mellitus with exudative maculopathy'),('diabetes-type-i',1,'C10EQ00','Type 1 diabetes mellitus with gastroparesis'),('diabetes-type-i',1,'C10EQ','Type 1 diabetes mellitus with gastroparesis'),('diabetes-type-i',1,'C10EQ11','Type I diabetes mellitus with gastroparesis'),('diabetes-type-i',1,'C10EQ','Type I diabetes mellitus with gastroparesis'),('diabetes-type-i',1,'C10y000','Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes-type-i',1,'C10y0','Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes-type-i',1,'C10z000','Diabetes mellitus, juvenile type, with unspecified complication'),('diabetes-type-i',1,'C10z0','Diabetes mellitus, juvenile type, with unspecified complication');
INSERT INTO #codesreadv2
VALUES ('diabetes-type-ii',1,'C100100','Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C1001','Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'C100112','Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C1001','Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C101100','Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1011','Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C102100','Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1021','Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C103100','Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1031','Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C104100','Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1041','Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C105100','Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1051','Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C106100','Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1061','Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C107100','Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C1071','Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C109.00','Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.','Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.11','NIDDM - Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.','NIDDM - Non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109.12','Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109.','Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109.13','Type II diabetes mellitus'),('diabetes-type-ii',1,'C109.','Type II diabetes mellitus'),('diabetes-type-ii',1,'C109000','Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1090','Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C109011','Type II diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1090','Type II diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C109012','Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1090','Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C109100','Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1091','Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C109111','Type II diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1091','Type II diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C109112','Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1091','Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C109200','Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1092','Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C109211','Type II diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1092','Type II diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C109212','Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1092','Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C109300','Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1093','Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C109311','Type II diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1093','Type II diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C109312','Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1093','Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C109400','Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1094','Non-insulin dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C109411','Type II diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1094','Type II diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C109412','Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1094','Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C109500','Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1095','Non-insulin dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C109511','Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1095','Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C109512','Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1095','Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C109600','Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1096','Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C109611','Type II diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1096','Type II diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C109612','Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1096','Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C109700','Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C1097','Non-insulin dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C109711','Type II diabetes mellitus - poor control'),('diabetes-type-ii',1,'C1097','Type II diabetes mellitus - poor control'),('diabetes-type-ii',1,'C109712','Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C1097','Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C109900','Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C1099','Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'C109911','Type II diabetes mellitus without complication'),('diabetes-type-ii',1,'C1099','Type II diabetes mellitus without complication'),('diabetes-type-ii',1,'C109912','Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C1099','Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C109A00','Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A','Non-insulin dependent diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A11','Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A','Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A12','Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109A','Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C109B00','Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B','Non-insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B11','Type II diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B','Type II diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B12','Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109B','Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C109C00','Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C','Non-insulin dependent diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C11','Type II diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C','Type II diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C12','Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109C','Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C109D00','Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D','Non-insulin dependent diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D11','Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D','Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D12','Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109D','Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C109E00','Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E','Non-insulin dependent diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E11','Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E','Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E12','Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109E','Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C109F00','Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F','Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F11','Type II diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F','Type II diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F12','Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C109F','Type 2 diabetes mellitus with peripheral angiopathy'),
('diabetes-type-ii',1,'C109G00','Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G','Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G11','Type II diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G','Type II diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G12','Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109G','Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C109H00','Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H','Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H11','Type II diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H','Type II diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H12','Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109H','Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C109J00','Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109J','Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109J11','Insulin treated non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109J','Insulin treated non-insulin dependent diabetes mellitus'),('diabetes-type-ii',1,'C109J12','Insulin treated Type II diabetes mellitus'),('diabetes-type-ii',1,'C109J','Insulin treated Type II diabetes mellitus'),('diabetes-type-ii',1,'C109K00','Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C109K','Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10D.00','Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10D.','Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'C10F.00','Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F.','Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10F.11','Type II diabetes mellitus'),('diabetes-type-ii',1,'C10F.','Type II diabetes mellitus'),('diabetes-type-ii',1,'C10F000','Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F0','Type 2 diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F011','Type II diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F0','Type II diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C10F100','Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F1','Type 2 diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F111','Type II diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F1','Type II diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C10F200','Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F2','Type 2 diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F211','Type II diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F2','Type II diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C10F300','Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F3','Type 2 diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F311','Type II diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F3','Type II diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C10F400','Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F4','Type 2 diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F411','Type II diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F4','Type II diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C10F500','Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F5','Type 2 diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F511','Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F5','Type II diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C10F600','Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F6','Type 2 diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F611','Type II diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F6','Type II diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C10F700','Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F7','Type 2 diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F711','Type II diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F7','Type II diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10F900','Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10F9','Type 2 diabetes mellitus without complication'),('diabetes-type-ii',1,'C10F911','Type II diabetes mellitus without complication'),('diabetes-type-ii',1,'C10F9','Type II diabetes mellitus without complication'),('diabetes-type-ii',1,'C10FA00','Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FA','Type 2 diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FA11','Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FA','Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'C10FB00','Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FB','Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FB11','Type II diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FB','Type II diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'C10FC00','Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FC','Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FC11','Type II diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FC','Type II diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'C10FD00','Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FD','Type 2 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FD11','Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FD','Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'C10FE00','Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FE','Type 2 diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FE11','Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FE','Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'C10FF00','Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FF','Type 2 diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FF11','Type II diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FF','Type II diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'C10FG00','Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FG','Type 2 diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FG11','Type II diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FG','Type II diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'C10FH00','Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FH','Type 2 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FH11','Type II diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FH','Type II diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'C10FJ00','Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FJ','Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FJ11','Insulin treated Type II diabetes mellitus'),('diabetes-type-ii',1,'C10FJ','Insulin treated Type II diabetes mellitus'),('diabetes-type-ii',1,'C10FK00','Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK','Hyperosmolar non-ketotic state in type 2 diabetes mellitus'),('diabetes-type-ii',1,'C10FK11','Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes-type-ii',1,'C10FK','Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes-type-ii',1,'C10FL00','Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FL','Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FL11','Type II diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FL','Type II diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'C10FM00','Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FM','Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FM11','Type II diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FM','Type II diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'C10FN00','Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FN','Type 2 diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FN11','Type II diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FN','Type II diabetes mellitus with ketoacidosis'),('diabetes-type-ii',1,'C10FP00','Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FP','Type 2 diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FP11','Type II diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FP','Type II diabetes mellitus with ketoacidotic coma'),('diabetes-type-ii',1,'C10FQ00','Type 2 diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'C10FQ','Type 2 diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'C10FQ11','Type II diabetes mellitus with exudative maculopathy'),
('diabetes-type-ii',1,'C10FQ','Type II diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'C10FR00','Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10FR','Type 2 diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10FR11','Type II diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10FR','Type II diabetes mellitus with gastroparesis'),('diabetes-type-ii',1,'C10y100','Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10y1','Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z100','Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'C10z1','Diabetes mellitus, adult onset, with unspecified complication')

INSERT INTO #AllCodes
SELECT [concept], [version], [code] from #codesreadv2;

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('diabetes-type-i',1,'C1000','Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes-type-i',1,'C1010','Diabetes mellitus, juvenile type, with ketoacidosis'),('diabetes-type-i',1,'C1020','Diabetes mellitus, juvenile type, with hyperosmolar coma'),('diabetes-type-i',1,'C1030','Diabetes mellitus, juvenile type, with ketoacidotic coma'),('diabetes-type-i',1,'C1040','Diabetes mellitus, juvenile type, with renal manifestation'),('diabetes-type-i',1,'C1050','Diabetes mellitus, juvenile type, with ophthalmic manifestation'),('diabetes-type-i',1,'C1060','Diabetes mellitus, juvenile type, with neurological manifestation'),('diabetes-type-i',1,'C1070','Diabetes mellitus, juvenile type, with peripheral circulatory disorder'),('diabetes-type-i',1,'C1080','Insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-i',1,'C1081','Insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-i',1,'C1082','Insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-i',1,'C1083','Insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-i',1,'C1085','Insulin-dependent diabetes mellitus with ulcer'),('diabetes-type-i',1,'C1086','Insulin-dependent diabetes mellitus with gangrene'),('diabetes-type-i',1,'C1087','IDDM - Insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-i',1,'C1088','Insulin-dependent diabetes mellitus - poor control'),('diabetes-type-i',1,'C1089','Insulin-dependent diabetes maturity onset'),('diabetes-type-i',1,'C10y0','Diabetes mellitus, juvenile type, with other specified manifestation'),('diabetes-type-i',1,'C10z0','Diabetes mellitus, juvenile type, with unspecified complication'),('diabetes-type-i',1,'X40J4','Insulin-dependent diabetes mellitus'),('diabetes-type-i',1,'X40JY','Congenital insulin-dependent diabetes mellitus with fatal secretory diarrhoea'),('diabetes-type-i',1,'XE10E','Diabetes mellitus, juvenile type, with no mention of complication'),('diabetes-type-i',1,'XE12C','Insulin dependent diabetes mel'),('diabetes-type-i',1,'XM19i','[EDTA] Diabetes Type I (insulin dependent) associated with renal failure'),('diabetes-type-i',1,'Xa4g7','Unstable type 1 diabetes mellitus'),('diabetes-type-i',1,'XaA6b','Perceived control of insulin-dependent diabetes'),('diabetes-type-i',1,'XaELP','Insulin-dependent diabetes without complication'),('diabetes-type-i',1,'XaEnn','Type I diabetes mellitus with mononeuropathy'),('diabetes-type-i',1,'XaEno','Insulin dependent diabetes mellitus with polyneuropathy'),('diabetes-type-i',1,'XaF04','Type 1 diabetes mellitus with nephropathy'),('diabetes-type-i',1,'XaFWG','Type 1 diabetes mellitus with hypoglycaemic coma'),('diabetes-type-i',1,'XaFm8','Type 1 diabetes mellitus with diabetic cataract'),('diabetes-type-i',1,'XaFmK','Type I diabetes mellitus with peripheral angiopathy'),('diabetes-type-i',1,'XaFmL','Type 1 diabetes mellitus with arthropathy'),('diabetes-type-i',1,'XaFmM','Type 1 diabetes mellitus with neuropathic arthropathy'),('diabetes-type-i',1,'XaIzM','Type 1 diabetes mellitus with persistent proteinuria'),('diabetes-type-i',1,'XaIzN','Type 1 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-i',1,'XaJSr','Type I diabetes mellitus with exudative maculopathy'),('diabetes-type-i',1,'XaKyW','Type I diabetes mellitus with gastroparesis');
INSERT INTO #codesctv3
VALUES ('diabetes-type-ii',1,'C1011','Diabetes mellitus, adult onset, with ketoacidosis'),('diabetes-type-ii',1,'C1021','Diabetes mellitus, adult onset, with hyperosmolar coma'),('diabetes-type-ii',1,'C1031','Diabetes mellitus, adult onset, with ketoacidotic coma'),('diabetes-type-ii',1,'C1041','Diabetes mellitus, adult onset, with renal manifestation'),('diabetes-type-ii',1,'C1051','Diabetes mellitus, adult onset, with ophthalmic manifestation'),('diabetes-type-ii',1,'C1061','Diabetes mellitus, adult onset, with neurological manifestation'),('diabetes-type-ii',1,'C1071','Diabetes mellitus, adult onset, with peripheral circulatory disorder'),('diabetes-type-ii',1,'C1090','Non-insulin-dependent diabetes mellitus with renal complications'),('diabetes-type-ii',1,'C1091','Non-insulin-dependent diabetes mellitus with ophthalmic complications'),('diabetes-type-ii',1,'C1092','Non-insulin-dependent diabetes mellitus with neurological complications'),('diabetes-type-ii',1,'C1093','Non-insulin-dependent diabetes mellitus with multiple complications'),('diabetes-type-ii',1,'C1094','Non-insulin-dependent diabetes mellitus with ulcer'),('diabetes-type-ii',1,'C1095','Non-insulin-dependent diabetes mellitus with gangrene'),('diabetes-type-ii',1,'C1096','NIDDM - Non-insulin-dependent diabetes mellitus with retinopathy'),('diabetes-type-ii',1,'C1097','Non-insulin-dependent diabetes mellitus - poor control'),('diabetes-type-ii',1,'C10y1','Diabetes mellitus, adult onset, with other specified manifestation'),('diabetes-type-ii',1,'C10z1','Diabetes mellitus, adult onset, with unspecified complication'),('diabetes-type-ii',1,'X40J5','Non-insulin-dependent diabetes mellitus'),('diabetes-type-ii',1,'X40J6','Insulin treated Type 2 diabetes mellitus'),('diabetes-type-ii',1,'X40JJ','Diabetes mellitus autosomal dominant type 2'),('diabetes-type-ii',1,'XE10F','Diabetes mellitus, adult onset, with no mention of complication'),('diabetes-type-ii',1,'XM19j','[EDTA] Diabetes Type II (non-insulin-dependent) associated with renal failure'),('diabetes-type-ii',1,'XaELQ','Non-insulin-dependent diabetes mellitus without complication'),('diabetes-type-ii',1,'XaEnp','Type II diabetes mellitus with mononeuropathy'),('diabetes-type-ii',1,'XaEnq','Type 2 diabetes mellitus with polyneuropathy'),('diabetes-type-ii',1,'XaF05','Type 2 diabetes mellitus with nephropathy'),('diabetes-type-ii',1,'XaFWI','Type II diabetes mellitus with hypoglycaemic coma'),('diabetes-type-ii',1,'XaFmA','Type II diabetes mellitus with diabetic cataract'),('diabetes-type-ii',1,'XaFn7','Non-insulin-dependent diabetes mellitus with peripheral angiopathy'),('diabetes-type-ii',1,'XaFn8','Non-insulin dependent diabetes mellitus with arthropathy'),('diabetes-type-ii',1,'XaFn9','Non-insulin dependent diabetes mellitus with neuropathic arthropathy'),('diabetes-type-ii',1,'XaIfG','Type II diabetes on insulin'),('diabetes-type-ii',1,'XaIfI','Type II diabetes on diet only'),('diabetes-type-ii',1,'XaIrf','Hyperosmolar non-ketotic state in type II diabetes mellitus'),('diabetes-type-ii',1,'XaIzQ','Type 2 diabetes mellitus with persistent proteinuria'),('diabetes-type-ii',1,'XaIzR','Type 2 diabetes mellitus with persistent microalbuminuria'),('diabetes-type-ii',1,'XaJQp','Type II diabetes mellitus with exudative maculopathy'),('diabetes-type-ii',1,'XaKyX','Type II diabetes mellitus with gastroparesis')

INSERT INTO #AllCodes
SELECT [concept], [version], [code] from #codesctv3;

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];



INSERT INTO #AllCodes
SELECT [concept], [version], [code] from #codessnomed;

IF OBJECT_ID('tempdb..#codesemis') IS NOT NULL DROP TABLE #codesemis;
CREATE TABLE #codesemis (
  [concept] [varchar](255) NOT NULL,
  [version] INT NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];



INSERT INTO #AllCodes
SELECT [concept], [version], [code] from #codesemis;


IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, version INT NOT NULL);

-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.concept, dcr.[version]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.concept, dcc.[version]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

-- EMIS codes with a FK Reference Coding ID
INSERT INTO #TempRefCodes
SELECT FK_Reference_Coding_ID, ce.concept, ce.[version]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL, [version] INT NOT NULL);

-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.concept, dcs.[version]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- EMIS codes with a FK SNOMED ID but without a FK Reference Coding ID
INSERT INTO #TempSNOMEDRefCodes
SELECT FK_Reference_SnomedCT_ID, ce.concept, ce.[version]
FROM [SharedCare].[Reference_Local_Code] rlc
INNER JOIN #codesemis ce on ce.code = rlc.LocalCode
WHERE FK_Reference_Coding_ID = -1
AND FK_Reference_SnomedCT_ID != -1;

-- De-duped tables
IF OBJECT_ID('tempdb..#CodeSets') IS NOT NULL DROP TABLE #CodeSets;
CREATE TABLE #CodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL);

IF OBJECT_ID('tempdb..#SnomedSets') IS NOT NULL DROP TABLE #SnomedSets;
CREATE TABLE #SnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, concept VARCHAR(255) NOT NULL);

IF OBJECT_ID('tempdb..#VersionedCodeSets') IS NOT NULL DROP TABLE #VersionedCodeSets;
CREATE TABLE #VersionedCodeSets (FK_Reference_Coding_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT);

IF OBJECT_ID('tempdb..#VersionedSnomedSets') IS NOT NULL DROP TABLE #VersionedSnomedSets;
CREATE TABLE #VersionedSnomedSets (FK_Reference_SnomedCT_ID BIGINT NOT NULL, Concept VARCHAR(255), [Version] INT);

INSERT INTO #VersionedCodeSets
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #VersionedSnomedSets
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

INSERT INTO #CodeSets
SELECT FK_Reference_Coding_ID, c.concept
FROM #VersionedCodeSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedCodeSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

INSERT INTO #SnomedSets
SELECT FK_Reference_SnomedCT_ID, c.concept
FROM #VersionedSnomedSets c
INNER JOIN (
  SELECT concept, MAX(version) AS maxVersion FROM #VersionedSnomedSets
  GROUP BY concept)
sub ON sub.concept = c.concept AND c.version = sub.maxVersion;

-- >>> Following code sets injected: diabetes-type-i v1
IF OBJECT_ID('tempdb..#DiabeticTypeIPatients') IS NOT NULL DROP TABLE #DiabeticTypeIPatients;
CREATE TABLE #DiabeticTypeIPatients(FK_Patient_Link_ID BIGINT, FirstT1DiagnosisDate DATE, DeathDate DATE);
INSERT INTO #DiabeticTypeIPatients
SELECT FK_Patient_Link_ID, MIN(CAST(EventDate AS DATE)) AS FirstT1DiagnosisDate, NULL
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept IN ('diabetes-type-i') AND [Version]=1) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept IN ('diabetes-type-i') AND [Version]=1)
)
GROUP BY FK_Patient_Link_ID;

-- Add death date where applicable
UPDATE d
SET d.DeathDate = p.DeathDate
FROM #DiabeticTypeIPatients d
INNER JOIN [RLS].vw_Patient_Link p ON p.PK_Patient_Link_ID = d.FK_Patient_Link_ID;

-- Get all patients with T2DM and the first diagnosis date
-- >>> Following code sets injected: diabetes-type-ii v1
IF OBJECT_ID('tempdb..#DiabeticTypeIIPatients') IS NOT NULL DROP TABLE #DiabeticTypeIIPatients;
CREATE TABLE #DiabeticTypeIIPatients(FK_Patient_Link_ID BIGINT, FirstT2DiagnosisDate DATE, DeathDate DATE);
INSERT INTO #DiabeticTypeIIPatients
SELECT FK_Patient_Link_ID, MIN(CAST(EventDate AS DATE)) AS FirstT2DiagnosisDate, NULL
FROM RLS.vw_GP_Events
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #VersionedSnomedSets WHERE Concept IN ('diabetes-type-ii') AND [Version]=1) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #VersionedCodeSets WHERE Concept IN ('diabetes-type-ii') AND [Version]=1)
)
GROUP BY FK_Patient_Link_ID;

-- Add death date where applicable
UPDATE d
SET d.DeathDate = p.DeathDate
FROM #DiabeticTypeIIPatients d
INNER JOIN [RLS].vw_Patient_Link p ON p.PK_Patient_Link_ID = d.FK_Patient_Link_ID;

-- Get all patients and death dates
IF OBJECT_ID('tempdb..#AllPatientsForSummaryDeathCount') IS NOT NULL DROP TABLE #AllPatientsForSummaryDeathCount;
SELECT PK_Patient_Link_ID, DeathDate INTO #AllPatientsForSummaryDeathCount FROM [RLS].vw_Patient_Link
INNER JOIN [RLS].vw_Patient p ON p.FK_Patient_Link_ID = PK_Patient_Link_ID
WHERE FK_Reference_Tenancy_ID = 2;

--┌────────────────────┐
--│ Patient GP history │
--└────────────────────┘

-- OBJECTIVE: To produce a table showing the start and end dates for each practice the patient
--            has been registered at.

-- ASSUMPTIONS:
--	-	We do not have data on patients who move out of GM, though we do know that it happened. 
--    For these patients we record the GPPracticeCode as OutOfArea
--  - Where two adjacent time periods either overlap, or have a gap between them, we assume that
--    the most recent registration is more accurate and adjust the end date of the first time
--    period accordingly. This is an infrequent occurrence.

-- INPUT: No pre-requisites

-- OUTPUT: A temp table as follows:
-- #PatientGPHistory (FK_Patient_Link_ID, GPPracticeCode, StartDate, EndDate)
--	- FK_Patient_Link_ID - unique patient id
--	- GPPracticeCode - national GP practice id system
--	- StartDate - date the patient registered at the practice
--	- EndDate - date the patient left the practice

-- First let's get the raw data from the GP history table
IF OBJECT_ID('tempdb..#AllGPHistoryData') IS NOT NULL DROP TABLE #AllGPHistoryData;
SELECT 
	FK_Patient_Link_ID, CASE WHEN GPPracticeCode like 'ZZZ%' THEN 'OutOfArea' ELSE GPPracticeCode END AS GPPracticeCode, 
	CASE WHEN StartDate IS NULL THEN '1900-01-01' ELSE CAST(StartDate AS DATE) END AS StartDate, 
	CASE WHEN EndDate IS NULL THEN '2100-01-01' ELSE CAST(EndDate AS DATE) END AS EndDate 
INTO #AllGPHistoryData FROM rls.vw_Patient_GP_History
WHERE FK_Reference_Tenancy_ID=2 -- limit to GP feed makes it easier than trying to deal with the conflicting data coming from acute care
AND (StartDate < EndDate OR EndDate IS NULL) --Some time periods are instantaneous (start = end) - this ignores them
AND GPPracticeCode IS NOT NULL;
--4147852

IF OBJECT_ID('tempdb..#PatientGPHistory') IS NOT NULL DROP TABLE #PatientGPHistory;
CREATE TABLE #PatientGPHistory(FK_Patient_Link_ID BIGINT, GPPracticeCode NVARCHAR(50), StartDate DATE, EndDate DATE);

IF OBJECT_ID('tempdb..#AllGPHistoryDataOrdered') IS NOT NULL DROP TABLE #AllGPHistoryDataOrdered;
CREATE TABLE #AllGPHistoryDataOrdered(FK_Patient_Link_ID BIGINT, GPPracticeCode NVARCHAR(50), StartDate DATE, EndDate DATE, RowNumber INT);

IF OBJECT_ID('tempdb..#AllGPHistoryDataOrderedJoined') IS NOT NULL DROP TABLE #AllGPHistoryDataOrderedJoined;
CREATE TABLE #AllGPHistoryDataOrderedJoined(
  FK_Patient_Link_ID BIGINT,
  GP1 NVARCHAR(50),
  R1 INT,
  S1 DATE,
  E1 DATE,
  GP2 NVARCHAR(50),
  S2 DATE,
  E2 DATE,
  R2 INT,
);

-- Easier to get rid of everyone who only has one GP history entry
IF OBJECT_ID('tempdb..#PatientGPHistoryJustOneEntryIds') IS NOT NULL DROP TABLE #PatientGPHistoryJustOneEntryIds;
SELECT FK_Patient_Link_ID INTO #PatientGPHistoryJustOneEntryIds FROM #AllGPHistoryData
GROUP BY FK_Patient_Link_ID
HAVING COUNT(*) = 1;

-- Holding table for their data
IF OBJECT_ID('tempdb..#PatientGPHistoryJustOneEntry') IS NOT NULL DROP TABLE #PatientGPHistoryJustOneEntry;
SELECT * INTO #PatientGPHistoryJustOneEntry FROM #AllGPHistoryData
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #PatientGPHistoryJustOneEntryIds);

-- Remove from main table
DELETE FROM #AllGPHistoryData
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #PatientGPHistoryJustOneEntryIds);

DECLARE @size INT;
SET @size = (SELECT COUNT(*) FROM #AllGPHistoryData) + 1;

WHILE(@size > (SELECT COUNT(*) FROM #AllGPHistoryData))
BEGIN
  SET @size = (SELECT COUNT(*) FROM #AllGPHistoryData);

  -- Add row numbers so we can join with next row
  TRUNCATE TABLE #AllGPHistoryDataOrdered;
  INSERT INTO #AllGPHistoryDataOrdered
  SELECT *, ROW_NUMBER() OVER (PARTITION BY FK_Patient_Link_ID ORDER BY StartDate) AS RowNumber from #AllGPHistoryData;

  -- Join each patient row with the next one, but only look at the odd numbers to avoid duplicating
  TRUNCATE TABLE #AllGPHistoryDataOrderedJoined;
  INSERT INTO #AllGPHistoryDataOrderedJoined
  SELECT 
    o1.FK_Patient_Link_ID,o1.GPPracticeCode AS GP1,o1.RowNumber AS R1, 
    o1.StartDate AS S1, o1.EndDate AS E1, o2.GPPracticeCode AS GP2, 
    o2.StartDate as S2, o2.EndDate as E2, o2.RowNumber as R2
  FROM #AllGPHistoryDataOrdered o1
  LEFT OUTER JOIN #AllGPHistoryDataOrdered o2 ON o1.FK_Patient_Link_ID = o2.FK_Patient_Link_ID AND o1.RowNumber = o2.RowNumber - 1
  WHERE o1.RowNumber % 2 = 1
  ORDER BY o1.FK_Patient_Link_ID DESC, o1.StartDate;

  -- If GP is the same, then merge the time periods
  TRUNCATE TABLE #PatientGPHistory;
  INSERT INTO #PatientGPHistory
  SELECT FK_Patient_Link_ID, GP1, S1, CASE WHEN E2 > E1 THEN E2 ELSE E1 END AS E
  FROM #AllGPHistoryDataOrderedJoined
  WHERE GP1 = GP2;

  -- If GP is different, first insert the GP2 record
  INSERT INTO #PatientGPHistory
  SELECT FK_Patient_Link_ID, GP2, S2, E2 FROM #AllGPHistoryDataOrderedJoined
  WHERE GP1 != GP2;

  --  then insert the GP1 record
  INSERT into #PatientGPHistory
  SELECT FK_Patient_Link_ID, GP1, S1, S2 FROM #AllGPHistoryDataOrderedJoined
  WHERE GP1 != GP2;

  -- If the GP2 is null, implies it's the last row and didn't have a subsequent
  -- row to match on, so we just put it back in the gp history table
  INSERT into #PatientGPHistory
  SELECT FK_Patient_Link_ID, GP1, S1, E1 FROM #AllGPHistoryDataOrderedJoined
  WHERE GP2 IS NULL;

  -- Nuke the AllGPHistoryData table
  TRUNCATE TABLE #AllGPHistoryData;

  -- Repopulate with the current "final" snapshot
  INSERT INTO #AllGPHistoryData
  SELECT * FROM #PatientGPHistory;

END

-- Finally re-add the people with only one record
INSERT INTO #PatientGPHistory
SELECT * FROM #PatientGPHistoryJustOneEntry;

-- Table of dates for future joining
IF OBJECT_ID('tempdb..#DatesFrom2019') IS NOT NULL DROP TABLE #DatesFrom2019;
CREATE TABLE #DatesFrom2019 ([date] date);
declare @dt datetime = '2019-01-01'
declare @dtEnd datetime = GETDATE();
WHILE (@dt <= @dtEnd) BEGIN
    insert into #DatesFrom2019([date])
        values(@dt)
    SET @dt = DATEADD(month, 1, @dt)
END;

-- T1 population per month
IF OBJECT_ID('tempdb..#T1PopPerMonth') IS NOT NULL DROP TABLE #T1PopPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS T1Population INTO #T1PopPerMonth FROM #DatesFrom2019 d
INNER JOIN #DiabeticTypeIPatients t1 
	ON d.date > t1.FirstT1DiagnosisDate --only count people starting in the month AFTER their diagnosis and onwards
	AND (d.date <= t1.DeathDate OR t1.DeathDate IS NULL) --don't count people who have died before the month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=t1.FK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- T1 deaths per month
IF OBJECT_ID('tempdb..#T1DeathsPerMonth') IS NOT NULL DROP TABLE #T1DeathsPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS T1Deaths INTO #T1DeathsPerMonth FROM #DatesFrom2019 d
INNER JOIN #DiabeticTypeIPatients t1 
	ON d.date > t1.FirstT1DiagnosisDate --only count people starting in the month AFTER their diagnosis and onwards
	AND d.date <= t1.DeathDate
	AND DATEADD(month, 1, d.date) > t1.DeathDate --only count people who have died in this month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=t1.FK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- T2 population per month
IF OBJECT_ID('tempdb..#T2PopPerMonth') IS NOT NULL DROP TABLE #T2PopPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS T2Population INTO #T2PopPerMonth FROM #DatesFrom2019 d
INNER JOIN #DiabeticTypeIIPatients T2 
	ON d.date > T2.FirstT2DiagnosisDate --only count people starting in the month AFTER their diagnosis and onwards
	AND (d.date <= T2.DeathDate OR T2.DeathDate IS NULL) --don't count people who have died before the month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=T2.FK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- T2 deaths per month
IF OBJECT_ID('tempdb..#T2DeathsPerMonth') IS NOT NULL DROP TABLE #T2DeathsPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS T2Deaths INTO #T2DeathsPerMonth FROM #DatesFrom2019 d
INNER JOIN #DiabeticTypeIIPatients T2 
	ON d.date > T2.FirstT2DiagnosisDate --only count people starting in the month AFTER their diagnosis and onwards
	AND d.date <= T2.DeathDate
	AND DATEADD(month, 1, d.date) > T2.DeathDate --only count people who have died in this month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=T2.FK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- ALL population per month
IF OBJECT_ID('tempdb..#ALLPopPerMonth') IS NOT NULL DROP TABLE #ALLPopPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS ALLPopulation INTO #ALLPopPerMonth FROM #DatesFrom2019 d
INNER JOIN #AllPatientsForSummaryDeathCount a 
	ON (d.date <= a.DeathDate OR a.DeathDate IS NULL) --don't count people who have died before the month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=a.PK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- ALL deaths per month
IF OBJECT_ID('tempdb..#ALLDeathsPerMonth') IS NOT NULL DROP TABLE #ALLDeathsPerMonth;
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, COUNT(*) AS ALLDeaths INTO #ALLDeathsPerMonth FROM #DatesFrom2019 d
INNER JOIN #AllPatientsForSummaryDeathCount a 
	ON d.date <= a.DeathDate
	AND DATEADD(month, 1, d.date) > a.DeathDate --only count people who have died in this month
LEFT OUTER JOIN #PatientGPHistory h
	on h.StartDate <= d.date -- match the current practice for each patient each month
	AND h.EndDate >=d.date
	AND h.FK_Patient_Link_ID=a.PK_Patient_Link_ID
where h.GPPracticeCode != 'OutOfArea' -- don't count people each month who are not GM GP registered
OR h.GPPracticeCode IS NULL 
GROUP BY YEAR(d.date), MONTH(d.date)
ORDER BY YEAR(d.date), MONTH(d.date);

-- Final extract
SELECT YEAR(d.date) AS Year, MONTH(d.date) AS Month, T1Population, T1Deaths, T2Population, T2Deaths, ALLPopulation, ALLDeaths FROM #DatesFrom2019 d
LEFT OUTER JOIN #T1DeathsPerMonth t1d on t1d.Year = YEAR(d.date) and t1d.Month = MONTH(d.date)
LEFT OUTER JOIN #T1PopPerMonth t1 on t1.Year = YEAR(d.date) and t1.Month = MONTH(d.date)
LEFT OUTER JOIN #T2DeathsPerMonth t2d on t2d.Year = YEAR(d.date) and t2d.Month = MONTH(d.date)
LEFT OUTER JOIN #T2PopPerMonth t2 on t2.Year = YEAR(d.date) and t2.Month = MONTH(d.date)
LEFT OUTER JOIN #ALLDeathsPerMonth ad on ad.Year = YEAR(d.date) and ad.Month = MONTH(d.date)
LEFT OUTER JOIN #ALLPopPerMonth a on a.Year = YEAR(d.date) and a.Month = MONTH(d.date)
WHERE YEAR(d.date) < YEAR(GETDATE())
OR MONTH(d.date) < MONTH(GETDATE()); -- No deaths in "current" month so no point returning
