--Just want the output, not the messages
SET NOCOUNT ON;

-- Set the start date
DECLARE @StartDate datetime;
SET @StartDate = '2020-01-01';

--┌───────────────────────────────┐
--│ CLASSIFY SECONDARY ADMISSIONS │
--└───────────────────────────────┘

-- OUTPUT: A temp table as follows:
-- #AdmissionTypes (FK_Patient_Link_ID, AdmissionDate, AdmissionType)
-- 	- FK_Patient_Link_ID - unique patient id
--	- AdmissionDate - date of admission (YYYY-MM-DD)
--	- AcuteProvider - Bolton, SRFT, Stockport etc..
--	- AdmissionType - One of: Maternity/Unplanned/Planned/Transfer/Unknown

-- For each acute admission we find the type. If multiple admissions on same day
-- we group and take the 'highest' category e.g.
-- choose Unplanned, then Planned, then Maternity, then Transfer, then Unknown
IF OBJECT_ID('tempdb..#AdmissionTypes') IS NOT NULL DROP TABLE #AdmissionTypes;
SELECT 
	FK_Patient_Link_ID, AdmissionDate, 
	CASE 
		WHEN AdmissionId = 5 THEN 'Maternity' 
		WHEN AdmissionId = 4 THEN 'Unplanned' 
		WHEN AdmissionId = 3 THEN 'Planned' 
		WHEN AdmissionId = 2 THEN 'Transfer' 
		WHEN AdmissionId = 1 THEN 'Unknown' 
	END as AdmissionType,
	AcuteProvider 
INTO #AdmissionTypes FROM (
	SELECT 
		FK_Patient_Link_ID, CONVERT(DATE, AdmissionDate) as AdmissionDate, 
		MAX(
			CASE 
				WHEN AdmissionTypeCode IN ('PL','11','WL','13','12','BL','TR','IPPlannedAd') THEN 3 --'Planned'
				WHEN AdmissionTypeCode IN ('AE','21','22','23','EM','28','2D','24','AI','BB','DO','2A','A+E Admission','Emerg GP') THEN 4 --'Unplanned'
				WHEN AdmissionTypeCode IN ('31','BH','AN','82','PN','32','BHOSP','83') THEN 5 --'Maternity'
				WHEN AdmissionTypeCode IN ('81', 'ET','T','HospTran') THEN 2 --'Transfer'
				ELSE 1 --'Unknown'
			END
		)	AS AdmissionId,
		t.TenancyName AS AcuteProvider
	FROM RLS.vw_Acute_Inpatients i
	LEFT OUTER JOIN SharedCare.Reference_Tenancy t ON t.PK_Reference_Tenancy_ID = i.FK_Reference_Tenancy_ID
	WHERE EventType = 'Admission'
	AND AdmissionDate >= @StartDate
	GROUP BY FK_Patient_Link_ID, CONVERT(DATE, AdmissionDate), t.TenancyName
) sub;
-- 523477 rows	523477 rows
-- 00:00:16		00:00:45

-- Populate a table with all the patients so in the future we can get their LTCs and deprivation score etc.
IF OBJECT_ID('tempdb..#Patients') IS NOT NULL DROP TABLE #Patients;
SELECT DISTINCT FK_Patient_Link_ID INTO #Patients FROM #AdmissionTypes;
-- 286087 rows
-- 00:00:01

--
--┌──────────┐
--│ GET LTCS │
--└──────────┘

-- INPUT: Assumes there exists a temp table as follows:
-- #Patients (FK_Patient_Link_ID)
-- A distinct list of FK_Patient_Link_IDs for each patient in the cohort

-- OUTPUT: A temp table with a row for each patient and ltc combo
-- #PatientsWithLTCs (FK_Patient_Link_ID, LTC)

-- Get the LTCs that each patient had prior to @StartDate

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY - see "node create-ltc-sql.js" !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



IF OBJECT_ID('tempdb..#codesreadv2') IS NOT NULL DROP TABLE #codesreadv2;
CREATE TABLE #codesreadv2 (
  [condition] [varchar](255) NOT NULL,
  [group] [varchar](255) NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesreadv2
VALUES ('atrial fibrillation','Cardiovascular','G573200',''),('atrial fibrillation','Cardiovascular','G5732',''),('atrial fibrillation','Cardiovascular','G573000',''),('atrial fibrillation','Cardiovascular','G5730',''),('atrial fibrillation','Cardiovascular','G573100',''),('atrial fibrillation','Cardiovascular','G5731',''),('atrial fibrillation','Cardiovascular','G573.00',''),('atrial fibrillation','Cardiovascular','G573.',''),('atrial fibrillation','Cardiovascular','G573z00',''),('atrial fibrillation','Cardiovascular','G573z',''),('atrial fibrillation','Cardiovascular','G573300',''),('atrial fibrillation','Cardiovascular','G5733',''),('atrial fibrillation','Cardiovascular','G573500',''),('atrial fibrillation','Cardiovascular','G5735',''),('atrial fibrillation','Cardiovascular','G573400',''),('atrial fibrillation','Cardiovascular','G5734','');

IF OBJECT_ID('tempdb..#codesctv3') IS NOT NULL DROP TABLE #codesctv3;
CREATE TABLE #codesctv3 (
  [condition] [varchar](255) NOT NULL,
  [group] [varchar](255) NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codesctv3
VALUES ('atrial fibrillation','Cardiovascular','G573.',''),('atrial fibrillation','Cardiovascular','G5730',''),('atrial fibrillation','Cardiovascular','G5731',''),('atrial fibrillation','Cardiovascular','G573z',''),('atrial fibrillation','Cardiovascular','X202R',''),('atrial fibrillation','Cardiovascular','X202S',''),('atrial fibrillation','Cardiovascular','Xa2E8',''),('atrial fibrillation','Cardiovascular','Xa7nI',''),('atrial fibrillation','Cardiovascular','XaEga',''),('atrial fibrillation','Cardiovascular','XaOfa',''),('atrial fibrillation','Cardiovascular','XaOft',''),('atrial fibrillation','Cardiovascular','XaaUH',''),('atrial fibrillation','Cardiovascular','XaeUP',''),('atrial fibrillation','Cardiovascular','XaeUQ',''),('atrial fibrillation','Cardiovascular','XaeUR','');

IF OBJECT_ID('tempdb..#codessnomed') IS NOT NULL DROP TABLE #codessnomed;
CREATE TABLE #codessnomed (
  [condition] [varchar](255) NOT NULL,
  [group] [varchar](255) NOT NULL,
	[code] [varchar](20) COLLATE Latin1_General_CS_AS NOT NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY];

INSERT INTO #codessnomed
VALUES ('heart failure','Cardiovascular','153931000119109',''),('heart failure','Cardiovascular','10633002',''),('heart failure','Cardiovascular','49584005',''),('heart failure','Cardiovascular','443343001',''),('heart failure','Cardiovascular','698296002',''),('heart failure','Cardiovascular','56675007',''),('heart failure','Cardiovascular','195114002',''),('heart failure','Cardiovascular','74960003',''),('heart failure','Cardiovascular','364006',''),('heart failure','Cardiovascular','153951000119103',''),('heart failure','Cardiovascular','443344007',''),('heart failure','Cardiovascular','443253003',''),('heart failure','Cardiovascular','80479009',''),('heart failure','Cardiovascular','359617009',''),('heart failure','Cardiovascular','443254009',''),('heart failure','Cardiovascular','78862003',''),('heart failure','Cardiovascular','194767001',''),('heart failure','Cardiovascular','13839000',''),('heart failure','Cardiovascular','92506005',''),('heart failure','Cardiovascular','71892000',''),('heart failure','Cardiovascular','410431009',''),('heart failure','Cardiovascular','153941000119100',''),('heart failure','Cardiovascular','88805009',''),('heart failure','Cardiovascular','79955004',''),('heart failure','Cardiovascular','441530006',''),('heart failure','Cardiovascular','48447003',''),('heart failure','Cardiovascular','5375005',''),('heart failure','Cardiovascular','111283005',''),('heart failure','Cardiovascular','66989003',''),('heart failure','Cardiovascular','10335000',''),('heart failure','Cardiovascular','441481004',''),('heart failure','Cardiovascular','195112003',''),('heart failure','Cardiovascular','206586007',''),('heart failure','Cardiovascular','42343007',''),('heart failure','Cardiovascular','72481000119103',''),('heart failure','Cardiovascular','101281000119107',''),('heart failure','Cardiovascular','426263006',''),('heart failure','Cardiovascular','426611007',''),('heart failure','Cardiovascular','717840005',''),('heart failure','Cardiovascular','15629591000119103',''),('heart failure','Cardiovascular','67441000119101',''),('heart failure','Cardiovascular','15629541000119106',''),('heart failure','Cardiovascular','67431000119105',''),('heart failure','Cardiovascular','23341000119109',''),('heart failure','Cardiovascular','82523003',''),('heart failure','Cardiovascular','83291003',''),('heart failure','Cardiovascular','195111005',''),('heart failure','Cardiovascular','424404003',''),('heart failure','Cardiovascular','371862006',''),('heart failure','Cardiovascular','418304008',''),('heart failure','Cardiovascular','120891000119109',''),('heart failure','Cardiovascular','120881000119106',''),('heart failure','Cardiovascular','96311000119109',''),('heart failure','Cardiovascular','84114007',''),('heart failure','Cardiovascular','233924009',''),('heart failure','Cardiovascular','471880001',''),('heart failure','Cardiovascular','446221000',''),('heart failure','Cardiovascular','703272007',''),('heart failure','Cardiovascular','703275009',''),('heart failure','Cardiovascular','703273002',''),('heart failure','Cardiovascular','703276005',''),('heart failure','Cardiovascular','703274008',''),('heart failure','Cardiovascular','10091002',''),('heart failure','Cardiovascular','15781000119107',''),('heart failure','Cardiovascular','194779001',''),('heart failure','Cardiovascular','194781004',''),('heart failure','Cardiovascular','5148006',''),('heart failure','Cardiovascular','46113002',''),('heart failure','Cardiovascular','275514001',''),('heart failure','Cardiovascular','85232009',''),('heart failure','Cardiovascular','44088000',''),('heart failure','Cardiovascular','25544003',''),('heart failure','Cardiovascular','83105008',''),('heart failure','Cardiovascular','314206003',''),('heart failure','Cardiovascular','43736008',''),('heart failure','Cardiovascular','128404006',''),('heart failure','Cardiovascular','426012001',''),('heart failure','Cardiovascular','44313006',''),('heart failure','Cardiovascular','367363000',''),('heart failure','Cardiovascular','15964701000119109',''),('heart failure','Cardiovascular','698594003',''),('heart failure','Cardiovascular','417996009',''),('heart failure','Cardiovascular','120861000119102',''),('heart failure','Cardiovascular','15629741000119102',''),('heart failure','Cardiovascular','120851000119104',''),
('peptic ulcer disease','Gastrointestinal','235648004',''),('peptic ulcer disease','Gastrointestinal','196652006',''),('peptic ulcer disease','Gastrointestinal','12847006',''),('peptic ulcer disease','Gastrointestinal','87756006',''),('peptic ulcer disease','Gastrointestinal','86895006',''),('peptic ulcer disease','Gastrointestinal','51847008',''),('peptic ulcer disease','Gastrointestinal','66767006',''),('peptic ulcer disease','Gastrointestinal','41986000',''),('peptic ulcer disease','Gastrointestinal','196658005',''),('peptic ulcer disease','Gastrointestinal','61347001',''),('peptic ulcer disease','Gastrointestinal','62936002',''),('peptic ulcer disease','Gastrointestinal','22511002',''),('peptic ulcer disease','Gastrointestinal','32490005',''),('peptic ulcer disease','Gastrointestinal','75342000',''),('peptic ulcer disease','Gastrointestinal','23693000',''),('peptic ulcer disease','Gastrointestinal','39344002',''),('peptic ulcer disease','Gastrointestinal','444926003',''),('peptic ulcer disease','Gastrointestinal','111350000',''),('peptic ulcer disease','Gastrointestinal','18665000',''),('peptic ulcer disease','Gastrointestinal','95529005',''),('peptic ulcer disease','Gastrointestinal','89748001',''),('peptic ulcer disease','Gastrointestinal','46708007',''),('peptic ulcer disease','Gastrointestinal','48974009',''),('peptic ulcer disease','Gastrointestinal','17067009',''),('peptic ulcer disease','Gastrointestinal','70418001',''),('peptic ulcer disease','Gastrointestinal','53337006',''),('peptic ulcer disease','Gastrointestinal','196632005',''),('peptic ulcer disease','Gastrointestinal','19850005',''),('peptic ulcer disease','Gastrointestinal','43694004',''),('peptic ulcer disease','Gastrointestinal','90628007',''),('peptic ulcer disease','Gastrointestinal','67964002',''),('peptic ulcer disease','Gastrointestinal','81225008',''),('peptic ulcer disease','Gastrointestinal','54053008',''),('peptic ulcer disease','Gastrointestinal','196707000',''),('peptic ulcer disease','Gastrointestinal','63954007',''),('peptic ulcer disease','Gastrointestinal','72408002',''),('peptic ulcer disease','Gastrointestinal','81387001',''),('peptic ulcer disease','Gastrointestinal','66673003',''),('peptic ulcer disease','Gastrointestinal','59515005',''),('peptic ulcer disease','Gastrointestinal','58711008',''),('peptic ulcer disease','Gastrointestinal','196712004',''),('peptic ulcer disease','Gastrointestinal','66636001',''),('peptic ulcer disease','Gastrointestinal','72219001',''),('peptic ulcer disease','Gastrointestinal','72395008',''),('peptic ulcer disease','Gastrointestinal','30514008',''),('peptic ulcer disease','Gastrointestinal','10389003',''),('peptic ulcer disease','Gastrointestinal','77987006',''),('peptic ulcer disease','Gastrointestinal','183281000119107',''),('peptic ulcer disease','Gastrointestinal','196682000',''),('peptic ulcer disease','Gastrointestinal','235687004',''),('peptic ulcer disease','Gastrointestinal','235647009',''),('peptic ulcer disease','Gastrointestinal','12274003',''),('peptic ulcer disease','Gastrointestinal','43406003',''),('peptic ulcer disease','Gastrointestinal','111353003',''),('peptic ulcer disease','Gastrointestinal','47064007',''),('peptic ulcer disease','Gastrointestinal','22157005',''),('peptic ulcer disease','Gastrointestinal','28945005',''),('peptic ulcer disease','Gastrointestinal','196687006',''),('peptic ulcer disease','Gastrointestinal','79118000',''),('peptic ulcer disease','Gastrointestinal','35681000',''),('peptic ulcer disease','Gastrointestinal','34921009',''),('peptic ulcer disease','Gastrointestinal','45485004',''),('peptic ulcer disease','Gastrointestinal','58085004',''),('peptic ulcer disease','Gastrointestinal','3023008',''),('peptic ulcer disease','Gastrointestinal','109814008',''),('peptic ulcer disease','Gastrointestinal','724523000',''),('peptic ulcer disease','Gastrointestinal','724522005',''),('peptic ulcer disease','Gastrointestinal','4911000119101',''),('peptic ulcer disease','Gastrointestinal','307233002',''),('peptic ulcer disease','Gastrointestinal','308882008',''),('peptic ulcer disease','Gastrointestinal','43035002',''),('peptic ulcer disease','Gastrointestinal','235650007',''),('peptic ulcer disease','Gastrointestinal','128286008',''),('peptic ulcer disease','Gastrointestinal','89469000',''),('peptic ulcer disease','Gastrointestinal','34021006',''),('peptic ulcer disease','Gastrointestinal','36975000',''),('peptic ulcer disease','Gastrointestinal','81142005',''),('peptic ulcer disease','Gastrointestinal','62341002',''),('peptic ulcer disease','Gastrointestinal','86258000',''),('peptic ulcer disease','Gastrointestinal','196666001',''),('peptic ulcer disease','Gastrointestinal','49916007',''),('peptic ulcer disease','Gastrointestinal','60551006',''),('peptic ulcer disease','Gastrointestinal','34602004',''),('peptic ulcer disease','Gastrointestinal','40214005',''),('peptic ulcer disease','Gastrointestinal','28082003',''),('peptic ulcer disease','Gastrointestinal','57940000',''),('peptic ulcer disease','Gastrointestinal','63137003',''),('peptic ulcer disease','Gastrointestinal','95530000',''),('peptic ulcer disease','Gastrointestinal','57246001',''),('peptic ulcer disease','Gastrointestinal','85859006',''),('peptic ulcer disease','Gastrointestinal','76181002',''),('peptic ulcer disease','Gastrointestinal','74341002',''),('peptic ulcer disease','Gastrointestinal','76078009',''),('peptic ulcer disease','Gastrointestinal','85787009',''),('peptic ulcer disease','Gastrointestinal','196639001',''),('peptic ulcer disease','Gastrointestinal','31301004',''),('peptic ulcer disease','Gastrointestinal','55483002',''),('peptic ulcer disease','Gastrointestinal','36246001',''),('peptic ulcer disease','Gastrointestinal','76796008',''),('peptic ulcer disease','Gastrointestinal','60531007',''),('peptic ulcer disease','Gastrointestinal','1567007',''),('peptic ulcer disease','Gastrointestinal','128288009',''),('peptic ulcer disease','Gastrointestinal','62838000',''),('peptic ulcer disease','Gastrointestinal','90257004',''),('peptic ulcer disease','Gastrointestinal','45640006',''),('peptic ulcer disease','Gastrointestinal','46523000',''),('peptic ulcer disease','Gastrointestinal','59356009',''),('peptic ulcer disease','Gastrointestinal','24001002',''),('peptic ulcer disease','Gastrointestinal','196719008',''),('peptic ulcer disease','Gastrointestinal','2807004',''),('peptic ulcer disease','Gastrointestinal','10897002',''),('peptic ulcer disease','Gastrointestinal','62477005',''),('peptic ulcer disease','Gastrointestinal','4269005',''),('peptic ulcer disease','Gastrointestinal','56579005',''),('peptic ulcer disease','Gastrointestinal','41626001',''),('peptic ulcer disease','Gastrointestinal','128287004',''),('peptic ulcer disease','Gastrointestinal','235691009',''),('peptic ulcer disease','Gastrointestinal','235649007',''),('peptic ulcer disease','Gastrointestinal','49232000',''),('peptic ulcer disease','Gastrointestinal','56461008',''),('peptic ulcer disease','Gastrointestinal','61300005',''),('peptic ulcer disease','Gastrointestinal','55746001',''),('peptic ulcer disease','Gastrointestinal','81518000',''),('peptic ulcer disease','Gastrointestinal','77661009',''),('peptic ulcer disease','Gastrointestinal','196694009',''),('peptic ulcer disease','Gastrointestinal','3483000',''),('peptic ulcer disease','Gastrointestinal','57871005',''),('peptic ulcer disease','Gastrointestinal','80953005',''),('peptic ulcer disease','Gastrointestinal','5492000',''),('peptic ulcer disease','Gastrointestinal','12384004',''),('peptic ulcer disease','Gastrointestinal','60400003',''),('peptic ulcer disease','Gastrointestinal','173889005',''),('peptic ulcer disease','Gastrointestinal','173842008',''),('peptic ulcer disease','Gastrointestinal','8322005',''),('peptic ulcer disease','Gastrointestinal','359574001',''),('peptic ulcer disease','Gastrointestinal','79806007',''),('peptic ulcer disease','Gastrointestinal','367474008',''),('peptic ulcer disease','Gastrointestinal','235690005',''),('peptic ulcer disease','Gastrointestinal','39755000',''),('peptic ulcer disease','Gastrointestinal','235689001',''),('peptic ulcer disease','Gastrointestinal','738791006',''),('peptic ulcer disease','Gastrointestinal','308212008',''),('peptic ulcer disease','Gastrointestinal','109813002',''),('peptic ulcer disease','Gastrointestinal','235692002',''),('peptic ulcer disease','Gastrointestinal','196764005',''),('peptic ulcer disease','Gastrointestinal','723884008',''),('peptic ulcer disease','Gastrointestinal','724529001',''),('peptic ulcer disease','Gastrointestinal','724534002',''),('peptic ulcer disease','Gastrointestinal','724528009',''),('peptic ulcer disease','Gastrointestinal','724530006',''),('peptic ulcer disease','Gastrointestinal','724531005',''),('peptic ulcer disease','Gastrointestinal','722200003',''),('peptic ulcer disease','Gastrointestinal','724533008',''),('peptic ulcer disease','Gastrointestinal','51868009',''),('peptic ulcer disease','Gastrointestinal','717892001',''),('peptic ulcer disease','Gastrointestinal','287828006',''),('peptic ulcer disease','Gastrointestinal','423643000',''),('peptic ulcer disease','Gastrointestinal','173887007',''),('peptic ulcer disease','Gastrointestinal','27281001',''),('peptic ulcer disease','Gastrointestinal','18367003',''),('peptic ulcer disease','Gastrointestinal','23812009',''),('peptic ulcer disease','Gastrointestinal','15115006',''),('peptic ulcer disease','Gastrointestinal','35560008',''),('peptic ulcer disease','Gastrointestinal','12355008',''),('peptic ulcer disease','Gastrointestinal','29755007',''),('peptic ulcer disease','Gastrointestinal','849601000000109',''),('peptic ulcer disease','Gastrointestinal','88968005',''),('peptic ulcer disease','Gastrointestinal','77410006',''),('peptic ulcer disease','Gastrointestinal','86983005',''),('peptic ulcer disease','Gastrointestinal','56776001',''),('peptic ulcer disease','Gastrointestinal','18169007',''),('peptic ulcer disease','Gastrointestinal','34580000',''),('peptic ulcer disease','Gastrointestinal','314627002',''),('peptic ulcer disease','Gastrointestinal','314629004',''),('peptic ulcer disease','Gastrointestinal','717878007',''),('peptic ulcer disease','Gastrointestinal','1086791000119100',''),('peptic ulcer disease','Gastrointestinal','16516008',''),('peptic ulcer disease','Gastrointestinal','6761005',''),('peptic ulcer disease','Gastrointestinal','235651006',''),('peptic ulcer disease','Gastrointestinal','397825006',''),('peptic ulcer disease','Gastrointestinal','723103002',''),('peptic ulcer disease','Gastrointestinal','723099007',''),('peptic ulcer disease','Gastrointestinal','723105009',''),('peptic ulcer disease','Gastrointestinal','713638002',''),('peptic ulcer disease','Gastrointestinal','723101000',''),('peptic ulcer disease','Gastrointestinal','724519008',''),('peptic ulcer disease','Gastrointestinal','723104008',''),('peptic ulcer disease','Gastrointestinal','129141000119104',''),('peptic ulcer disease','Gastrointestinal','723100004',''),('peptic ulcer disease','Gastrointestinal','103691000119106',''),('peptic ulcer disease','Gastrointestinal','723102007',''),('peptic ulcer disease','Gastrointestinal','717891008',''),('peptic ulcer disease','Gastrointestinal','424301005',''),('peptic ulcer disease','Gastrointestinal','173841001',''),('peptic ulcer disease','Gastrointestinal','15902003',''),('peptic ulcer disease','Gastrointestinal','53877005',''),('peptic ulcer disease','Gastrointestinal','62366003',''),('peptic ulcer disease','Gastrointestinal','2066005',''),('peptic ulcer disease','Gastrointestinal','16694003',''),('peptic ulcer disease','Gastrointestinal','17593008',''),('peptic ulcer disease','Gastrointestinal','849591000000103',''),('peptic ulcer disease','Gastrointestinal','9829001',''),('peptic ulcer disease','Gastrointestinal','72486001',''),('peptic ulcer disease','Gastrointestinal','84038009',''),('peptic ulcer disease','Gastrointestinal','73481001',''),('peptic ulcer disease','Gastrointestinal','31452001',''),('peptic ulcer disease','Gastrointestinal','59913009',''),('peptic ulcer disease','Gastrointestinal','24060004',''),('peptic ulcer disease','Gastrointestinal','16121001',''),('peptic ulcer disease','Gastrointestinal','84124004',''),('peptic ulcer disease','Gastrointestinal','42698006',''),('peptic ulcer disease','Gastrointestinal','64094003',''),('peptic ulcer disease','Gastrointestinal','87796008',''),('peptic ulcer disease','Gastrointestinal','50663005',''),('peptic ulcer disease','Gastrointestinal','54798007',''),('peptic ulcer disease','Gastrointestinal','849621000000100',''),('peptic ulcer disease','Gastrointestinal','30183003',''),('peptic ulcer disease','Gastrointestinal','21759003',''),('peptic ulcer disease','Gastrointestinal','11818002',''),('peptic ulcer disease','Gastrointestinal','2783007',''),('peptic ulcer disease','Gastrointestinal','47152002',''),('peptic ulcer disease','Gastrointestinal','35517004',''),('peptic ulcer disease','Gastrointestinal','301007008',''),('peptic ulcer disease','Gastrointestinal','245754007',''),('peptic ulcer disease','Gastrointestinal','360372005',''),('peptic ulcer disease','Gastrointestinal','68834009',''),('peptic ulcer disease','Gastrointestinal','275547005',''),('peptic ulcer disease','Gastrointestinal','275548000',''),('peptic ulcer disease','Gastrointestinal','266998003',''),('peptic ulcer disease','Gastrointestinal','235702004',''),('peptic ulcer disease','Gastrointestinal','196775009',''),('peptic ulcer disease','Gastrointestinal','89662003',''),('peptic ulcer disease','Gastrointestinal','16089131000119108',''),('peptic ulcer disease','Gastrointestinal','442805003',''),('peptic ulcer disease','Gastrointestinal','762274007',''),('peptic ulcer disease','Gastrointestinal','708645007',''),('peptic ulcer disease','Gastrointestinal','307190008',''),('peptic ulcer disease','Gastrointestinal','708644006',''),('peptic ulcer disease','Gastrointestinal','31256001',''),('peptic ulcer disease','Gastrointestinal','717879004',''),('peptic ulcer disease','Gastrointestinal','235652004',''),('peptic ulcer disease','Gastrointestinal','313425006',''),('peptic ulcer disease','Gastrointestinal','248891000000103',''),('peptic ulcer disease','Gastrointestinal','76338009',''),('peptic ulcer disease','Gastrointestinal','10699001',''),('peptic ulcer disease','Gastrointestinal','307557003',''),('peptic ulcer disease','Gastrointestinal','226891000000104',''),('peptic ulcer disease','Gastrointestinal','307510004',''),('peptic ulcer disease','Gastrointestinal','307512007',''),('peptic ulcer disease','Gastrointestinal','35892001',''),('peptic ulcer disease','Gastrointestinal','360377004',''),('peptic ulcer disease','Gastrointestinal','235232008',''),('peptic ulcer disease','Gastrointestinal','698496004',''),('peptic ulcer disease','Gastrointestinal','717863000',''),('peptic ulcer disease','Gastrointestinal','13200003',''),('peptic ulcer disease','Gastrointestinal','276525003',''),('peptic ulcer disease','Gastrointestinal','6129004',''),('peptic ulcer disease','Gastrointestinal','398177004',''),('peptic ulcer disease','Gastrointestinal','64121000',''),('peptic ulcer disease','Gastrointestinal','64398008',''),('peptic ulcer disease','Gastrointestinal','55617001',''),('peptic ulcer disease','Gastrointestinal','90489006',''),('peptic ulcer disease','Gastrointestinal','48658001',''),('peptic ulcer disease','Gastrointestinal','26221006',''),('peptic ulcer disease','Gastrointestinal','849611000000106',''),('peptic ulcer disease','Gastrointestinal','88169003',''),('peptic ulcer disease','Gastrointestinal','48336009',''),('peptic ulcer disease','Gastrointestinal','12625009',''),('peptic ulcer disease','Gastrointestinal','37442009',''),('peptic ulcer disease','Gastrointestinal','54157007',''),('peptic ulcer disease','Gastrointestinal','38365000',''),('peptic ulcer disease','Gastrointestinal','78054007',''),('peptic ulcer disease','Gastrointestinal','22620000',''),('peptic ulcer disease','Gastrointestinal','39204006',''),('peptic ulcer disease','Gastrointestinal','196671008',''),('peptic ulcer disease','Gastrointestinal','307556007',''),('peptic ulcer disease','Gastrointestinal','287832000',''),('peptic ulcer disease','Gastrointestinal','235688009',''),('peptic ulcer disease','Gastrointestinal','415624002',''),('peptic ulcer disease','Gastrointestinal','307259004',''),('peptic ulcer disease','Gastrointestinal','307260009',''),('peptic ulcer disease','Gastrointestinal','724532003',''),('peptic ulcer disease','Gastrointestinal','762276009',''),('peptic ulcer disease','Gastrointestinal','724520002',''),('peptic ulcer disease','Gastrointestinal','724521003',''),('peptic ulcer disease','Gastrointestinal','307511000',''),('peptic ulcer disease','Gastrointestinal','314632001',''),('peptic ulcer disease','Gastrointestinal','53132006',''),
('asthma','Respiratory','304527002',''),('asthma','Respiratory','708093000',''),('asthma','Respiratory','708038006',''),('asthma','Respiratory','99031000119107',''),('asthma','Respiratory','442025000',''),('asthma','Respiratory','1751000119100',''),('asthma','Respiratory','708094006',''),('asthma','Respiratory','135181000119109',''),('asthma','Respiratory','135171000119106',''),('asthma','Respiratory','708095007',''),('asthma','Respiratory','708090002',''),('asthma','Respiratory','10674711000119105',''),('asthma','Respiratory','708096008',''),('asthma','Respiratory','10675911000119109',''),('asthma','Respiratory','10675991000119100',''),('asthma','Respiratory','707981009',''),('asthma','Respiratory','10676431000119103',''),('asthma','Respiratory','707980005',''),('asthma','Respiratory','10676511000119109',''),('asthma','Respiratory','10675471000119109',''),('asthma','Respiratory','707979007',''),('asthma','Respiratory','10675551000119104',''),('asthma','Respiratory','733858005',''),('asthma','Respiratory','389145006',''),('asthma','Respiratory','703954005',''),('asthma','Respiratory','703953004',''),('asthma','Respiratory','30352005',''),('asthma','Respiratory','10692681000119108',''),('asthma','Respiratory','407674008',''),('asthma','Respiratory','195967001',''),('asthma','Respiratory','401193004',''),('asthma','Respiratory','10742121000119104',''),('asthma','Respiratory','395022009',''),('asthma','Respiratory','401000119107',''),('asthma','Respiratory','55570000',''),('asthma','Respiratory','10692761000119107',''),('asthma','Respiratory','405944004',''),('asthma','Respiratory','34015007',''),('asthma','Respiratory','225057002',''),('asthma','Respiratory','85761009',''),('asthma','Respiratory','233672007',''),('asthma','Respiratory','404806001',''),('asthma','Respiratory','92807009',''),('asthma','Respiratory','233678006',''),('asthma','Respiratory','866881000000101',''),('asthma','Respiratory','195949008',''),('asthma','Respiratory','10692721000119102',''),('asthma','Respiratory','233687002',''),('asthma','Respiratory','409663006',''),('asthma','Respiratory','41553006',''),('asthma','Respiratory','93432008',''),('asthma','Respiratory','183478001',''),('asthma','Respiratory','281239006',''),('asthma','Respiratory','425969006',''),('asthma','Respiratory','707445000',''),('asthma','Respiratory','707446004',''),('asthma','Respiratory','707447008',''),('asthma','Respiratory','31387002',''),('asthma','Respiratory','63088003',''),('asthma','Respiratory','13151001',''),('asthma','Respiratory','161527007',''),('asthma','Respiratory','233683003',''),('asthma','Respiratory','429258006',''),('asthma','Respiratory','424643009',''),('asthma','Respiratory','427603009',''),('asthma','Respiratory','125021000119107',''),('asthma','Respiratory','1741000119102',''),('asthma','Respiratory','266361008',''),('asthma','Respiratory','12428000',''),('asthma','Respiratory','404808000',''),('asthma','Respiratory','233679003',''),('asthma','Respiratory','1086701000000102',''),('asthma','Respiratory','734904007',''),('asthma','Respiratory','1064821000000109',''),('asthma','Respiratory','1086711000000100',''),('asthma','Respiratory','19849005',''),('asthma','Respiratory','370218001',''),('asthma','Respiratory','427679007',''),('asthma','Respiratory','10675871000119106',''),('asthma','Respiratory','426979002',''),('asthma','Respiratory','125011000119100',''),('asthma','Respiratory','11641008',''),('asthma','Respiratory','195977004',''),('asthma','Respiratory','734905008',''),('asthma','Respiratory','1064811000000103',''),('asthma','Respiratory','370219009',''),('asthma','Respiratory','10676391000119108',''),('asthma','Respiratory','427295004',''),('asthma','Respiratory','125001000119103',''),('asthma','Respiratory','423889005',''),('asthma','Respiratory','370220003',''),('asthma','Respiratory','57607007',''),('asthma','Respiratory','16584951000119101',''),('asthma','Respiratory','404804003',''),('asthma','Respiratory','18041002',''),('asthma','Respiratory','445427006',''),('asthma','Respiratory','370221004',''),('asthma','Respiratory','10675391000119101',''),('asthma','Respiratory','10675431000119106',''),('asthma','Respiratory','426656000',''),('asthma','Respiratory','124991000119109',''),('asthma','Respiratory','10675751000119107',''),('asthma','Respiratory','2360001000004109',''),('asthma','Respiratory','424199006',''),('asthma','Respiratory','233688007',''),('asthma','Respiratory','418395004',''),('asthma','Respiratory','707444001',''),('asthma','Respiratory','707511009',''),('asthma','Respiratory','707512002',''),('asthma','Respiratory','707513007',''),('asthma','Respiratory','59786004',''),('asthma','Respiratory','56968009',''),('asthma','Respiratory','2010031000006100',''),('asthma','Respiratory','2010041000006105','');

IF OBJECT_ID('tempdb..#TempRefCodes') IS NOT NULL DROP TABLE #TempRefCodes;
CREATE TABLE #TempRefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, condition VARCHAR(255) NOT NULL, [group] VARCHAR(255) NOT NULL);



-- Read v2 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcr.condition, dcr.[group]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesreadv2 dcr on dcr.code = rc.MainCode
WHERE CodingType='ReadCodeV2'
and PK_Reference_Coding_ID != -1;

-- CTV3 codes
INSERT INTO #TempRefCodes
SELECT PK_Reference_Coding_ID, dcc.condition, dcc.[group]
FROM [SharedCare].[Reference_Coding] rc
INNER JOIN #codesctv3 dcc on dcc.code = rc.MainCode
WHERE CodingType='CTV3'
and PK_Reference_Coding_ID != -1;

IF OBJECT_ID('tempdb..#TempSNOMEDRefCodes') IS NOT NULL DROP TABLE #TempSNOMEDRefCodes;
CREATE TABLE #TempSNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, condition VARCHAR(255) NOT NULL, [group] VARCHAR(255) NOT NULL);



-- SNOMED codes
INSERT INTO #TempSNOMEDRefCodes
SELECT PK_Reference_SnomedCT_ID, dcs.condition, dcs.[group]
FROM SharedCare.Reference_SnomedCT rs
INNER JOIN #codessnomed dcs on dcs.code = rs.ConceptID;

-- De-duped tables
IF OBJECT_ID('tempdb..#RefCodes') IS NOT NULL DROP TABLE #RefCodes;
IF OBJECT_ID('tempdb..#SNOMEDRefCodes') IS NOT NULL DROP TABLE #SNOMEDRefCodes;
CREATE TABLE #RefCodes (FK_Reference_Coding_ID BIGINT NOT NULL, condition VARCHAR(255) NOT NULL, [group] VARCHAR(255) NOT NULL);
CREATE TABLE #SNOMEDRefCodes (FK_Reference_SnomedCT_ID BIGINT NOT NULL, condition VARCHAR(255) NOT NULL, [group] VARCHAR(255) NOT NULL);

INSERT INTO #RefCodes
SELECT DISTINCT * FROM #TempRefCodes;

INSERT INTO #SNOMEDRefCodes
SELECT DISTINCT * FROM #TempSNOMEDRefCodes;

IF OBJECT_ID('tempdb..#LTCTemp') IS NOT NULL DROP TABLE #LTCTemp;
SELECT DISTINCT FK_Patient_Link_ID, FK_Reference_SnomedCT_ID, FK_Reference_Coding_ID INTO #LTCTemp 
FROM RLS.vw_GP_Events e
WHERE (
	FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #SNOMEDRefCodes) OR
  FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #RefCodes)
)
AND FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND EventDate < @StartDate;

IF OBJECT_ID('tempdb..#PatientsWithLTCs') IS NOT NULL DROP TABLE #PatientsWithLTCs;
SELECT DISTINCT 
  FK_Patient_Link_ID, 
  CASE
    WHEN (
      FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #SNOMEDRefCodes WHERE condition = 'atrial fibrillation') OR
      FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #RefCodes WHERE condition = 'atrial fibrillation')
    ) THEN 'atrial fibrillation'
	  WHEN (
      FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #SNOMEDRefCodes WHERE condition = 'heart failure') OR
      FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #RefCodes WHERE condition = 'heart failure')
    ) THEN 'heart failure'
	  WHEN (
      FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #SNOMEDRefCodes WHERE condition = 'peptic ulcer disease') OR
      FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #RefCodes WHERE condition = 'peptic ulcer disease')
    ) THEN 'peptic ulcer disease'
	  WHEN (
      FK_Reference_SnomedCT_ID IN (SELECT FK_Reference_SnomedCT_ID FROM #SNOMEDRefCodes WHERE condition = 'asthma') OR
      FK_Reference_Coding_ID IN (SELECT FK_Reference_Coding_ID FROM #RefCodes WHERE condition = 'asthma')
    ) THEN 'asthma'
  END AS LTC
INTO #PatientsWithLTCs
FROM #LTCTemp;


--
-- ┌────────────────────────────┐
-- │ GET LTC Groups per patient │
-- └────────────────────────────┘

-- INPUT: Assumes there exists a temp table as follows:
-- #PatientsWithLTCs (FK_Patient_Link_ID, LTC)
-- Therefore this is run after query-patient-ltcs.sql

-- OUTPUT: A temp table with a row for each patient and ltc group combo
-- #LTCGroups (FK_Patient_Link_ID, LTCGroup)

-- Calculate the LTC groups for each patient
IF OBJECT_ID('tempdb..#LTCGroups') IS NOT NULL DROP TABLE #LTCGroups;
SELECT 
  DISTINCT FK_Patient_Link_ID, 
  CASE
    WHEN LTC IN ('atrial fibrillation','heart failure') THEN 'Cardiovascular'
		WHEN LTC IN ('') THEN 'Endocrine'
		WHEN LTC IN ('peptic ulcer disease') THEN 'Gastrointestinal'
		WHEN LTC IN ('') THEN 'Musculoskeletal or Skin'
		WHEN LTC IN ('') THEN 'Neurological'
		WHEN LTC IN ('') THEN 'Psychiatric'
		WHEN LTC IN ('') THEN 'Renal or Urological'
		WHEN LTC IN ('asthma') THEN 'Respiratory'
		WHEN LTC IN ('') THEN 'Sensory Impairment or Learning Disability'
		WHEN LTC IN ('') THEN 'Substance Abuse'
  END AS LTCGroup INTO #LTCGroups
FROM #PatientsWithLTCs;


--┌──────────┐
--│ GET IMDs │
--└──────────┘

-- INPUT: Assumes there exists a temp table as follows:
-- #Patients (FK_Patient_Link_ID)
-- A distinct list of FK_Patient_Link_IDs for each patient in the cohort

-- OUTPUT: A temp table as follows:
-- #PatientIMDDecile (FK_Patient_Link_ID, IMD2019Decile1IsMostDeprived10IsLeastDeprived)
-- 	- FK_Patient_Link_ID - unique patient id
--	- IMD2019Decile1IsMostDeprived10IsLeastDeprived - number 1 to 10 inclusive

-- Get all patients IMD_Score (which is a rank) for the cohort and map to decile
-- (Data on mapping thresholds at: https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019
IF OBJECT_ID('tempdb..#AllPatientIMDDeciles') IS NOT NULL DROP TABLE #AllPatientIMDDeciles;
SELECT 
	FK_Patient_Link_ID,
	FK_Reference_Tenancy_ID,
	HDMModifDate,
	CASE 
		WHEN IMD_Score <= 3284 THEN 1
		WHEN IMD_Score <= 6568 THEN 2
		WHEN IMD_Score <= 9853 THEN 3
		WHEN IMD_Score <= 13137 THEN 4
		WHEN IMD_Score <= 16422 THEN 5
		WHEN IMD_Score <= 19706 THEN 6
		WHEN IMD_Score <= 22990 THEN 7
		WHEN IMD_Score <= 26275 THEN 8
		WHEN IMD_Score <= 29559 THEN 9
		ELSE 10
	END AS IMD2019Decile1IsMostDeprived10IsLeastDeprived 
INTO #AllPatientIMDDeciles
FROM RLS.vw_Patient p
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND IMD_Score IS NOT NULL
AND IMD_Score != -1;
-- 972479 rows
-- 00:00:11

-- If patients have a tenancy id of 2 we take this as their most likely IMD_Score
-- as this is the GP data feed and so most likely to be up to date
IF OBJECT_ID('tempdb..#PatientIMDDecile') IS NOT NULL DROP TABLE #PatientIMDDecile;
SELECT FK_Patient_Link_ID, MIN(IMD2019Decile1IsMostDeprived10IsLeastDeprived) as IMD2019Decile1IsMostDeprived10IsLeastDeprived INTO #PatientIMDDecile FROM #AllPatientIMDDeciles
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND FK_Reference_Tenancy_ID = 2
GROUP BY FK_Patient_Link_ID;
-- 247377 rows
-- 00:00:00

-- Find the patients who remain unmatched
IF OBJECT_ID('tempdb..#UnmatchedPatients') IS NOT NULL DROP TABLE #UnmatchedPatients;
SELECT FK_Patient_Link_ID INTO #UnmatchedPatients FROM #Patients
EXCEPT
SELECT FK_Patient_Link_ID FROM #PatientIMDDecile;
-- 38710 rows
-- 00:00:00

-- If every IMD_Score is the same for all their linked patient ids then we use that
INSERT INTO #PatientIMDDecile
SELECT FK_Patient_Link_ID, MIN(IMD2019Decile1IsMostDeprived10IsLeastDeprived) FROM #AllPatientIMDDeciles
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #UnmatchedPatients)
GROUP BY FK_Patient_Link_ID
HAVING MIN(IMD2019Decile1IsMostDeprived10IsLeastDeprived) = MAX(IMD2019Decile1IsMostDeprived10IsLeastDeprived);
-- 36656
-- 00:00:00

-- Find any still unmatched patients
TRUNCATE TABLE #UnmatchedPatients;
INSERT INTO #UnmatchedPatients
SELECT FK_Patient_Link_ID FROM #Patients
EXCEPT
SELECT FK_Patient_Link_ID FROM #PatientIMDDecile;
-- 2054 rows
-- 00:00:00

-- If there is a unique most recent imd decile then use that
INSERT INTO #PatientIMDDecile
SELECT p.FK_Patient_Link_ID, MIN(p.IMD2019Decile1IsMostDeprived10IsLeastDeprived) FROM #AllPatientIMDDeciles p
INNER JOIN (
	SELECT FK_Patient_Link_ID, MAX(HDMModifDate) MostRecentDate FROM #AllPatientIMDDeciles
	WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #UnmatchedPatients)
	GROUP BY FK_Patient_Link_ID
) sub ON sub.FK_Patient_Link_ID = p.FK_Patient_Link_ID AND sub.MostRecentDate = p.HDMModifDate
GROUP BY p.FK_Patient_Link_ID
HAVING MIN(IMD2019Decile1IsMostDeprived10IsLeastDeprived) = MAX(IMD2019Decile1IsMostDeprived10IsLeastDeprived);
-- 489
-- 00:00:00

--┌─────────────────────────────────────────────┐
--│ GET Secondary Admissions and Length of Stay │
--└─────────────────────────────────────────────┘

-- INPUT: No pre-requisites

-- OUTPUT: Two temp table as follows:
-- #Admissions (FK_Patient_Link_ID, AdmissionDate, AcuteProvider)
-- 	- FK_Patient_Link_ID - unique patient id
--	- AdmissionDate - date of discharge (YYYY-MM-DD)
--	- AcuteProvider - Bolton, SRFT, Stockport etc..
--  (Limited to one admission per person per hospital per day, because if a patient has 2 admissions 
--   on the same day to the same hopsital then it's most likely data duplication rather than two short
--   hospital stays)
-- #LengthOfStay (FK_Patient_Link_ID, AdmissionDate)
-- 	- FK_Patient_Link_ID - unique patient id
--	- AdmissionDate - date of discharge (YYYY-MM-DD)
--	- DischargeDate - date of discharge (YYYY-MM-DD)
--	- LengthOfStay - Number of days between admission and discharge. 1 = [0,1) days, 2 = [1,2) days, etc.

-- Populate temporary table with admissions
-- Convert AdmissionDate to a date to avoid issues where a person has two admissions
-- on the same day (but only one discharge)
IF OBJECT_ID('tempdb..#Admissions') IS NOT NULL DROP TABLE #Admissions;
SELECT DISTINCT FK_Patient_Link_ID, CONVERT(DATE, AdmissionDate) AS AdmissionDate, t.TenancyName AS AcuteProvider INTO #Admissions FROM [RLS].[vw_Acute_Inpatients] i
LEFT OUTER JOIN SharedCare.Reference_Tenancy t ON t.PK_Reference_Tenancy_ID = i.FK_Reference_Tenancy_ID
WHERE EventType = 'Admission'
AND AdmissionDate >= @StartDate;
-- 523477 rows	523477 rows
-- 00:00:19		00:00:15

--┌──────────────────────────┐
--│ GET Secondary Discharges │
--└──────────────────────────┘

-- INPUT: No pre-requisites

-- OUTPUT: A temp table as follows:
-- #Discharges (FK_Patient_Link_ID, DischargeDate, AcuteProvider)
-- 	- FK_Patient_Link_ID - unique patient id
--	- DischargeDate - date of discharge (YYYY-MM-DD)
--	- AcuteProvider - Bolton, SRFT, Stockport etc..
--  (Limited to one discharge per person per hospital per day, because if a patient has 2 discharges 
--   on the same day to the same hopsital then it's most likely data duplication rather than two short
--   hospital stays)

-- Populate temporary table with discharges
IF OBJECT_ID('tempdb..#Discharges') IS NOT NULL DROP TABLE #Discharges;
SELECT DISTINCT FK_Patient_Link_ID, CONVERT(DATE, DischargeDate) AS DischargeDate, t.TenancyName AS AcuteProvider INTO #Discharges FROM [RLS].[vw_Acute_Inpatients] i
LEFT OUTER JOIN SharedCare.Reference_Tenancy t ON t.PK_Reference_Tenancy_ID = i.FK_Reference_Tenancy_ID
WHERE EventType = 'Discharge'
AND DischargeDate >= @StartDate;
-- 535285 rows	535285 rows
-- 00:00:28		00:00:14


-- Link admission with discharge to get length of stay
-- Length of stay is zero-indexed e.g. 
-- 1 = [0,1) days
-- 2 = [1,2) days
IF OBJECT_ID('tempdb..#LengthOfStay') IS NOT NULL DROP TABLE #LengthOfStay;
SELECT 
	a.FK_Patient_Link_ID, a.AdmissionDate, a.AcuteProvider, 
	MIN(d.DischargeDate) AS DischargeDate, 
	1 + DATEDIFF(day,a.AdmissionDate, MIN(d.DischargeDate)) AS LengthOfStay
	INTO #LengthOfStay
FROM #Admissions a
INNER JOIN #Discharges d ON d.FK_Patient_Link_ID = a.FK_Patient_Link_ID AND d.DischargeDate >= a.AdmissionDate AND d.AcuteProvider = a.AcuteProvider
GROUP BY a.FK_Patient_Link_ID, a.AdmissionDate, a.AcuteProvider
ORDER BY a.FK_Patient_Link_ID, a.AdmissionDate, a.AcuteProvider;
-- 511740 rows	511740 rows	
-- 00:00:04		00:00:05


--┌─────────────────────────────────────────────────┐
--│ GET COVID utilisation from secondary admissions │
--└─────────────────────────────────────────────────┘

-- INPUT: Assumes there exists two temp tables as follows:
-- #Patients (FK_Patient_Link_ID)
--  A distinct list of FK_Patient_Link_IDs for each patient in the cohort
-- #Admissions (FK_Patient_Link_ID, AdmissionDate, AcuteProvider)
--  A distinct list of the admissions for each patient in the cohort

-- OUTPUT: A temp table as follows:
-- #COVIDUtilisationAdmissions (FK_Patient_Link_ID, AdmissionDate, AcuteProvider, CovidHealthcareUtilisation)
-- 	- FK_Patient_Link_ID - unique patient id
--	- AdmissionDate - date of discharge (YYYY-MM-DD)
--	- AcuteProvider - Bolton, SRFT, Stockport etc..
--  - CovidHealthcareUtilisation - 'TRUE' if admission within 4 weeks after, or up to 14 days before, a positive test

-- Get first positive covid test for each patient
IF OBJECT_ID('tempdb..#CovidCases') IS NOT NULL DROP TABLE #CovidCases;
SELECT FK_Patient_Link_ID, MIN(CONVERT(DATE, [EventDate])) AS CovidPositiveDate INTO #CovidCases
FROM [RLS].[vw_COVID19]
WHERE FK_Patient_Link_ID IN (SELECT FK_Patient_Link_ID FROM #Patients)
AND GroupDescription = 'Confirmed'
GROUP BY FK_Patient_Link_ID;


IF OBJECT_ID('tempdb..#COVIDUtilisationAdmissions') IS NOT NULL DROP TABLE #COVIDUtilisationAdmissions;
SELECT 
	a.*, 
	CASE
		WHEN c.FK_Patient_Link_ID IS NOT NULL THEN 'TRUE'
		ELSE 'FALSE'
	END AS CovidHealthcareUtilisation
INTO #COVIDUtilisationAdmissions 
FROM #Admissions a
LEFT OUTER join #CovidCases c ON 
	a.FK_Patient_Link_ID = c.FK_Patient_Link_ID 
	AND a.AdmissionDate <= DATEADD(WEEK, 4, c.CovidPositiveDate)
	AND a.AdmissionDate >= DATEADD(DAY, -14, c.CovidPositiveDate);


-- Prepare discharge data
IF OBJECT_ID('tempdb..#FinalDischarges') IS NOT NULL DROP TABLE #FinalDischarges;
SELECT 
	DischargeDate, l.AcuteProvider,	ISNULL(IMD2019Decile1IsMostDeprived10IsLeastDeprived, 0) AS IMD2019Decile1IsMostDeprived10IsLeastDeprived, 
	ISNULL(LTCGroup, 'None') AS LTCGroup, CovidHealthcareUtilisation, count(*) AS NumberDischarged 
	INTO #FinalDischarges
FROM #LengthOfStay l
LEFT OUTER JOIN #COVIDUtilisationAdmissions c ON c.FK_Patient_Link_ID = l.FK_Patient_Link_ID AND c.AdmissionDate = l.AdmissionDate AND c.AcuteProvider = l.AcuteProvider
LEFT OUTER JOIN #LTCGroups ltc ON ltc.FK_Patient_Link_ID = l.FK_Patient_Link_ID
LEFT OUTER JOIN #PatientIMDDecile imd ON imd.FK_Patient_Link_ID = l.FK_Patient_Link_ID
GROUP BY DischargeDate, l.AcuteProvider,IMD2019Decile1IsMostDeprived10IsLeastDeprived, LTCGroup, CovidHealthcareUtilisation;
-- 28764

-- Prepare admission data
IF OBJECT_ID('tempdb..#FinalAdmissions') IS NOT NULL DROP TABLE #FinalAdmissions;
SELECT 
	p.AdmissionDate, p.AcuteProvider, ISNULL(IMD2019Decile1IsMostDeprived10IsLeastDeprived, 0) AS IMD2019Decile1IsMostDeprived10IsLeastDeprived, 
	ISNULL(LTCGroup, 'None') AS LTCGroup, CovidHealthcareUtilisation,
	SUM(CASE WHEN AdmissionType = 'Unplanned' THEN 1 ELSE 0 END) AS NumberUnplannedAdmissions,
	SUM(CASE WHEN AdmissionType = 'Planned' THEN 1 ELSE 0 END) AS NumberPlannedAdmissions,
	SUM(CASE WHEN AdmissionType = 'Maternity' THEN 1 ELSE 0 END) AS NumberMaternityAdmissions,
	SUM(CASE WHEN AdmissionType = 'Transfer' THEN 1 ELSE 0 END) AS NumberTransferAdmissions,
	SUM(CASE WHEN AdmissionType = 'Unknown' THEN 1 ELSE 0 END) AS NumberUnknownAdmissions,
	avg(CAST(l.LengthOfStay AS FLOAT)) AS AverageLengthOfStay
	INTO #FinalAdmissions
FROM #AdmissionTypes p
	LEFT OUTER JOIN #Admissions a ON a.FK_Patient_Link_ID = p.FK_Patient_Link_ID AND a.AdmissionDate = p.AdmissionDate AND a.AcuteProvider = p.AcuteProvider
	LEFT OUTER JOIN #COVIDUtilisationAdmissions c ON c.FK_Patient_Link_ID = p.FK_Patient_Link_ID AND c.AdmissionDate = p.AdmissionDate AND c.AcuteProvider = p.AcuteProvider
	LEFT OUTER JOIN #LengthOfStay l ON l.FK_Patient_Link_ID = p.FK_Patient_Link_ID AND l.AdmissionDate = p.AdmissionDate AND l.AcuteProvider = p.AcuteProvider
	LEFT OUTER JOIN #LTCGroups ltc ON ltc.FK_Patient_Link_ID = p.FK_Patient_Link_ID
	LEFT OUTER JOIN #PatientIMDDecile imd ON imd.FK_Patient_Link_ID = p.FK_Patient_Link_ID
GROUP BY p.AdmissionDate,p.AcuteProvider,IMD2019Decile1IsMostDeprived10IsLeastDeprived, CovidHealthcareUtilisation,LTCGroup;
-- 29833

-- Find unique combinations of data, provider, decile, ltcGroup and covid utilisation
IF OBJECT_ID('tempdb..#CovariateCombinations') IS NOT NULL DROP TABLE #CovariateCombinations;
SELECT DISTINCT DischargeDate AS [Date], AcuteProvider, IMD2019Decile1IsMostDeprived10IsLeastDeprived, LTCGroup, CovidHealthcareUtilisation
INTO #CovariateCombinations
FROM #FinalDischarges
UNION
SELECT DISTINCT AdmissionDate, AcuteProvider,IMD2019Decile1IsMostDeprived10IsLeastDeprived, LTCGroup, CovidHealthcareUtilisation
FROM #FinalAdmissions
--32352

-- Bring it all together for output
SELECT 
	cc.[Date], cc.AcuteProvider, cc.IMD2019Decile1IsMostDeprived10IsLeastDeprived, 
	cc.LTCGroup, cc.CovidHealthcareUtilisation,
	ISNULL(fa.NumberMaternityAdmissions, 0) AS NumberMaternityAdmissions, 
	ISNULL(fa.NumberPlannedAdmissions, 0) AS NumberPlannedAdmissions, 
	ISNULL(fa.NumberTransferAdmissions, 0) AS NumberTransferAdmissions,
	ISNULL(fa.NumberUnknownAdmissions, 0) AS NumberUnknownAdmissions, 
	ISNULL(fa.NumberUnplannedAdmissions, 0) AS NumberUnplannedAdmissions, 
	ISNULL(fd.NumberDischarged, 0) AS NumberDischarged
	FROM #CovariateCombinations cc
LEFT OUTER JOIN #FinalAdmissions fa ON 
	fa.AdmissionDate = cc.[Date] AND
	fa.AcuteProvider = cc.AcuteProvider AND
	fa.IMD2019Decile1IsMostDeprived10IsLeastDeprived = cc.IMD2019Decile1IsMostDeprived10IsLeastDeprived AND
	fa.LTCGroup = cc.LTCGroup AND
	fa.CovidHealthcareUtilisation = cc.CovidHealthcareUtilisation
LEFT OUTER JOIN #FinalDischarges fd ON 
	fd.DischargeDate = cc.[Date] AND
	fd.AcuteProvider = cc.AcuteProvider AND
	fd.IMD2019Decile1IsMostDeprived10IsLeastDeprived = cc.IMD2019Decile1IsMostDeprived10IsLeastDeprived AND
	fd.LTCGroup = cc.LTCGroup AND
	fd.CovidHealthcareUtilisation = cc.CovidHealthcareUtilisation
ORDER BY cc.[Date], cc.AcuteProvider, cc.IMD2019Decile1IsMostDeprived10IsLeastDeprived, cc.LTCGroup, cc.CovidHealthcareUtilisation;