--
--┌────────────────────────────────────────┐
--│ Long-term condition groups per patient │
--└────────────────────────────────────────┘

-- OBJECTIVE: To provide the long-term condition group or groups for each patient. Examples
--            of long term condition groups would be: Cardiovascular, Endocrine, Respiratory

-- INPUT: Assumes there exists a temp table as follows:
-- #PatientsWithLTCs (FK_Patient_Link_ID, LTC)
-- Therefore this is run after query-patient-ltcs.sql

-- OUTPUT: A temp table with a row for each patient and ltc group combo
-- #LTCGroups (FK_Patient_Link_ID, LTCGroup)

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!! DO NOT EDIT THIS FILE MANUALLY - see "node create-ltc-sql.js" !!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-- Calculate the LTC groups for each patient
IF OBJECT_ID('tempdb..#LTCGroups') IS NOT NULL DROP TABLE #LTCGroups;
SELECT 
  DISTINCT FK_Patient_Link_ID, 
  CASE
    WHEN LTC IN ('Cancer') THEN 'Cancer'
		WHEN LTC IN ('Atrial Fibrillation','Coronary Heart Disease','Heart Failure','Hypertension','Peripheral Vascular Disease','Stroke And Tia') THEN 'Cardiovascular'
		WHEN LTC IN ('Diabetes','Thyroid Disorders') THEN 'Endocrine'
		WHEN LTC IN ('Chronic Liver Disease','Diverticular Disease Of Intestine','Inflammatory Bowel Disease','Irritable Bowel Syndrome','Peptic Ulcer Disease') THEN 'Gastrointestinal'
		WHEN LTC IN ('Painful Condition','Psoriasis Or Eczema','Rheumatoid Arthritis And Other Inflammatory Polyarthropathies') THEN 'Musculoskeletal or Skin'
		WHEN LTC IN ('Migraine','Multiple Sclerosis','Parkinsons Disease') THEN 'Neurological'
		WHEN LTC IN ('Anorexia Or Bulimia','Anxiety And Other Somatoform Disorders','Dementia','Depression','Schizophrenia Or Bipolar') THEN 'Psychiatric'
		WHEN LTC IN ('Chronic Kidney Disease','Prostate Disorders') THEN 'Renal or Urological'
		WHEN LTC IN ('Asthma','Bronchiectasis','Chronic Sinusitis','COPD') THEN 'Respiratory'
		WHEN LTC IN ('Blindness And Low Vision','Glaucoma','Hearing Loss','Learning Disability') THEN 'Sensory Impairment or Learning Disability'
		WHEN LTC IN ('Alcohol Problems','Psychoactive Substance Abuse') THEN 'Substance Abuse'
  END AS LTCGroup INTO #LTCGroups
FROM #PatientsWithLTCs;
